#!/usr/bin/env python3
"""Exact verification of reversal factorizations in the Hecke algebra H_6(q).

Setting.  H_n(q) is the type-A Hecke algebra over Z[q] with basis {T_w},
    T_x T_{s_i} = T_{x s_i}                if l(x s_i) > l(x),
    T_x T_{s_i} = q T_{x s_i} + (q-1) T_x  if l(x s_i) < l(x),
and Ctilde_w = sum_{v <= w} P_{v,w}(q) T_v is the modified signless
Kazhdan-Lusztig basis.  For 1 <= a < b <= n, s[a,b] is the longest element of
the parabolic subgroup generated by s_a,...,s_{b-1} and C_{ab} := Ctilde_{s[a,b]}.
For an interval sequence A = ([a_1,b_1],...,[a_m,b_m]),
    I_{i,j} = ([a_i,b_i] cap [a_j,b_j]) \\ union_{i<k<j} [a_k,b_k],
    f_A(q)  = prod_{i<j} [ |I_{i,j}| ]_q!,     [r]_q! = prod_{k=1}^r (1+...+q^{k-1}),
and a reversal factorization of Ctilde_w is an identity
    f_A(q) Ctilde_w = C_{a_1 b_1} ... C_{a_m b_m}.
The conjecture under test asserts that no such identity exists when w contains
the pattern 45312.

TAKEN FROM THE PAPER (inputs, transcribed literally, never re-derived):
  * the seven permutations F = {463152, 526413, 463512, 536412, 562413,
    563142, 563412} and, for each, the interval sequence A of its claimed
    factorization and the claimed prefactor (1+q)^2;
  * the claimed positions of a 45312 occurrence in each element of F;
  * the three intermediate identities C24 C13 = (1+q) Ctilde_431256,
    Ctilde_431256 C46 = Ctilde_431652, Ctilde_431652 C24 = (1+q) Ctilde_463152,
    and the two chain identities Ctilde_463152 C45 = Ctilde_463512,
    C45 Ctilde_463512 = Ctilde_563412;
  * the thirteen-element exclusion set N1 and the six (w, v) pairs with claimed
    P_{v,w}(q) = 1 + q^2;
  * the claimed symmetry orbits of F, and the two symmetries iota, omega;
  * the interval sequence and prefactor (1+q)^4 of the prior-work identity
    for 463152, and the prior-work resolution data I_0, I_1, I_2 and overlaps
    J_1, J_2 quoted in the remark.

DERIVED HERE (everything below is computed by this program, in exact integer
polynomial arithmetic over Z[q]; no floating point is used anywhere):
  * the defining relations of H_6(q) for the multiplication routine itself
    (quadratic, braid, length-additivity, unit, associativity, and agreement of
    the two independent code paths), verified before any identity is trusted;
  * the whole Kazhdan-Lusztig basis of H_6(q) from the mu-recurrence, checked
    against its normalization, positivity, P_{v,w}(0) = 1, agreement of its
    supports with the Bruhat order, two independently known values, the
    smooth-permutation count, and the two symmetries P_{v,w} = P_{v^-1,w^-1} =
    P_{w0 v w0, w0 w w0} (which the construction does not enforce);
  * the census of 45312-containing elements of S_6 and the claimed partition
    of it into sets of sizes 7, 13, 6;
  * f_A(q) for every displayed interval sequence, from the definition, together
    with the paper's claim about which I_{i,j} of row one exceed cardinality one,
    and the splitting of the prior-work parabolics into interval components;
  * that iota reverses products and fixes every C_{ab}, and that transporting
    each displayed interval sequence by iota or omega yields a genuine reversal
    factorization of the image permutation -- the paper's step "applying these
    symmetries gives the remaining four rows";
  * every displayed identity, by multiplying out in the T-basis;
  * the pattern conditions on N1 and the Kazhdan-Lusztig polynomials of the six
    pairs, including the internal zero at q^1;
  * an exhaustive single-edit battery over all seven exhibited interval
    sequences (delete or replace any one factor), plus the uniqueness of each
    row's target inside all of S_6, showing the identity checks can fail;
  * the corollary's parabolic-embedding claim, verified in H_7: the Bruhat
    intervals below the embedded elements stay inside the parabolic, and the
    first factorization is multiplied out again over S_7.
"""

import sys
from itertools import permutations

N = 6
CHECKS = []


def ck(name, ok, detail=""):
    CHECKS.append((name, bool(ok)))
    line = ("PASS " if ok else "FAIL ") + name
    if detail:
        line += " [" + detail + "]"
    print(line)
    return bool(ok)


# ----------------------------------------------------------------- Z[q] arithmetic
ZERO = ()
ONE = (1,)


def pnorm(c):
    c = list(c)
    while c and c[-1] == 0:
        c.pop()
    return tuple(c)


def padd(a, b):
    m = max(len(a), len(b))
    return pnorm([(a[i] if i < len(a) else 0) + (b[i] if i < len(b) else 0)
                  for i in range(m)])


def pscale(a, k):
    if k == 0:
        return ZERO
    return pnorm([k * x for x in a])


def pmul(a, b):
    if not a or not b:
        return ZERO
    out = [0] * (len(a) + len(b) - 1)
    for i, x in enumerate(a):
        if x:
            for j, y in enumerate(b):
                out[i + j] += x * y
    return pnorm(out)


def ppow(a, k):
    r = ONE
    for _ in range(k):
        r = pmul(r, a)
    return r


def qbrack_fact(r):
    """[r]_q! = prod_{k=1}^r (1 + q + ... + q^{k-1}); equals 1 for r in {0,1}."""
    r = int(r)
    out = ONE
    for k in range(1, r + 1):
        out = pmul(out, tuple([1] * k))
    return out


# --------------------------------------------------------- permutations of {1..N}
def ell(w):
    return sum(1 for i in range(len(w)) for j in range(i + 1, len(w)) if w[i] > w[j])


def perm_inverse(w):
    out = [0] * len(w)
    for i, v in enumerate(w):
        out[v - 1] = i + 1
    return tuple(out)


def conj_w0(w):
    n = len(w)
    return tuple(n + 1 - w[n - 1 - i] for i in range(n))


def bruhat_leq(v, w):
    """Standard dot/tableau criterion for v <= w in the Bruhat order."""
    n = len(v)
    for i in range(1, n + 1):
        for j in range(1, n + 1):
            cv = sum(1 for a in range(i) if v[a] >= j)
            cw = sum(1 for a in range(i) if w[a] >= j)
            if cv > cw:
                return False
    return True


def contains_pattern(w, p):
    k = len(p)
    for idx in permutations(range(len(w)), k):
        if list(idx) != sorted(idx):
            continue
        vals = [w[i] for i in idx]
        rank = sorted(range(k), key=lambda t: vals[t])
        rel = [0] * k
        for r, t in enumerate(rank):
            rel[t] = r + 1
        if tuple(rel) == tuple(p):
            return True
    return False


def occurrence_at(w, positions, p):
    """True iff the given 1-based positions of w form an occurrence of pattern p."""
    if list(positions) != sorted(positions) or len(positions) != len(p):
        return False
    vals = [w[i - 1] for i in positions]
    k = len(p)
    rank = sorted(range(k), key=lambda t: vals[t])
    rel = [0] * k
    for r, t in enumerate(rank):
        rel[t] = r + 1
    return tuple(rel) == tuple(p)


# ------------------------------------------------------------- Hecke algebra H_N(q)
# An element is a dict {permutation tuple: Z[q] polynomial}, zero entries pruned.
QPOLY = (0, 1)          # q
QM1 = (-1, 1)           # q - 1


def hadd(X, Y):
    out = dict(X)
    for w, p in Y.items():
        r = padd(out.get(w, ZERO), p)
        if r:
            out[w] = r
        else:
            out.pop(w, None)
    return out


def hscale(X, c):
    out = {}
    for w, p in X.items():
        r = pmul(p, c)
        if r:
            out[w] = r
    return out


def _acc(out, w, p):
    if not p:
        return
    r = padd(out.get(w, ZERO), p)
    if r:
        out[w] = r
    else:
        out.pop(w, None)


def left_mult_s(X, i):
    """T_{s_i} * X.  Left multiplication swaps the VALUES i and i+1."""
    out = {}
    for x, p in X.items():
        y = tuple(i + 1 if v == i else (i if v == i + 1 else v) for v in x)
        if x.index(i) < x.index(i + 1):       # l(s_i x) > l(x)
            _acc(out, y, p)
        else:
            _acc(out, y, pmul(p, QPOLY))
            _acc(out, x, pmul(p, QM1))
    return out


def right_mult_s(X, i):
    """X * T_{s_i}.  Right multiplication swaps POSITIONS i and i+1."""
    out = {}
    for x, p in X.items():
        y = list(x)
        y[i - 1], y[i] = y[i], y[i - 1]
        y = tuple(y)
        if x[i - 1] < x[i]:                   # l(x s_i) > l(x)
            _acc(out, y, p)
        else:
            _acc(out, y, pmul(p, QPOLY))
            _acc(out, x, pmul(p, QM1))
    return out


def hmul(X, Y, n=N):
    """Product X*Y in H_n(q), expanding Y in the T-basis via reduced words."""
    ident = tuple(range(1, n + 1))
    memo = {ident: X}

    def xt(v):
        if v in memo:
            return memo[v]
        for i in range(1, n):
            if v[i - 1] > v[i]:
                vp = list(v)
                vp[i - 1], vp[i] = vp[i], vp[i - 1]
                memo[v] = right_mult_s(xt(tuple(vp)), i)
                return memo[v]
        raise AssertionError("identity handled above")

    out = {}
    for v, p in Y.items():
        for w, r in xt(v).items():
            _acc(out, w, pmul(p, r))
    return out


def hmul_all(factors, n=N):
    out = factors[0]
    for f in factors[1:]:
        out = hmul(out, f, n)
    return out


def build_kl_basis():
    """Ctilde_w for all w in S_N.

    Uses only the defining properties: Ctilde_e = T_e, Ctilde_{s} = T_s + T_e,
    and, for l(s_i w) < l(w) with w' = s_i w, the element Ctilde_{s_i} Ctilde_{w'}
    equals Ctilde_w plus a Z[q]-combination of Ctilde_z with z < w.  The
    combination is pinned down uniquely by the degree bound
    deg P_{z,w} <= (l(w) - l(z) - 1)/2, so we simply strip, from the coefficient
    of each T_z, the part exceeding that bound.  The mu-coefficients are thereby
    derived rather than assumed; CORRECTIONS records them for later inspection.
    """
    ident = tuple(range(1, N + 1))
    perms = sorted(permutations(range(1, N + 1)), key=ell)
    desc = list(reversed(perms))
    C = {ident: {ident: ONE}}
    corrections = []
    for w in perms:
        if w == ident:
            continue
        lw = ell(w)
        i = next(k for k in range(1, N) if w.index(k) > w.index(k + 1))
        wp = tuple(i + 1 if v == i else (i if v == i + 1 else v) for v in w)
        X = hadd(left_mult_s(C[wp], i), C[wp])
        for z in desc:
            if z == w:
                continue
            lz = ell(z)
            if lz >= lw:
                continue
            c = X.get(z, ZERO)
            d = (lw - lz - 1) // 2
            if len(c) <= d + 1:
                continue
            g = pnorm([0] * (d + 1) + list(c[d + 1:]))
            X = hadd(X, hscale(C[z], pscale(g, -1)))
            corrections.append((w, wp, z, g))
        C[w] = X
    return C, corrections


def s_interval(a, b, n=N):
    """Longest element of the parabolic generated by s_a,...,s_{b-1}, inside S_n."""
    w = list(range(1, n + 1))
    w[a - 1:b] = list(reversed(w[a - 1:b]))
    return tuple(w)


def f_A(intervals):
    """f_A(q) computed from the definition, for A = [(a_1,b_1),...,(a_m,b_m)]."""
    sets = [set(range(a, b + 1)) for (a, b) in intervals]
    m = len(sets)
    out = ONE
    for i in range(m):
        for j in range(i + 1, m):
            inter = sets[i] & sets[j]
            for k in range(i + 1, j):
                inter = inter - sets[k]
            out = pmul(out, qbrack_fact(len(inter)))
    return out


# ---------------------------------------------------- inputs taken from the paper
PATTERN = (4, 5, 3, 1, 2)

FACTORABLE = ["463152", "526413", "463512", "536412", "562413", "563142", "563412"]

POSITIONS = {
    "463152": (1, 2, 3, 4, 6),
    "526413": (1, 3, 4, 5, 6),
    "463512": (1, 2, 3, 5, 6),
    "536412": (1, 3, 4, 5, 6),
    "562413": (1, 2, 4, 5, 6),
    "563142": (1, 2, 3, 4, 6),
    "563412": (1, 2, 3, 5, 6),
}

FACTORIZATIONS = {
    "463152": [(2, 4), (1, 3), (4, 6), (2, 4)],
    "526413": [(3, 5), (4, 6), (1, 3), (3, 5)],
    "463512": [(2, 4), (1, 3), (4, 6), (2, 4), (4, 5)],
    "536412": [(2, 3), (3, 5), (1, 3), (4, 6), (3, 5)],
    "562413": [(3, 5), (4, 6), (1, 3), (3, 5), (2, 3)],
    "563142": [(4, 5), (2, 4), (4, 6), (1, 3), (2, 4)],
    "563412": [(4, 5), (2, 4), (1, 3), (4, 6), (2, 4), (4, 5)],
}

N1 = ["156423", "256413", "453126", "453162", "456312", "463125", "465312",
      "516423", "546312", "564123", "564132", "564213", "564312"]

N2_PAIRS = [("356412", "213456"), ("453612", "123465"), ("561423", "213456"),
            ("563124", "123465"), ("564231", "134526"), ("645312", "152346")]

CLAIMED_P = (1, 0, 1)                      # 1 + q^2, with an internal zero at q^1

ORBITS = [{"463152", "526413"},
          {"463512", "536412", "562413", "563142"},
          {"563412"}]

PRIOR_A = [(2, 4), (5, 6), (1, 3), (4, 6), (2, 4), (5, 6)]

LARSON_I = [(2, 3, 5), (1, 2, 4, 5), (2, 3, 5)]     # resolution data, prior work
LARSON_J = [(2, 5), (2, 5)]                          # the claimed overlaps J_1, J_2

CONTROLS = [[(1, 3), (2, 4), (4, 6), (2, 4)],
            [(2, 4), (1, 3), (4, 6)],
            [(2, 4), (1, 3), (3, 5), (2, 4)],
            [(2, 4), (1, 3), (4, 6), (2, 4), (2, 4)],
            [(2, 4), (4, 6), (2, 4), (1, 3), (2, 4)]]


def perm(s):
    return tuple(int(c) for c in s)


# --------------------------------------------------------------------- the checks
def check_hecke_axioms():
    """The multiplication routine used for every displayed identity is validated
    against the defining relations of H_N(q) before it is trusted.  Without this,
    a bug in hmul would silently reproduce itself on both sides of nothing --
    the identity checks below are only as good as this routine."""
    ident = tuple(range(1, N + 1))
    gen = {}
    for i in range(1, N):
        s = list(ident)
        s[i - 1], s[i] = s[i], s[i - 1]
        gen[i] = tuple(s)

    def T(w):
        return {w: ONE}

    quad = all(hmul(T(gen[i]), T(gen[i]))
               == {ident: QPOLY, gen[i]: QM1} for i in range(1, N))
    braid = all(hmul_all([T(gen[i]), T(gen[j]), T(gen[i])])
                == hmul_all([T(gen[j]), T(gen[i]), T(gen[j])])
                for i in range(1, N) for j in range(1, N) if abs(i - j) == 1)
    commute = all(hmul(T(gen[i]), T(gen[j])) == hmul(T(gen[j]), T(gen[i]))
                  for i in range(1, N) for j in range(1, N) if abs(i - j) > 1)
    ck("hecke_quadratic_and_braid_relations", quad and braid and commute,
       "T_s^2 = q T_e + (q-1) T_s: %s; braid: %s; far generators commute: %s"
       % (quad, braid, commute))

    # T_x T_y = T_{xy} whenever lengths add; and T_e is a two-sided unit.
    perms = list(permutations(range(1, N + 1)))
    addit, cnt = True, 0
    for x in perms:
        for y in perms:
            xy = tuple(x[y[k] - 1] for k in range(N))
            if ell(x) + ell(y) == ell(xy):
                cnt += 1
                if hmul(T(x), T(y)) != T(xy):
                    addit = False
    unit = all(hmul(T(ident), T(x)) == T(x) and hmul(T(x), T(ident)) == T(x)
               for x in perms)
    ck("hecke_length_additivity_and_unit", addit and unit and cnt > 0,
       "T_x T_y = T_{xy} on %d length-additive pairs; T_e is a two-sided unit"
       % cnt)

    # Associativity, and agreement of the two independent code paths:
    # left_mult_s (used to build the KL basis) and hmul (used for the identities).
    sample = sorted(perms, key=ell)[::37]
    assoc = all(hmul(hmul(T(x), T(y)), T(z)) == hmul(T(x), hmul(T(y), T(z)))
                for x in sample for y in sample for z in sample)
    agree = all(hmul(T(gen[i]), {x: (1, -2, 3)}) == left_mult_s({x: (1, -2, 3)}, i)
                for i in range(1, N) for x in perms)
    ck("hecke_associativity_and_left_right_paths_agree", assoc and agree,
       "associative on %d triples; hmul(T_s,.) == left_mult_s on all %d T_x"
       % (len(sample) ** 3, len(perms)))


def check_kl_sanity(C, corr):
    ident = tuple(range(1, N + 1))
    w0 = tuple(range(N, 0, -1))
    ok = True
    for i in range(1, N):
        s = list(ident)
        s[i - 1], s[i] = s[i], s[i - 1]
        s = tuple(s)
        if C[s] != {s: ONE, ident: ONE}:
            ok = False
    ok = ok and len(C[w0]) == 720 and all(p == ONE for p in C[w0].values())
    ck("kl_generators_and_longest_element", ok,
       "Ctilde_s = T_s + T_e for %d generators; Ctilde_w0 = sum of all %d T_v"
       % (N - 1, len(C[w0])))

    bad = []
    for w, el in C.items():
        lw = ell(w)
        if el.get(w) != ONE:
            bad.append((w, "leading"))
        for v, p in el.items():
            if p[0] != 1:
                bad.append((v, w, "const"))
            if v != w and len(p) - 1 > (lw - ell(v) - 1) // 2:
                bad.append((v, w, "degree"))
            if any(c < 0 for c in p):
                bad.append((v, w, "negative"))
    ck("kl_degree_bound_positivity_and_constant_term", not bad,
       "P_{w,w}=1, P_{v,w}(0)=1, coefficients >= 0 (all three derived); "
       "deg P_{v,w} <= (l(w)-l(v)-1)/2 holds by construction, since that bound is "
       "what build_kl_basis strips by, so only the first three can fail here"
       if not bad else "%d violations" % len(bad))

    bad = []
    for w, wp, z, g in corr:
        i = next(k for k in range(1, N) if w.index(k) > w.index(k + 1))
        d = ell(wp) - ell(z)
        monomial = sum(1 for c in g if c != 0) == 1
        if not (monomial and g[-1] > 0 and d % 2 == 1
                and len(g) - 1 == (d + 1) // 2
                and z.index(i) > z.index(i + 1)):
            bad.append((w, z, g))
    ck("kl_mu_corrections_are_positive_monomials", corr and not bad,
       "%d corrections, each mu*q^((l(w')-l(z)+1)/2) with mu>0 and s z < z"
       % len(corr))


def check_kl_external(C):
    ident = tuple(range(1, N + 1))
    got1 = C[perm("341256")][ident]
    got2 = C[perm("423156")][ident]
    ck("kl_known_polynomials_3412_and_4231", got1 == (1, 1) and got2 == (1, 1),
       "P_{123456,341256}=%s, P_{123456,423156}=%s (both 1+q)" % (got1, got2))

    allone = set(w for w, el in C.items() if all(p == ONE for p in el.values()))
    smooth = set(w for w in C
                 if not contains_pattern(w, (3, 4, 1, 2))
                 and not contains_pattern(w, (4, 2, 3, 1)))
    ck("kl_trivial_iff_3412_4231_avoiding", allone == smooth and len(smooth) == 366,
       "|{w : all P_{v,w}=1}| = %d = |{w avoiding 3412 and 4231}| = %d"
       % (len(allone), len(smooth)))


def check_census(C):
    census = set(w for w in C if contains_pattern(w, PATTERN))
    ck("census_45312_containing_in_S6_is_26", len(census) == 26,
       "%d permutations of S_6 contain 45312" % len(census))

    f = set(perm(s) for s in FACTORABLE)
    n1 = set(perm(s) for s in N1)
    n2 = set(perm(w) for w, _ in N2_PAIRS)
    sizes = (len(f), len(n1), len(n2))
    disjoint = not (f & n1) and not (f & n2) and not (n1 & n2)
    ck("exclusion_sets_partition_the_census",
       sizes == (7, 13, 6) and disjoint and (f | n1 | n2) == census,
       "sizes %s, pairwise disjoint=%s, union equals census=%s"
       % (str(sizes), disjoint, (f | n1 | n2) == census))

    bad = [s for s in FACTORABLE
           if not occurrence_at(perm(s), POSITIONS.get(s, ()), PATTERN)]
    ck("stated_positions_are_45312_occurrences", not bad,
       "all 7 position tuples realise 45312" if not bad else "bad: %s" % bad)

    sub = sorted(census | {tuple(range(N, 0, -1))})
    bad = []
    for w in sub:
        below = set(v for v in C if bruhat_leq(v, w))
        if set(C[w].keys()) != below:
            bad.append(w)
    ck("kl_support_is_the_bruhat_interval", not bad,
       "support(Ctilde_w) = {v : v <= w} for %d elements" % len(sub))


def check_f_A():
    target = ppow((1, 1), 2)
    bad = []
    for s in FACTORABLE:
        got = f_A(FACTORIZATIONS[s]) if s in FACTORIZATIONS else None
        if got != target:
            bad.append((s, got))
    ck("f_A_equals_one_plus_q_squared_in_every_row", not bad,
       "f_A(q) = (1+q)^2 for all 7 interval sequences" if not bad
       else "bad: %s" % bad)

    # [r]_q! against its closed form for small r, so that f_A above is not being
    # read off a helper that happens to return (1+q)^2 for the wrong reason.
    ck("qbrack_factorials_are_correct",
       qbrack_fact(0) == ONE and qbrack_fact(1) == ONE
       and qbrack_fact(2) == (1, 1) and qbrack_fact(3) == (1, 2, 2, 1),
       "[0]_q!=[1]_q!=1, [2]_q!=1+q, [3]_q!=1+2q+2q^2+q^3")

    # The paper does not merely assert f_A=(1+q)^2 for row 1; it asserts WHICH
    # intersections are large: "the only I_{i,j} of cardinality greater than one
    # are I_{1,2} = I_{2,4} = {2,3}".  Recomputed from the definition here.
    A = FACTORIZATIONS["463152"]
    sets = [set(range(a, b + 1)) for (a, b) in A]
    big = {}
    for i in range(len(A)):
        for j in range(i + 1, len(A)):
            inter = sets[i] & sets[j]
            for k in range(i + 1, j):
                inter = inter - sets[k]
            if len(inter) > 1:
                big[(i + 1, j + 1)] = tuple(sorted(inter))
    ck("row_one_large_intersections_are_exactly_I12_and_I24",
       big == {(1, 2): (2, 3), (2, 4): (2, 3)},
       "|I_{i,j}| > 1 exactly for (i,j) = (1,2) and (2,4), both equal to {2,3}"
       if big == {(1, 2): (2, 3), (2, 4): (2, 3)} else "got %s" % big)


def check_wellformed(C):
    """Every permutation transcribed from the paper must really be one of S_N."""
    names = (list(FACTORABLE) + list(POSITIONS) + list(FACTORIZATIONS) + list(N1)
             + [x for pr in N2_PAIRS for x in pr]
             + ["431256", "431652"] + [x for o in ORBITS for x in o])
    bad = [s for s in names if perm(s) not in C]
    ck("transcribed_words_are_permutations_of_1_to_6", not bad,
       "%d transcribed one-line words, all in S_%d" % (len(names), N)
       if not bad else "not permutations: %s" % sorted(set(bad)))


def eq(X, Y):
    return X is not None and Y is not None and X == Y


def Ct(C, s):
    return C.get(perm(s))


def check_factorizations(C):
    target = ppow((1, 1), 2)
    bad = []
    for s in FACTORABLE:
        A = FACTORIZATIONS.get(s)
        if not A or perm(s) not in C:
            bad.append(s)
            continue
        lhs = hscale(C[perm(s)], target)
        rhs = hmul_all([C[s_interval(a, b)] for (a, b) in A])
        if lhs != rhs:
            bad.append(s)
    ck("seven_reversal_factorizations_hold_exactly", not bad,
       "(1+q)^2 Ctilde_w = product of C_{ab} for all 7 w, in the T-basis"
       if not bad else "failed rows: %s" % bad)

    C24, C13, C46, C45 = (C[s_interval(2, 4)], C[s_interval(1, 3)],
                          C[s_interval(4, 6)], C[s_interval(4, 5)])
    a1, a2, a3 = Ct(C, "431256"), Ct(C, "431652"), Ct(C, "463152")
    e1 = a1 is not None and eq(hmul(C24, C13), hscale(a1, (1, 1)))
    e2 = a1 is not None and eq(hmul(a1, C46), a2)
    e3 = a2 is not None and a3 is not None and eq(hmul(a2, C24), hscale(a3, (1, 1)))
    ck("three_intermediate_identities", e1 and e2 and e3,
       "C24 C13=(1+q)Ct_431256: %s; .C46=Ct_431652: %s; .C24=(1+q)Ct_463152: %s"
       % (e1, e2, e3))

    b1, b2 = Ct(C, "463512"), Ct(C, "563412")
    c1 = a3 is not None and eq(hmul(a3, C45), b1)
    c2 = b1 is not None and eq(hmul(C45, b1), b2)
    ck("two_chain_identities", c1 and c2,
       "Ct_463152 C45 = Ct_463512: %s; C45 Ct_463512 = Ct_563412: %s" % (c1, c2))


def check_symmetry(C):
    F = set(perm(s) for s in FACTORABLE)
    closed = (all(perm_inverse(w) in F for w in F)
              and all(conj_w0(w) in F for w in F))

    seen, orbits = set(), []
    for w in sorted(F):
        if w in seen:
            continue
        o = {w}
        while True:
            t = set(o) | {perm_inverse(x) for x in o} | {conj_w0(x) for x in o}
            if t == o:
                break
            o = t
        seen |= o
        orbits.append(set("".join(map(str, x)) for x in o))
    ck("symmetry_orbits_of_the_factorable_set",
       closed and sorted(map(sorted, orbits)) == sorted(map(sorted, ORBITS)),
       "F closed under w->w^{-1} and w->w0 w w0; orbit sizes %s"
       % sorted(len(o) for o in orbits))

    # omega maps C_{ab} to C_{7-b,7-a}: verified directly on the basis elements
    bad = []
    for a in range(1, N):
        for b in range(a + 1, N + 1):
            if conj_w0(s_interval(a, b)) != s_interval(N + 1 - b, N + 1 - a):
                bad.append((a, b))
    ck("diagram_automorphism_maps_intervals_correctly", not bad,
       "w0 s[a,b] w0 = s[%d-b,%d-a] for all %d intervals"
       % (N + 1, N + 1, N * (N - 1) // 2))

    # The paper asserts iota(Ctilde_w) = Ctilde_{w^{-1}} and omega(Ctilde_w) =
    # Ctilde_{w0 w w0} on the basis itself, i.e. P_{v,w} = P_{v^{-1},w^{-1}} =
    # P_{w0 v w0, w0 w w0}.  Neither is enforced by build_kl_basis (which breaks
    # symmetry by choosing one descent i), so this is an independent global test
    # of the whole computed basis, not a restatement of its construction.
    bad_i = [w for w in C
             if {perm_inverse(v): p for v, p in C[w].items()} != C[perm_inverse(w)]]
    bad_o = [w for w in C
             if {conj_w0(v): p for v, p in C[w].items()} != C[conj_w0(w)]]
    ck("kl_basis_is_stable_under_inverse_and_w0_conjugation",
       not bad_i and not bad_o,
       "P_{v,w} = P_{v^-1,w^-1} = P_{w0 v w0, w0 w w0} for all %d w in S_%d"
       % (len(C), N)
       if not bad_i and not bad_o
       else "inverse violations %d, w0 violations %d" % (len(bad_i), len(bad_o)))

    # iota is an anti-automorphism ("iota reverses products", used by the paper to
    # transport a factorization to its inverse), and each C_{ab} is iota-fixed.
    ivs = [(a, b) for a in range(1, N) for b in range(a + 1, N + 1)]

    def iota(X):
        return {perm_inverse(w): p for w, p in X.items()}

    fixed = all(perm_inverse(s_interval(a, b)) == s_interval(a, b) for (a, b) in ivs)
    anti = all(iota(hmul(C[s_interval(*x)], C[s_interval(*y)]))
               == hmul(iota(C[s_interval(*y)]), iota(C[s_interval(*x)]))
               for x in ivs for y in ivs)
    ck("iota_reverses_products_and_fixes_every_C_ab", fixed and anti,
       "s[a,b]^-1 = s[a,b] for all %d intervals; iota(XY) = iota(Y) iota(X) on all "
       "%d pairs of C_{ab}" % (len(ivs), len(ivs) ** 2))

    # The substance of "applying these symmetries gives the remaining four rows":
    # transport each exhibited interval sequence by iota (reverse the product) and
    # by omega (relabel [a,b] -> [7-b,7-a]) and check that the result really is a
    # reversal factorization of the image permutation, with f_A still (1+q)^2.
    tgt = ppow((1, 1), 2)
    bad, coincide = [], 0
    for s in FACTORABLE:
        A = FACTORIZATIONS[s]
        for B, img in ((list(reversed(A)), perm_inverse(perm(s))),
                       ([(N + 1 - b, N + 1 - a) for (a, b) in A], conj_w0(perm(s)))):
            if img not in F:
                bad.append((s, "image outside F"))
                continue
            if (hmul_all([C[s_interval(a, b)] for (a, b) in B])
                    != hscale(C[img], tgt) or f_A(B) != tgt):
                bad.append((s, B, "".join(map(str, img))))
            if FACTORIZATIONS.get("".join(map(str, img))) == B:
                coincide += 1
    ck("symmetry_transports_each_row_to_a_valid_row_of_the_table", not bad,
       "all 14 iota/omega images of the 7 rows are reversal factorizations of the "
       "image permutation with f_A=(1+q)^2; %d of the 14 reproduce the exhibited "
       "sequence verbatim, the rest are alternative sequences for a self-image row"
       % coincide if not bad else "bad transports: %s" % bad)


def check_exclusions(C):
    bad = []
    for s in N1:
        w = perm(s)
        if contains_pattern(w, (4, 2, 3, 1)) or not contains_pattern(w, (3, 4, 1, 2)):
            bad.append(s)
    ck("N1_avoids_4231_and_contains_3412", len(N1) == 13 and not bad,
       "all 13 elements of N1 avoid 4231 and contain 3412" if not bad
       else "bad: %s" % bad)

    bad = []
    for ws, vs in N2_PAIRS:
        w, v = perm(ws), perm(vs)
        p = C.get(w, {}).get(v, ZERO)
        if not (bruhat_leq(v, w) and v != w and p == CLAIMED_P):
            bad.append((ws, vs, p))
    ck("N2_kazhdan_lusztig_polynomials_have_an_internal_zero",
       len(N2_PAIRS) == 6 and not bad,
       "v < w and P_{v,w} = 1 + q^2 (coefficient of q^1 is zero) in all 6 pairs"
       if not bad else "bad: %s" % bad)


def check_prior_work(C):
    C24, C13, C46, C56 = (C[s_interval(2, 4)], C[s_interval(1, 3)],
                          C[s_interval(4, 6)], C[s_interval(5, 6)])

    # PRIOR_A is transcribed from the paper, but it is meant to be the "split" of
    # Larson's resolution data I_0, I_1, I_2 into connected parabolic components.
    # That step is re-derived here rather than taken on trust.
    def components(gens):
        gens = sorted(gens)
        runs, cur = [], [gens[0]]
        for x in gens[1:]:
            if x == cur[-1] + 1:
                cur.append(x)
            else:
                runs.append(cur)
                cur = [x]
        runs.append(cur)
        return [(r[0], r[-1] + 1) for r in runs]

    split = (components(LARSON_I[0]) + components(LARSON_I[1])
             + components(LARSON_I[2]))
    ck("prior_work_interval_sequence_is_the_split_of_larsons_parabolics",
       split == PRIOR_A and all(set(J) == (set(LARSON_I[k - 1]) & set(LARSON_I[k]))
                                for k, J in ((1, LARSON_J[0]), (2, LARSON_J[1]))),
       "connected components of I_0,I_1,I_2 = %s = the displayed sequence; "
       "J_k = I_{k-1} cap I_k" % (str(split),)
       if split == PRIOR_A else "components %s != displayed %s"
       % (str(split), str(PRIOR_A)))

    fa = f_A(PRIOR_A)
    lhs = hscale(Ct(C, "463152"), ppow((1, 1), 4))
    rhs = hmul_all([C[s_interval(a, b)] for (a, b) in PRIOR_A])
    ck("prior_work_split_identity_for_463152",
       fa == ppow((1, 1), 4) and lhs == rhs,
       "f_A=(1+q)^4: %s; (1+q)^4 Ctilde_463152 = C24 C56 C13 C46 C24 C56: %s"
       % (fa == ppow((1, 1), 4), lhs == rhs))

    absorb = (hmul(C56, C46) == hscale(C46, (1, 1))
              and hmul(C46, C56) == hscale(C46, (1, 1)))
    commute = (hmul(C56, C13) == hmul(C13, C56)
               and hmul(C56, C24) == hmul(C24, C56))
    ck("contraction_relations_used_in_the_reduction", absorb and commute,
       "C56 C46 = C46 C56 = (1+q) C46: %s; C56 commutes with C13 and C24: %s"
       % (absorb, commute))


def check_controls(C):
    base = Ct(C, "463152")
    target = hscale(base, ppow((1, 1), 2))
    row1 = hmul_all([C[s_interval(a, b)] for (a, b) in FACTORIZATIONS["463152"]])
    hits = [A for A in CONTROLS
            if hmul_all([C[s_interval(a, b)] for (a, b) in A]) == target]
    other = [ppow((1, 1), k) for k in (1, 3, 4)]
    wrong_pref = [k for k in other if row1 == hscale(base, k)]
    wrong_w = [s for s in FACTORABLE
               if s != "463152" and Ct(C, s) is not None
               and row1 == hscale(Ct(C, s), ppow((1, 1), 2))]
    ck("identity_test_is_sensitive_to_perturbation",
       not hits and not wrong_pref and not wrong_w,
       "%d mutated interval sequences, %d wrong prefactors and %d wrong targets "
       "all rejected" % (len(CONTROLS), len(other), len(FACTORABLE) - 1))

    # Exhaustive single-edit battery over ALL seven rows: delete any one factor,
    # or replace any one factor by any of the other 15 intervals.  A surviving
    # edit would mean the exhibited interval sequence is not what carries the
    # identity.  An edited sequence counts as a survivor as soon as its product
    # equals (1+q)^2 Ctilde_w, whether or not f_A of the edited sequence is still
    # (1+q)^2: the weaker criterion is the one that could expose a non-sharp
    # identity test, so it is the one applied.
    ivs = [(a, b) for a in range(1, N) for b in range(a + 1, N + 1)]
    tgt = ppow((1, 1), 2)
    edits = 0
    survivors = []
    for s in FACTORABLE:
        A = FACTORIZATIONS[s]
        want = hscale(C[perm(s)], tgt)
        for i in range(len(A)):
            edits += 1
            B = A[:i] + A[i + 1:]
            if hmul_all([C[s_interval(a, b)] for (a, b) in B]) == want:
                survivors.append(("delete", s, i))
            for iv in ivs:
                if iv == A[i]:
                    continue
                edits += 1
                B = list(A)
                B[i] = iv
                if hmul_all([C[s_interval(a, b)] for (a, b) in B]) == want:
                    survivors.append(("replace", s, i, iv, f_A(B) == tgt))
    ck("no_single_edit_of_any_exhibited_interval_sequence_survives",
       edits > 0 and not survivors,
       "%d single edits across the 7 rows, none reproduces (1+q)^2 Ctilde_w"
       % edits if not survivors else "survivors: %s" % survivors)

    # The product of each row determines its target uniquely inside all of S_6,
    # not merely among the seven exhibited permutations.
    bad = []
    for s in FACTORABLE:
        P = hmul_all([C[s_interval(a, b)] for (a, b) in FACTORIZATIONS[s]])
        alt = [w for w in C if w != perm(s) and P == hscale(C[w], tgt)]
        if alt:
            bad.append((s, alt))
    ck("each_row_product_matches_no_other_element_of_S6", not bad,
       "for each of the 7 rows, (1+q)^2 Ctilde_v = product for exactly one of the "
       "%d elements v of S_%d" % (len(C), N)
       if not bad else "ambiguous rows: %s" % bad)


def check_corollary(C):
    bad = []
    for n in range(N + 1, N + 4):
        w = perm("463152") + tuple(range(N + 1, n + 1))
        if not contains_pattern(w, PATTERN):
            bad.append(n)
    inside = all(1 <= a < b <= N for (a, b) in FACTORIZATIONS["463152"])
    ck("corollary_embedding_still_contains_45312", not bad and inside,
       "463152 7...n contains 45312 for n=7,8,9 and row 1 uses only s_1..s_%d"
       % (N - 1))

    # The substance of the corollary is that the first factorization survives the
    # parabolic embedding.  That is verified here in H_7 rather than cited.
    M = N + 1
    row1 = FACTORIZATIONS["463152"]
    keys = [perm("463152")] + [s_interval(a, b) for (a, b) in row1]

    # Step 1: for each relevant w in S_6, the Bruhat interval below its image in
    # S_7 is exactly the image of the interval below w in S_6, and lengths agree.
    # Hence no element outside the parabolic can enter, so the Kazhdan-Lusztig
    # recurrence run in S_7 is literally the same computation as in S_6 and
    # Ctilde_{w 7} is the image of Ctilde_w.  This is derived, not assumed.
    full = list(permutations(range(1, M + 1)))
    bad = []
    for w in keys:
        below7 = set(v for v in full if bruhat_leq(v, w + (M,)))
        below6 = set(v + (M,) for v in C if bruhat_leq(v, w))
        if below7 != below6:
            bad.append(w)
    lens = all(ell(v) == ell(v + (M,)) for v in C)
    ck("bruhat_intervals_below_the_embedded_elements_stay_in_the_parabolic",
       not bad and lens,
       "{v in S_%d : v <= w7} = image of {v in S_%d : v <= w} for the %d relevant "
       "w, and l is unchanged by the embedding" % (M, N, len(keys))
       if not bad and lens else "leaks: %s" % bad)

    # Step 2: multiply the four C_{ab} out in H_7 and compare with the embedding.
    def emb(X):
        return {w + (M,): p for w, p in X.items()}

    prod = hmul_all([emb(C[s_interval(a, b)]) for (a, b) in row1], M)
    lhs = hscale(emb(C[perm("463152")]), ppow((1, 1), 2))
    leaks = [w for w in prod if w[M - 1] != M]
    ck("row_one_factorization_holds_verbatim_in_H_7", prod == lhs and not leaks,
       "(1+q)^2 Ctilde_4631527 = C24 C13 C46 C24 computed in H_%d, with no term "
       "outside the parabolic" % M
       if prod == lhs and not leaks else "H_%d identity failed" % M)


def main():
    check_hecke_axioms()
    C, corr = build_kl_basis()
    check_kl_sanity(C, corr)
    check_kl_external(C)
    check_wellformed(C)
    check_census(C)
    check_f_A()
    check_factorizations(C)
    check_symmetry(C)
    check_exclusions(C)
    check_prior_work(C)
    check_controls(C)
    check_corollary(C)
    print("NOT RE-RUN (each item below is asserted by the paper and is NOT covered "
          "by any check above):")
    print("  1. The 3412-gap values quoted for N1 (2 for twelve elements, 3 for "
          "564312) are not recomputed: the gap statistic is defined in the cited "
          "reference and not in this paper. The gap>1 hypothesis of the cited "
          "Theorem 5.2 is therefore NOT verified here; only 4231-avoidance and "
          "3412-containment are.")
    print("  2. The 'only if' half of the classification -- that the nineteen "
          "remaining elements have NO reversal factorization -- is not re-derived "
          "by an exhaustive search over all interval sequences. This program "
          "verifies only the hypotheses on which the two cited obstruction "
          "theorems act, and neither obstruction theorem itself is reproved here.")
    print("  3. The corollary is stated for every n >= 6, but only n = 7 is "
          "computed (pattern containment is checked for n = 7, 8, 9). The step "
          "from n = 7 to general n rests on the cited parabolic compatibility of "
          "the Kazhdan-Lusztig basis, not on an induction carried out here.")
    print("  4. The degree bound deg P_{v,w} <= (l(w)-l(v)-1)/2 is enforced by the "
          "construction of the basis rather than tested against it; the "
          "independent evidence that the computed basis is the right one is "
          "positivity, P(0)=1, the two known values, the smooth count, the Bruhat "
          "supports, and the inverse/w0 symmetries.")


if __name__ == "__main__":
    main()
    nfail = sum(1 for _, ok in CHECKS if not ok)
    n = len(CHECKS)
    if nfail:
        print("VERDICT: %d OF %d CHECKS FAILED" % (nfail, n))
    else:
        print("VERDICT: ALL %d CHECKS PASS" % n)
    sys.exit(1 if nfail else 0)
