#!/usr/bin/env python3
"""Verification of a complete-intersection Tor-length counterexample.

The conjecture under test: if (R,m) is regular local of dimension n, I is
generated by a regular sequence of length k <= n-1 and J by a regular
sequence of length n, then length(Tor_i(R/I,R/J)) = C(k,i)*length(R/(I+J))
for 0 <= i <= k; together with the companion lower bound and the total
bound sum_i length(Tor_i) >= 2^k * length(R/(I+J)).

TAKEN FROM THE PAPER (inputs, transcribed verbatim, never used as evidence
for themselves):
  * the ambient ring S = Q[x,y,z,w], n = 4, k = 3;
  * the exhibited ideals
      I_S = (x^2+xw, y^2+yw, z^2+zw),
      J_S = (x^2+xy, xz+z^2, y^2+yz, xw+w^2);
  * the ten Grobner basis elements listed for I_S+J_S and the eight standard
    monomials 1, x, y, z, w, w^2, yw, zw;
  * the asserted numbers, held only as comparison targets: colength 8, Tor
    length vector (8,22,22,8), Hilbert function (1,4,3,0,0) of S/(I_S+J_S),
    and Hilbert series 8t^3 + 14t^4 of (I_S cap J_S)/(I_S J_S).

DERIVED HERE (computed from the ideals alone, by exact rational linear
algebra on graded pieces -- no value below is read from the paper):
  * Hilbert functions of S/I_S, S/J_S and S/(I_S+J_S), each as
    dim S_d - dim (ideal)_d via row reduction over Q; compared against the
    Koszul-numerator prediction for a complete intersection of quadrics,
    which certifies both height claims and hence both regular sequences;
  * artinian-ness of S/J_S, giving m^5 subset J_S and radical J_S = m;
  * colength(S/(I_S+J_S)) = 8;
  * the full Grobner claim, via Macaulay's basis criterion: every listed basis
    element lies in I_S+J_S, the listed elements generate I_S+J_S degreewise,
    their grevlex leading terms cut out exactly the eight listed standard
    monomials, and those eight are linearly independent modulo I_S+J_S;
  * the full Tor length vector, as the homology of the Koszul complex on the
    three generators of I_S tensored with the 16-dimensional algebra
    S/J_S (the Koszul complex resolves S/I_S because those generators are a
    regular sequence), from exact ranks of the three differentials;
  * the graded pieces of Tor_1 by a second, independent route:
    dim(I cap J)_d = dim I_d + dim J_d - dim (I+J)_d minus dim (I_S J_S)_d;
  * the vanishing of Tor_i for i >= 4, by exhibiting an element g of J_S that
    is a nonzerodivisor on S/I_S -- certified completely and finitely by
    S/(I_S+(g)) being artinian, since S/I_S is a 1-dimensional complete
    intersection and hence unmixed -- so that (0 :_{S/I_S} J_S) = 0 (no single
    generator of J_S works: each of the four factors);
  * the three failing statements of the corollary, formed from the DERIVED
    vector and the DERIVED colength: the equality of Conjecture 4.2, the
    degreewise lower bound of Question 5.1 (refuted by the same strict
    inequality, since the paper's ideals are an instance of that question's
    weaker hypothesis), and the total bound of Question 5.4 -- whose sum runs
    to i = n, so the vanishing certificate for i > k is a conjunct of that
    check rather than an assumption made elsewhere;
  * a positive control on monomial complete intersections where the
    conjectured equality does hold, so that a systematic undercount by this
    machinery would surface.

NOT re-run here: the passage from the graded ring to its localisation at the
maximal ideal (all modules involved have finite length, so the paper's
localisation step preserves them) -- so every length printed is an exact
Q-dimension over S and not an ell_R over R = S_m, and the paper's theorem,
stated entirely over R, is reached only through that untested step; the
citation-level appeal to Koszul duality, whose conclusion is instead checked
numerically; the degrees above the tabulated range for the second route to
Tor_1; and, the widest gap, the CONTENT and NUMBERING of the refuted
statements -- the shape of the conjectured equality and of the total bound and
the labels Conjecture 4.2, Question 5.1, Question 5.4, Proposition 1.9 come
from the paper, and the cited article itself (DOI and arXiv number included) is
never opened here, so no check in this file can detect a misattribution.  The
final run prints all four gaps in a single closing paragraph, together with the
count of checks that are mere restatements of an earlier one, so the printed
total is not read as 22 independent derivations.

Standard library only; exact integer and Fraction arithmetic throughout, no
floating point anywhere.
"""

from fractions import Fraction

NVARS = 4          # x, y, z, w
VARNAMES = "xyzw"
DMAX = 7           # top degree tabulated for every graded computation below;
                   # quoted verbatim in the closing scope disclosure

# ---- exhibited object, transcribed from the statement of the theorem -------
# Ideals of S = Q[x,y,z,w].  A polynomial is a dict {exponent tuple: coeff}.
# Exponent order is (x, y, z, w).

def mono(x=0, y=0, z=0, w=0):
    return (x, y, z, w)


def poly(*terms):
    p = {}
    for coeff, ex in terms:
        p[ex] = p.get(ex, Fraction(0)) + Fraction(coeff)
    return {e: c for e, c in p.items() if c != 0}


# I_S = (x^2 + xw, y^2 + yw, z^2 + zw)
GENS_I = [
    poly((1, mono(x=2)), (1, mono(x=1, w=1))),
    poly((1, mono(y=2)), (1, mono(y=1, w=1))),
    poly((1, mono(z=2)), (1, mono(z=1, w=1))),
]

# J_S = (x^2 + xy, xz + z^2, y^2 + yz, xw + w^2)
GENS_J = [
    poly((1, mono(x=2)), (1, mono(x=1, y=1))),
    poly((1, mono(x=1, z=1)), (1, mono(z=2))),
    poly((1, mono(y=2)), (1, mono(y=1, z=1))),
    poly((1, mono(x=1, w=1)), (1, mono(w=2))),
]

CHECKS = []


def ck(name, ok, detail=""):
    CHECKS.append((name, bool(ok)))
    tag = "PASS" if ok else "FAIL"
    if detail:
        print("%s %s [%s]" % (tag, name, detail))
    else:
        print("%s %s" % (tag, name))
    return bool(ok)


# ---- graded linear algebra over Q -----------------------------------------

_MONS = {}


def monomials(d):
    """All monomials of S of total degree d, in a fixed deterministic order."""
    if d < 0:
        return []
    if d in _MONS:
        return _MONS[d]
    out = []
    for a in range(d, -1, -1):
        for b in range(d - a, -1, -1):
            for c in range(d - a - b, -1, -1):
                out.append((a, b, c, d - a - b - c))
    _MONS[d] = out
    return out


def mindex(d):
    return {m: i for i, m in enumerate(monomials(d))}


def pmul(p, q):
    r = {}
    for e1, c1 in p.items():
        for e2, c2 in q.items():
            e = (e1[0] + e2[0], e1[1] + e2[1], e1[2] + e2[2], e1[3] + e2[3])
            r[e] = r.get(e, Fraction(0)) + c1 * c2
    return {e: c for e, c in r.items() if c != 0}


def pdeg(p):
    return max(sum(e) for e in p)


def echelon(rows, ncols):
    """Row-reduce (list of dense Fraction lists) to reduced row echelon form.

    Returns (rows, pivot_columns)."""
    rows = [list(r) for r in rows]
    piv = []
    r = 0
    for c in range(ncols):
        sel = None
        for i in range(r, len(rows)):
            if rows[i][c] != 0:
                sel = i
                break
        if sel is None:
            continue
        rows[r], rows[sel] = rows[sel], rows[r]
        inv = Fraction(1, 1) / rows[r][c]
        rows[r] = [v * inv for v in rows[r]]
        for i in range(len(rows)):
            if i != r and rows[i][c] != 0:
                f = rows[i][c]
                rows[i] = [a - f * b for a, b in zip(rows[i], rows[r])]
        piv.append(c)
        r += 1
        if r == len(rows):
            break
    return rows[:r], piv


def rank(rows, ncols):
    return len(echelon(rows, ncols)[1])


def ideal_degree_rows(gens, d):
    """Dense rows spanning the degree-d piece of the ideal generated by gens."""
    idx = mindex(d)
    rows = []
    for g in gens:
        dg = pdeg(g)
        if dg > d:
            continue
        for m in monomials(d - dg):
            prod = pmul(g, {m: Fraction(1)})
            row = [Fraction(0)] * len(idx)
            for e, c in prod.items():
                row[idx[e]] = c
            rows.append(row)
    return rows


def ideal_dim(gens, d):
    return rank(ideal_degree_rows(gens, d), len(monomials(d)))


def hilbert_function(gens, dmax):
    """HF of S/(gens) in degrees 0..dmax, by exact rank computation."""
    return [len(monomials(d)) - ideal_dim(gens, d) for d in range(dmax + 1)]


# ---- the finite-dimensional algebra A = S/J_S ------------------------------

class Quotient(object):
    """S/(gens) as a graded Q-vector space with an exact normal form."""

    def __init__(self, gens, dmax):
        self.dmax = dmax
        self.ech = {}
        self.pivots = {}
        self.basis_by_deg = {}
        for d in range(dmax + 1):
            ncols = len(monomials(d))
            rows, piv = echelon(ideal_degree_rows(gens, d), ncols)
            self.ech[d] = rows
            self.pivots[d] = piv
            pset = set(piv)
            self.basis_by_deg[d] = [c for c in range(ncols) if c not in pset]
        self.basis = []
        self.offset = {}
        for d in range(dmax + 1):
            self.offset[d] = len(self.basis)
            for c in self.basis_by_deg[d]:
                self.basis.append((d, monomials(d)[c]))
        self.dim = len(self.basis)

    def reduce_degree(self, vec, d):
        """Coordinates of a degree-d vector in the chosen basis of A_d."""
        if d > self.dmax:
            # No echelon form was built above dmax, so nothing can be decided
            # here: refuse rather than silently report the class as zero.
            if any(v != 0 for v in vec):
                raise ValueError("degree %d exceeds dmax=%d; the quotient was "
                                 "not tabulated that far, so this class cannot "
                                 "be reduced" % (d, self.dmax))
            return []
        vec = list(vec)
        for row, c in zip(self.ech[d], self.pivots[d]):
            if vec[c] != 0:
                f = vec[c]
                vec = [a - f * b for a, b in zip(vec, row)]
        return [vec[c] for c in self.basis_by_deg[d]]

    def class_of(self, p):
        """Normal-form coordinate vector (length self.dim) of a polynomial."""
        out = [Fraction(0)] * self.dim
        bydeg = {}
        for e, c in p.items():
            bydeg.setdefault(sum(e), {})[e] = c
        for d, part in bydeg.items():
            if d > self.dmax:
                dense = [Fraction(0)] * len(monomials(d))
                idx = mindex(d)
                for e, c in part.items():
                    dense[idx[e]] = c
                self.reduce_degree(dense, d)   # raises if genuinely nonzero
                continue
            dense = [Fraction(0)] * len(monomials(d))
            idx = mindex(d)
            for e, c in part.items():
                dense[idx[e]] = c
            coords = self.reduce_degree(dense, d)
            for k, v in enumerate(coords):
                out[self.offset[d] + k] = v
        return out

    def mult_matrix(self, f):
        """Rows[j] = coordinates of f * b_j, for basis element b_j."""
        rows = []
        for (d, m) in self.basis:
            rows.append(self.class_of(pmul(f, {m: Fraction(1)})))
        return rows


# ---- Koszul homology H_i(f1,f2,f3 ; A) = Tor_i(S/I_S, S/J_S) --------------
# The Koszul complex on a regular sequence f1,f2,f3 is a free resolution of
# S/I_S, so tensoring it with S/J_S and taking homology yields Tor.

def koszul_matrices(Q, mats):
    n = Q.dim
    zero = [Fraction(0)] * n

    def blk(parts):
        out = []
        for p in parts:
            out.extend(p)
        return out

    # d1 : A^3 -> A      (a e_i |-> f_i a)
    d1 = []
    for i in range(3):
        for j in range(n):
            d1.append(list(mats[i][j]))

    pairs = [(0, 1), (0, 2), (1, 2)]
    # d2 : A^3 (wedge pairs) -> A^3   (a e_i^e_j |-> f_i a e_j - f_j a e_i)
    d2 = []
    for (i, k) in pairs:
        for j in range(n):
            slots = [list(zero), list(zero), list(zero)]
            slots[k] = list(mats[i][j])
            slots[i] = [-v for v in mats[k][j]]
            d2.append(blk(slots))

    # d3 : A -> A^3 (wedge pairs)
    #   a e1^e2^e3 |-> f1 a (e2^e3) - f2 a (e1^e3) + f3 a (e1^e2)
    d3 = []
    signs = [(2, 0, Fraction(1)), (1, 1, Fraction(-1)), (0, 2, Fraction(1))]
    for j in range(n):
        slots = [list(zero), list(zero), list(zero)]
        for slot, fi, sg in signs:
            slots[slot] = [sg * v for v in mats[fi][j]]
        d3.append(blk(slots))
    return d1, d2, d3


def compose(rowsA, rowsB, ncolsB):
    """Matrix product where rows are images of basis vectors."""
    out = []
    for r in rowsA:
        acc = [Fraction(0)] * ncolsB
        for c, v in enumerate(r):
            if v != 0:
                rb = rowsB[c]
                for k in range(ncolsB):
                    if rb[k] != 0:
                        acc[k] += v * rb[k]
        out.append(acc)
    return out


# ---- the Gröbner data printed in the paper --------------------------------
# Generators of the initial-ideal-basis list for I_S + J_S, transcribed:
#   x^2-w^2, xy+w^2, y^2+yw, xz-zw, yz-yw, z^2+zw, xw+w^2, w^2 y, w^2 z, w^3
PAPER_GB = [
    poly((1, mono(x=2)), (-1, mono(w=2))),
    poly((1, mono(x=1, y=1)), (1, mono(w=2))),
    poly((1, mono(y=2)), (1, mono(y=1, w=1))),
    poly((1, mono(x=1, z=1)), (-1, mono(z=1, w=1))),
    poly((1, mono(y=1, z=1)), (-1, mono(y=1, w=1))),
    poly((1, mono(z=2)), (1, mono(z=1, w=1))),
    poly((1, mono(x=1, w=1)), (1, mono(w=2))),
    poly((1, mono(y=1, w=2)),),
    poly((1, mono(z=1, w=2)),),
    poly((1, mono(w=3)),),
]

# Standard monomials printed in the paper: 1, x, y, z, w, w^2, yw, zw
PAPER_STD = [
    mono(), mono(x=1), mono(y=1), mono(z=1), mono(w=1),
    mono(w=2), mono(y=1, w=1), mono(z=1, w=1),
]

# Values transcribed from the paper's statements (targets, never recomputed
# from themselves: each is compared against an independent computation).
CLAIM_COLENGTH = 8
CLAIM_TOR = (8, 22, 22, 8)
CLAIM_TOR1_HS = {3: 8, 4: 14}
CLAIM_HF_I_PLUS_J = [1, 4, 3, 0, 0]
K_LEN = 3          # length of the regular sequence generating I
N_DIM = 4          # dimension of the regular local ring


def grevlex_key(e):
    """Sort key realising graded reverse lex with x > y > z > w.

    Larger key = larger monomial: first by total degree, then by the rightmost
    differing exponent being *smaller* (that is grevlex)."""
    return (sum(e), tuple(-v for v in reversed(e)))


def leading_monomial(p):
    return max(p, key=grevlex_key)


def divides(a, b):
    return all(a[i] <= b[i] for i in range(NVARS))


def binom(n, k):
    if k < 0 or k > n:
        return 0
    r = 1
    for i in range(k):
        r = r * (n - i) // (i + 1)
    return r


def ci_hilbert_function(degrees, nvars, dmax):
    """HF of S/(regular sequence of the given degrees), from the Koszul
    numerator (1-t^d1)...(1-t^dk) divided by (1-t)^nvars, as exact integers."""
    num = [1] + [0] * dmax
    for d in degrees:
        new = list(num)
        for i in range(dmax + 1 - d):
            new[i + d] -= num[i]
        num = new
    for _ in range(nvars):
        acc = 0
        out = []
        for i in range(dmax + 1):
            acc += num[i]
            out.append(acc)
        num = out
    return num


def check_transcription(DMAX):
    ok = len(GENS_I) == K_LEN and len(GENS_J) == N_DIM
    for g in GENS_I + GENS_J:
        ok = ok and len(g) == 2
        ok = ok and all(sum(e) == 2 for e in g)
        ok = ok and all(c == 1 for c in g.values())
    ck("transcription.generators_are_quadratic_binomials", ok,
       "%d + %d homogeneous quadrics, unit coefficients"
       % (len(GENS_I), len(GENS_J)))
    # A product of nonzero polynomials in the domain Q[x,y,z,w] is never zero,
    # so "the products are nonzero" is unfalsifiable and proves nothing.  What
    # is genuinely at stake is that the two ideals are in general position:
    # no generator of either lies in the other, so I+J is strictly bigger than
    # both and I cap J is strictly bigger than I*J (else Tor_1 would vanish).
    QI = Quotient(GENS_I, DMAX)
    QJ = Quotient(GENS_J, DMAX)
    i_in_j = [k for k, f in enumerate(GENS_I)
              if all(v == 0 for v in QJ.class_of(f))]
    j_in_i = [k for k, f in enumerate(GENS_J)
              if all(v == 0 for v in QI.class_of(f))]
    ck("transcription.neither_ideal_contains_a_generator_of_the_other",
       not i_in_j and not j_in_i,
       "generators of I_S inside J_S: %s; of J_S inside I_S: %s"
       % (i_in_j or "none", j_in_i or "none"))


def check_regular_sequences(DMAX):
    hf_i = hilbert_function(GENS_I, DMAX)
    pred_i = ci_hilbert_function([2] * K_LEN, NVARS, DMAX)
    ck("I.hilbert_function_is_that_of_a_complete_intersection",
       hf_i == pred_i,
       "HF(S/I_S)=%s vs Koszul prediction %s" % (hf_i[:6], pred_i[:6]))
    # dim S/I_S = 1 (constant HF 8 = 2^3), so height I_S = 3 = #generators;
    # in the Cohen-Macaulay ring S this forces a regular sequence.
    tail = set(hf_i[K_LEN:])
    ck("I.has_height_three_so_generators_form_a_regular_sequence",
       tail == set([2 ** K_LEN]),
       "HF constant %s in degrees %d..%d" % (sorted(tail), K_LEN, DMAX))

    hf_j = hilbert_function(GENS_J, DMAX)
    pred_j = ci_hilbert_function([2] * N_DIM, NVARS, DMAX)
    ck("J.hilbert_function_is_that_of_a_complete_intersection",
       hf_j == pred_j and sum(hf_j) == 2 ** N_DIM,
       "HF(S/J_S)=%s, length %d" % (hf_j[:6], sum(hf_j)))
    # J_S artinian: once HF vanishes in degree d it vanishes forever, since
    # S_1*(S_d) = S_{d+1}; so m^d is contained in J_S and sqrt(J_S) = m.
    zero_from = None
    for d, v in enumerate(hf_j):
        if v == 0:
            zero_from = d
            break
    ck("J.is_m_primary_radical_is_the_maximal_ideal",
       zero_from is not None and all(v == 0 for v in hf_j[zero_from:]),
       "m^%s contained in J_S" % zero_from)
    return hf_i, hf_j


def check_colength(DMAX):
    gens = GENS_I + GENS_J
    hf = hilbert_function(gens, DMAX)
    ck("sum.hilbert_function_of_S_mod_I_plus_J",
       hf[:len(CLAIM_HF_I_PLUS_J)] == CLAIM_HF_I_PLUS_J
       and all(v == 0 for v in hf[len(CLAIM_HF_I_PLUS_J):]),
       "HF=%s" % hf)
    colen = sum(hf)
    ck("sum.colength_equals_eight", colen == CLAIM_COLENGTH,
       "length(S/(I_S+J_S)) = %d" % colen)

    Q = Quotient(gens, DMAX)
    inside = [i for i, g in enumerate(PAPER_GB)
              if all(v == 0 for v in Q.class_of(g))]
    ck("grobner.listed_basis_elements_lie_in_the_ideal",
       len(inside) == len(PAPER_GB),
       "%d of %d reduce to zero modulo I_S+J_S"
       % (len(inside), len(PAPER_GB)))

    # Membership alone only shows (PAPER_GB) is contained in I_S+J_S.  For the
    # list to be a Grobner *basis* of I_S+J_S it must also generate it.
    # Equal graded dimensions are conclusive only TOGETHER with the containment
    # check above: containment plus equal dimension in every degree gives
    # equality of the two ideals.  On its own this check is passable by an
    # unrelated ideal of the same Hilbert function, so both must hold.
    same = [d for d in range(DMAX + 1)
            if ideal_dim(PAPER_GB, d) == ideal_dim(gens, d)]
    ck("grobner.listed_basis_generates_the_whole_ideal",
       len(same) == DMAX + 1,
       "dim (PAPER_GB)_d = dim (I_S+J_S)_d in degrees %s" % same)

    rows = [Q.class_of({t: Fraction(1)}) for t in PAPER_STD]
    r = rank(rows, Q.dim)
    ck("grobner.standard_monomials_are_a_basis_of_the_quotient",
       r == len(PAPER_STD) and r == colen,
       "%d listed monomials, rank %d, colength %d"
       % (len(PAPER_STD), r, colen))

    # Macaulay's basis criterion: PAPER_GB lies in the ideal, generates it, and
    # the monomials outside the ideal spanned by its grevlex leading terms are
    # exactly the listed standard monomials -- and there are colength-many of
    # them.  That certifies the paper's Grobner claim, not just membership.
    lms = [leading_monomial(p) for p in PAPER_GB]
    std, empty_from = [], None
    for d in range(DMAX + 1):
        here = [m for m in monomials(d)
                if not any(divides(l, m) for l in lms)]
        std.extend(here)
        if not here and empty_from is None:
            empty_from = d
    # The complement of a monomial ideal is closed under division, so once a
    # whole degree is absent no higher degree can contribute.
    ck("grobner.grevlex_leading_terms_cut_out_exactly_the_listed_standard_monomials",
       sorted(std) == sorted(PAPER_STD) and len(std) == colen
       and empty_from is not None,
       "%d standard monomials, first empty degree %s, colength %d"
       % (len(std), empty_from, colen))
    return colen


def tor_lengths(gens_reg, gens_other, DMAX):
    """Lengths of Tor_i(S/(gens_reg), S/(gens_other)) for i = 0..3, as the
    homology of the Koszul complex on gens_reg tensored with the quotient."""
    Q = Quotient(gens_other, DMAX)
    shift = max(pdeg(f) for f in gens_reg)
    topdeg = max([d for d in range(DMAX + 1) if Q.basis_by_deg[d]] + [-1])
    if topdeg < 0 or topdeg + shift > DMAX:
        raise ValueError("second quotient is not known to have finite length "
                         "(top nonzero degree %d of %d); Koszul route needs "
                         "room for multiplication by degree %d"
                         % (topdeg, DMAX, shift))
    mats = [Q.mult_matrix(f) for f in gens_reg]
    d1, d2, d3 = koszul_matrices(Q, mats)
    n = Q.dim
    r1 = rank(d1, n)
    r2 = rank(d2, 3 * n)
    r3 = rank(d3, 3 * n)
    homology = [n - r1, (3 * n - r1) - r2, (3 * n - r2) - r3, n - r3]
    return homology, (d1, d2, d3), Q


def check_tor(colen):
    tor, (d1, d2, d3), Q = tor_lengths(GENS_I, GENS_J, 6)
    n = Q.dim
    z1 = compose(d2, d1, n)
    z2 = compose(d3, d2, 3 * n)
    ck("koszul.tensored_complex_composes_to_zero",
       all(v == 0 for r in z1 for v in r)
       and all(v == 0 for r in z2 for v in r),
       "d1 d2 = 0 and d2 d3 = 0 over the %d-dimensional quotient" % n)
    ck("tor.length_vector_is_8_22_22_8", tuple(tor) == CLAIM_TOR,
       "computed %s" % (tuple(tor),))
    ck("tor.degree_zero_term_matches_the_colength",
       tor[0] == colen,
       "H_0 = %d, length(S/(I_S+J_S)) = %d" % (tor[0], colen))
    ck("tor.vector_is_symmetric_under_koszul_duality",
       all(tor[i] == tor[K_LEN - i] for i in range(K_LEN + 1)),
       "%s reversed is %s" % (tor, tor[::-1]))
    return tor


def check_tor1_hilbert_series(tor, DMAX):
    """HS of (I_S cap J_S)/(I_S J_S) = Tor_1, degree by degree.

    dim (I cap J)_d = dim I_d + dim J_d - dim (I+J)_d, all exact ranks."""
    prod = [pmul(f, g) for f in GENS_I for g in GENS_J]
    hs = {}
    for d in range(DMAX + 1):
        cap = (ideal_dim(GENS_I, d) + ideal_dim(GENS_J, d)
               - ideal_dim(GENS_I + GENS_J, d))
        val = cap - ideal_dim(prod, d)
        if val:
            hs[d] = val
    ck("tor1.hilbert_series_is_8t3_plus_14t4", hs == CLAIM_TOR1_HS,
       "computed %s over degrees 0..%d"
       % (sorted(hs.items()), DMAX))
    ck("tor1.two_independent_computations_agree",
       sum(hs.values()) == tor[1] == CLAIM_TOR[1],
       "intersection route %d, Koszul route %d"
       % (sum(hs.values()), tor[1]))
    return hs


def check_consequences(tor, colen, higher_tor_vanishes):
    predicted = [binom(K_LEN, i) * colen for i in range(K_LEN + 1)]
    strict = [i for i in range(K_LEN + 1) if tor[i] < predicted[i]]
    # The same strict inequality settles two of the paper's three claims: it
    # contradicts the equality of Conjecture 4.2 and, a fortiori, the
    # degreewise LOWER bound asked for in Question 5.1 (whose hypothesis is
    # weaker -- the ideals need only CONTAIN regular sequences of lengths k
    # and n -- so an example generated by regular sequences is an instance).
    ck("consequence.conjecture_4_2_and_question_5_1_lower_bound_fail",
       len(strict) > 0
       and all(tor[i] == predicted[i] for i in range(K_LEN + 1)
               if i not in strict),
       "Tor=%s, conjectured %s, strictly smaller at i=%s -- refutes the "
       "equality of Conjecture 4.2 and the lower bound of Question 5.1"
       % (tor, predicted, strict))
    # Question 5.4's sum runs over i = 0..n, not 0..k.  Summing only the first
    # k+1 terms would UNDERCOUNT the left side and so make the bound easier to
    # violate; the omitted terms i = k+1..n are legitimately dropped only
    # because stage.higher_tor_vanishing certified that they are zero, so that
    # certificate is a conjunct here rather than an assumption elsewhere.
    total = sum(tor)
    bound = (2 ** K_LEN) * colen
    ck("consequence.total_length_bound_of_question_5_4_fails",
       total < bound and higher_tor_vanishes is True,
       "sum_{i=0}^{%d} Tor = %d (terms i=%d..%d contribute 0; vanishing "
       "certified: %s) < %d = 2^%d * %d"
       % (N_DIM, total, K_LEN + 1, N_DIM, higher_tor_vanishes, bound,
          K_LEN, colen))


def check_higher_tor_vanishes(DMAX):
    """Tor_i = 0 for i >= 4.

    The Koszul complex on the four generators of J_S resolves S/J_S, so
    Tor_i = 0 for i >= 5 outright, and Tor_4 = (0 :_B J) where B = S/I_S.
    It therefore suffices to exhibit one element of J_S acting injectively
    on B.

    Injectivity is certified two ways.  The complete one is finite: S/I_S is a
    complete intersection, hence Cohen-Macaulay of dimension 1 and unmixed, so
    g is a nonzerodivisor on B exactly when g avoids every minimal prime of
    I_S, i.e. exactly when S/(I_S + (g)) is artinian.  That is decided by a
    Hilbert function reaching zero, in finitely many degrees, with no
    extrapolation.  The graded-injectivity scan is kept as a cross-check, but
    it alone only inspects degrees 0..DMAX-deg(g) and so cannot conclude by
    itself."""
    B = Quotient(GENS_I, DMAX)

    def nonzerodivisor(g):
        """Complete test: S/(I_S+(g)) artinian <=> g is a nzd on S/I_S."""
        hf = hilbert_function(GENS_I + [g], DMAX)
        for d, v in enumerate(hf):
            if v == 0:
                # HF of a graded quotient, once zero, stays zero, since
                # S_1 * S_d spans S_{d+1}.
                return d if all(u == 0 for u in hf[d:]) else None
        return None

    def injective(g):
        degrees = []
        for d in range(DMAX + 1 - pdeg(g)):
            src = B.basis_by_deg[d]
            if not src:
                continue
            rows = [B.class_of(pmul(g, {monomials(d)[c]: Fraction(1)}))
                    for c in src]
            if rank(rows, B.dim) != len(src):
                return None
            degrees.append(d)
        return degrees

    # Each single generator of J_S is a zerodivisor on B (every one of them
    # factors), so search a short deterministic list of elements of J_S.
    candidates = [("g%d" % (i + 1), g) for i, g in enumerate(GENS_J)]
    total = {}
    for g in GENS_J:
        for e, c in g.items():
            total[e] = total.get(e, Fraction(0)) + c
    candidates.append(("g1+g2+g3+g4", {e: c for e, c in total.items() if c}))
    for k in range(len(GENS_J)):
        mix = {}
        for i, g in enumerate(GENS_J):
            w = Fraction(1 + ((i + k) % 3))
            for e, c in g.items():
                mix[e] = mix.get(e, Fraction(0)) + w * c
        candidates.append(("mix%d" % k, {e: c for e, c in mix.items() if c}))

    found = None
    for label, g in candidates:
        nzd = nonzerodivisor(g)
        if nzd is None:
            continue
        degs = injective(g)
        # The two independent certificates must not disagree.  Distinguish the
        # two ways the scan can fail to corroborate: a kernel was found
        # (degs is None) versus no degree was inspected at all (degs == []).
        # Collapsing them would report a kernel that was never seen.
        if degs is None:
            ck("tor.injectivity_certificates_agree", False,
               "%s is a nonzerodivisor by the artinian test but the graded "
               "scan found a kernel" % label)
            return False
        if not degs:
            ck("tor.injectivity_certificates_agree", False,
               "%s passed the artinian test but the graded scan inspected no "
               "degree at all, so it corroborates nothing" % label)
            return False
        found = (label, nzd, degs)
        break
    vanishes = ck("tor.vanishes_in_degrees_above_three", found is not None,
       ("element %s of J_S is a nonzerodivisor on S/I_S: S/(I_S+(%s)) is "
        "artinian from degree %d, and the graded scan is injective in degrees "
        "%s; hence (0 : J) = 0"
        % (found[0], found[0], found[1], found[2])) if found
       else "no candidate element of J_S was a nonzerodivisor on S/I_S")

    # Two observations, printed rather than asserted: neither is falsifiable as
    # a standalone predicate, so making them "checks" would pad the count.
    singles = [i + 1 for i, g in enumerate(GENS_J)
               if nonzerodivisor(g) is not None]
    print("NOTE: generators of J_S that are already nonzerodivisors on S/I_S: "
          "%s -- so searching past single generators is necessary."
          % (singles or "none"))
    print("NOTE: independently, I_S is generated by a regular sequence of "
          "length %d (certified by the Koszul Hilbert function check above), "
          "so pd(S/I_S) = %d and Tor_i(S/I_S, -) vanishes for i >= %d against "
          "any module; that is the paper's own reason for the vanishing."
          % (K_LEN, K_LEN, K_LEN + 1))
    return vanishes


def check_positive_control():
    """The same machinery on monomial complete intersections where the
    conjectured equality does hold, so a systematic undercount would show."""
    one = Fraction(1)
    ctrl_I = [{mono(x=2): one}, {mono(y=2): one}, {mono(z=2): one}]
    ctrl_J = [{mono(x=3): one}, {mono(y=3): one}, {mono(z=3): one},
              {mono(w=1): one}]
    tor, _, _ = tor_lengths(ctrl_I, ctrl_J, 8)
    colen = sum(hilbert_function(ctrl_I + ctrl_J, 8))
    predicted = [binom(K_LEN, i) * colen for i in range(K_LEN + 1)]
    ck("control.machinery_reproduces_the_conjectured_vector_on_a_monomial_case",
       tor == predicted and colen == 8,
       "control colength %d, Tor %s = %s" % (colen, tor, predicted))


def guarded(label, fn, *args):
    """Run a stage; a stage that cannot even complete is reported as a
    failed check rather than as a traceback."""
    try:
        return fn(*args)
    except Exception as exc:
        ck(label, False, "stage aborted: %s" % exc)
        return None


def main():
    guarded("stage.transcription", check_transcription, DMAX)
    guarded("stage.regular_sequences", check_regular_sequences, DMAX)
    colen = guarded("stage.colength", check_colength, DMAX)
    tor = guarded("stage.tor", check_tor, colen)
    if tor is None:
        tor = [None] * (K_LEN + 1)
    guarded("stage.tor1_hilbert_series", check_tor1_hilbert_series, tor, DMAX)
    vanishes = guarded("stage.higher_tor_vanishing",
                       check_higher_tor_vanishes, DMAX)
    guarded("stage.consequences", check_consequences, tor, colen, vanishes)
    guarded("stage.positive_control", check_positive_control)
    print("NOTE: everything is homogeneous, so all lengths are computed as "
          "exact Q-dimensions of graded pieces; the passage to the local ring "
          "at the maximal ideal is the paper's argument, not re-run here.")
    print("NOTE: the graded pieces of Tor_1 are re-run only in degrees 0..%d; "
          "their total already equals the Koszul-homology total, so no higher "
          "degree can contribute." % DMAX)


MIN_CHECKS = 22        # every stage below must actually report

# Honest accounting of the check list.  Each name below is a CONSISTENCY
# RESTATEMENT: it is logically implied by an earlier check, so it cannot fail
# in any run where the earlier one passes.  Such checks are worth keeping --
# they localise a fault and they mirror the paper's own derivation route -- but
# a referee counting the raw total would overestimate how much independent
# evidence the run supplies, so the count is disclosed rather than left
# implicit.
DEPENDENT_CHECKS = (
    # implied by I.hilbert_function_is_that_of_a_complete_intersection, whose
    # Koszul prediction is already constant 2^k in degrees k..DMAX
    "I.has_height_three_so_generators_form_a_regular_sequence",
    # implied by J.hilbert_function_is_that_of_a_complete_intersection, whose
    # prediction already vanishes from degree n+1 on
    "J.is_m_primary_radical_is_the_maximal_ideal",
    # implied by sum.hilbert_function_of_S_mod_I_plus_J, which pins the whole
    # Hilbert function and hence its sum
    "sum.colength_equals_eight",
    # the next three are implied by tor.length_vector_is_8_22_22_8 together
    # with sum.colength_equals_eight and tor1.hilbert_series_is_8t3_plus_14t4
    "tor.degree_zero_term_matches_the_colength",
    "tor.vector_is_symmetric_under_koszul_duality",
    "tor1.two_independent_computations_agree",
)


def finish():
    n = len(CHECKS)
    bad = [c for c, ok in CHECKS if not ok]
    if bad:
        print("VERDICT: %d OF %d CHECKS FAILED" % (len(bad), n))
        for c in bad:
            print("  failed: %s" % c)
        return 1
    # A run that silently asserted nothing must not be reported as a success.
    if n < MIN_CHECKS:
        print("VERDICT: ONLY %d CHECKS RAN, EXPECTED AT LEAST %d -- "
              "treating as failure" % (n, MIN_CHECKS))
        return 1
    # A stale disclosure list would misreport the accounting below, so it is
    # itself a failure condition rather than a comment that can rot.
    ran = set(name for name, _ in CHECKS)
    missing = [c for c in DEPENDENT_CHECKS if c not in ran]
    if missing:
        print("VERDICT: THE DEPENDENT-CHECK DISCLOSURE LIST IS STALE (%s never "
              "ran) -- treating as failure" % ", ".join(missing))
        return 1
    print("NOTE: %d of these %d checks are consistency restatements implied by "
          "an earlier check and so cannot fail alone (%s); the number of "
          "independent derivations is %d."
          % (len(DEPENDENT_CHECKS), n, ", ".join(DEPENDENT_CHECKS),
             n - len(DEPENDENT_CHECKS)))
    print("NOT VERIFIED HERE, and asserted by the paper: (1) the localisation "
          "step S -> S_m -- every length printed above is an exact Q-dimension "
          "over the graded ring S, never an ell_R over R = S_m, and the paper's "
          "argument that finite length makes localisation preserve lengths and "
          "commute with Tor is taken on trust, so the theorem's own statement "
          "(which is written entirely over R) is reached only through that "
          "untested step; (2) the paper's own proofs of the two facts this "
          "program instead re-derives numerically -- the prime-avoidance "
          "argument for sqrt(J_S) = m and the appeal to Koszul duality for the "
          "symmetry of the Tor vector; (3) the second, intersection route to "
          "Tor_1 enumerates graded pieces only in degrees 0..%d, so no degree "
          "above %d is inspected by it (its total does equal the Koszul-homology "
          "total, which is what closes the gap, but that is an argument, not a "
          "computation over the higher degrees); (4) and, the largest gap of "
          "all, the CONTENT and the NUMBERING of the statements being refuted. "
          "The shape of the conjectured equality, the shape of the total bound, "
          "the labels Conjecture 4.2, Question 5.1, Question 5.4 and "
          "Proposition 1.9, and the bibliographic identifiers of the cited "
          "article (its DOI and arXiv number) are all transcribed from the "
          "paper, which transcribes them from a source this program cannot "
          "open: nothing here reads the cited article, and this run has no "
          "network access by policy. Every arithmetic fact above can therefore "
          "be correct while the corollary is attached to the wrong numbered "
          "statement; that attribution needs a human with the cited article in "
          "hand." % (DMAX, DMAX))
    print("VERDICT: ALL %d CHECKS PASS" % n)
    return 0


if __name__ == "__main__":
    import sys
    main()
    sys.exit(finish())
