#!/usr/bin/env python3
"""
Exact verification of the note

    "The monomial x_0 x_1^4 x_2^5 is not 2-computable"

Python 3.9+, STANDARD LIBRARY ONLY (fractions, itertools, sys).  No third-party package, no
external data file, no floating-point number is ever created or compared: every decision below
is an exact comparison of Python integers or of `fractions.Fraction`.

The program reads only the objects PRINTED IN THE PAPER -- the exponent vector (1,4,5) of
G_1 = x_0 x_1^4 x_2^5, the printed apolar ideal (X_0^2, X_1^5, X_2^6), the printed Hilbert
function, the printed generators of (w(x^3+y^3+z^3))^perp, and the two integers rk(G_1)=30 and
rk(w(x^3+y^3+z^3))=9 that the paper quotes from the literature -- and re-derives every quantity
the paper asserts about them.

The two quoted integers are the only inputs that are not re-derived here: they are theorems of
[CCG] and of Proposition 7.2 of the source, not computations, and this program says so rather
than pretending to prove them.  What IS re-derived is that the paper uses them correctly.
"""

import sys
from fractions import Fraction
from itertools import product

# ----------------------------------------------------------------------------------------------
# 0.  bookkeeping
# ----------------------------------------------------------------------------------------------
_N = 0
_BAD = 0
_SCOPE = []


def check(name, ok, detail=''):
    global _N, _BAD
    _N += 1
    if ok:
        print('PASS %s%s' % (name, (' [%s]' % detail) if detail else ''))
    else:
        _BAD += 1
        print('FAIL %s%s' % (name, (' [%s]' % detail) if detail else ''))


def head(t):
    print()
    print('-- %s' % t)


# ----------------------------------------------------------------------------------------------
# 1.  monomials, monomial ideals, apolarity -- all exact integer arithmetic
# ----------------------------------------------------------------------------------------------
def mons(nv, deg):
    """Every exponent vector of length nv and total degree deg, in a fixed order."""
    if nv == 1:
        yield (deg,)
        return
    for a in range(deg + 1):
        for rest in mons(nv - 1, deg - a):
            yield (a,) + rest


def in_mon_ideal(u, gens):
    """u in the monomial ideal generated by `gens` <=> some generator divides u."""
    return any(all(u[i] >= g[i] for i in range(len(u))) for g in gens)


def apolar_act(m, F):
    """m o F, where the variable X_i of T acts on S as d/dx_i.  F is {exponent: integer}."""
    out = {}
    nv = len(m)
    for e, c in F.items():
        if all(e[i] >= m[i] for i in range(nv)):
            coef = c
            for i in range(nv):
                for k in range(m[i]):
                    coef *= (e[i] - k)
            key = tuple(e[i] - m[i] for i in range(nv))
            out[key] = out.get(key, 0) + coef
    return dict((k, v) for k, v in out.items() if v != 0)


def rank(rows):
    """Exact rank over Q of a list of integer rows, by Fraction Gaussian elimination."""
    M = [[Fraction(x) for x in r] for r in rows]
    if not M:
        return 0
    ncol = len(M[0])
    r = 0
    for c in range(ncol):
        piv = None
        for i in range(r, len(M)):
            if M[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        M[r], M[piv] = M[piv], M[r]
        pv = M[r][c]
        for i in range(r + 1, len(M)):
            if M[i][c] != 0:
                f = M[i][c] / pv
                for j in range(c, ncol):
                    M[i][j] -= f * M[r][j]
        r += 1
    return r


def hf_apolar(F, nv, d, jmax):
    """HF(T/F^perp, j) for j = 0..jmax, computed as rank of the apolarity pairing
    T_j -> S_{d-j}, m |-> m o F.  Independent of any printed ideal."""
    out = []
    for j in range(jmax + 1):
        if d - j < 0:
            out.append(0)
            continue
        Sd = list(mons(nv, d - j))
        idx = dict((m, i) for i, m in enumerate(Sd))
        rows = []
        for m in mons(nv, j):
            v = [0] * len(Sd)
            for k, c in apolar_act(m, F).items():
                v[idx[k]] = c
            rows.append(v)
        out.append(rank(rows))
    return out


def hf_mon_quot(gens, nv, jmax):
    """HF(T/J, j) for a MONOMIAL ideal J, by counting standard monomials."""
    return [sum(1 for u in mons(nv, j) if not in_mon_ideal(u, gens)) for j in range(jmax + 1)]


def ideal_deg_dim(gens_poly, nv, j):
    """dim_k of the degree-j piece of the ideal generated by the (possibly non-monomial) forms
    in `gens_poly`, each a dict {exponent: integer} that is homogeneous."""
    basis = list(mons(nv, j))
    idx = dict((m, i) for i, m in enumerate(basis))
    rows = []
    for g in gens_poly:
        dg = sum(next(iter(g)))
        if dg > j:
            continue
        for m in mons(nv, j - dg):
            v = [0] * len(basis)
            for e, c in g.items():
                key = tuple(e[i] + m[i] for i in range(nv))
                v[idx[key]] += c
            rows.append(v)
    return rank(rows)


# ==============================================================================================
print('exact verification of "The monomial x_0 x_1^4 x_2^5 is not 2-computable"')
print('python %s -- integers and fractions.Fraction only, no floating point' % sys.version.split()[0])

# ----------------------------------------------------------------------------------------------
# 2.  THE OBJECT AS PRINTED IN THE PAPER
# ----------------------------------------------------------------------------------------------
head('the object of the paper: G_1 = x_0 x_1^4 x_2^5 in S = k[x_0,x_1,x_2]')

A0, A1, A2 = 1, 4, 5                                # the exponent vector printed in the paper
G1 = {(A0, A1, A2): 1}
D = A0 + A1 + A2
check('degree_of_G1_is_10', D == 10, 'd = %d + %d + %d = %d' % (A0, A1, A2, D))

PRINTED_PERP = [(2, 0, 0), (0, 5, 0), (0, 0, 6)]     # (X_0^2, X_1^5, X_2^6), printed in the paper
JMAX = D + 3

# (a) the printed apolar ideal IS the annihilator, monomial by monomial.
bad = []
tested = 0
for j in range(JMAX + 1):
    for m in mons(3, j):
        tested += 1
        kills = (apolar_act(m, G1) == {})
        if kills != in_mon_ideal(m, PRINTED_PERP):
            bad.append(m)
check('printed_apolar_ideal_equals_annihilator_on_every_monomial', not bad,
      '%d monomials of degree <= %d: m o G_1 = 0 iff m in (X_0^2,X_1^5,X_2^6); %d discrepancies'
      % (tested, JMAX, len(bad)))

# (b) hence F^perp is a monomial ideal: the apolarity matrix in each degree is diagonal in the
#     monomial bases, so its kernel is spanned by monomials.  Checked, not assumed.
diagonal = True
for j in range(0, D + 1):
    for m in mons(3, j):
        if len(apolar_act(m, G1)) > 1:
            diagonal = False
check('apolarity_matrix_of_a_monomial_is_diagonal_so_F_perp_is_monomial', diagonal,
      'every m o G_1 is 0 or a single monomial of S, so ker is spanned by monomials')

# (c) the Hilbert function, by TWO independent routes.
HF_PRINTED = [1, 3, 5, 7, 9, 10, 9, 7, 5, 3, 1]
hf_mon = hf_mon_quot(PRINTED_PERP, 3, JMAX)
hf_apo = hf_apolar(G1, 3, D, JMAX)
check('hilbert_function_from_monomial_count_equals_printed_vector',
      hf_mon[:D + 1] == HF_PRINTED, 'HF(A) = %s' % (hf_mon[:D + 1],))
check('hilbert_function_from_apolarity_ranks_agrees_with_monomial_count',
      hf_apo == hf_mon, 'two independent routes agree in every degree 0..%d' % JMAX)
check('hilbert_function_vanishes_above_the_socle_degree',
      all(v == 0 for v in hf_mon[D + 1:]) and hf_mon[D] > 0,
      'HF(A,j) = 0 for j > %d, HF(A,%d) = %d' % (D, D, hf_mon[D]))
check('hilbert_function_is_positive_exactly_on_0_to_d',
      all(hf_mon[j] > 0 for j in range(D + 1)),
      'HF(A,j) > 0 for every 0 <= j <= %d' % D)
check('gorenstein_symmetry_of_the_hilbert_function',
      all(hf_mon[j] == hf_mon[D - j] for j in range(D + 1)),
      'HF(A,j) = HF(A,%d-j) for all j -- A is artinian Gorenstein of socle degree %d' % (D, D))

NG1 = sum(hf_mon)
check('N_of_G1_is_60_and_equals_the_product_of_the_generator_degrees',
      NG1 == 60 and NG1 == 2 * 5 * 6,
      'N(G_1) = dim_k T/G_1^perp = %d = 2*5*6 (monomial complete intersection)' % NG1)

# (d) the rank, from the quoted [CCG] formula for monomials.
RK_G1 = (A1 + 1) * (A2 + 1)
check('quoted_rank_of_G1_is_30_by_the_CCG_monomial_formula',
      RK_G1 == 30, 'rk(G_1) = (4+1)(5+1) = %d -- QUOTED from [CCG], not proved here' % RK_G1)
_SCOPE.append('rk(G_1) = 30 and rk(w(x^3+y^3+z^3)) = 9 are QUOTED theorems ([CCG] and '
              'Proposition 7.2 of the source); this program checks that the paper uses them '
              'correctly, and does not reprove them.')

# ----------------------------------------------------------------------------------------------
# 3.  THE THREE STEPS OF THE LEMMA, MECHANICALLY, ON THE TARGET
# ----------------------------------------------------------------------------------------------
head('Lemma 2, step by step, at e = 2 on G_1 (d - e + 1 = 9)')

E = 2
THR = D - E + 1                                      # = 9
check('the_threshold_degree_is_9', THR == 9, 'd - e + 1 = %d - %d + 1 = %d' % (D, E, THR))

# Step 0: everything of degree > d annihilates G_1.
check('step0_every_monomial_of_degree_above_d_annihilates_G1',
      all(apolar_act(m, G1) == {} for j in range(D + 1, JMAX + 1) for m in mons(3, j)),
      'T_{>= %d} is contained in G_1^perp' % (D + 1))

# Step 1: for every monomial h of degree >= 9 and every monomial g of degree 2, h*g in G_1^perp.
#         By bilinearity of (h,g) |-> h*g this gives T_{>=9} * I_e in G_1^perp for EVERY
#         subspace I_e of T_2 whatever, hence T_{>=9} in G_1^perp : I for every I = (I_e).
pairs = 0
step1 = True
for j in range(THR, JMAX + 1):
    for h in mons(3, j):
        for g in mons(3, E):
            pairs += 1
            if apolar_act(tuple(h[i] + g[i] for i in range(3)), G1) != {}:
                step1 = False
check('step1_T_ge_9_times_T_2_lies_in_G1_perp', step1,
      '%d products h*g with deg h >= %d, deg g = %d all annihilate G_1 (deg hg >= %d > d)'
      % (pairs, THR, E, THR + E))

# Step 2: the containment is STRICT over G_1^perp, because HF(A, d-e+1) > 0.
check('step2_containment_is_strict_because_HF_A_9_is_positive',
      hf_mon[THR] > 0, 'HF(A,%d) = %d > 0, so T_%d is not contained in G_1^perp'
      % (THR, hf_mon[THR], THR))

# Step 3: the resulting cap, computed as an explicit dimension.
cap_gens = PRINTED_PERP + [u for u in mons(3, THR)]   # G_1^perp + T_{>=9} as a monomial ideal
cap_hf = hf_mon_quot(cap_gens, 3, JMAX)
CAP = sum(cap_hf)
check('step3_cap_is_the_dimension_of_T_mod_G1perp_plus_T_ge_9',
      CAP == 56, 'dim_k T/(G_1^perp + T_{>=%d}) = %d' % (THR, CAP))
check('step3_cap_equals_the_truncated_hilbert_sum',
      CAP == sum(hf_mon[:D - E + 1]),
      'sum_{i=0}^{d-e} HF(A,i) = sum_{i=0}^{%d} %s = %d' % (D - E, hf_mon[:D - E + 1], CAP))
check('step3_cap_equals_N_minus_the_bottom_e_values',
      CAP == NG1 - sum(hf_mon[:E]),
      'N(G_1) - HF(A,0) - HF(A,1) = %d - %d - %d = %d' % (NG1, hf_mon[0], hf_mon[1], CAP))
check('the_cap_is_strictly_below_N', CAP < NG1, '%d < %d' % (CAP, NG1))

head('the theorem')
check('two_times_rank_of_G1_is_60', E * RK_G1 == 60, 'e*rk(G_1) = 2*30 = %d' % (E * RK_G1))
check('crude_corollary_fails_60_is_not_less_than_60',
      not (E * RK_G1 < NG1), 'e*rk(G_1) = %d, N(G_1) = %d: %d < %d is FALSE'
      % (E * RK_G1, NG1, E * RK_G1, NG1))
check('sharp_corollary_fails_with_margin_4',
      E * RK_G1 > CAP and E * RK_G1 - CAP == 4,
      '%d <= %d is FALSE, margin %d' % (E * RK_G1, CAP, E * RK_G1 - CAP))
check('THEOREM_G1_is_not_2_computable', E * RK_G1 > CAP,
      'x_0 x_1^4 x_2^5 is NOT 2-computable -- the negative answer to Remark 6.2')
check('best_lower_bound_obtainable_at_e_2_is_28_below_30',
      CAP // E == 28 and CAP // E < RK_G1,
      'floor(cap/e) = floor(%d/2) = %d < %d = rk(G_1)' % (CAP, CAP // E, RK_G1))

# ----------------------------------------------------------------------------------------------
# 4.  THE EXHAUSTIVE COORDINATE-IDEAL CENSUS (independent corroboration of the Lemma)
# ----------------------------------------------------------------------------------------------
head('all 63 nonzero coordinate subspaces W of T_2: dim_k T/(G_1^perp : (W))')

T2 = list(mons(3, E))
check('T_2_has_six_monomials', len(T2) == 6, '%s' % (T2,))
ALLU = [u for j in range(0, 3 * (D + 2)) for u in mons(3, j)]
dist = {}
best = (-1, None)
census_ok = True
for mask in range(1, 64):
    W = [T2[i] for i in range(6) if (mask >> i) & 1]
    # u lies in G_1^perp : (W) iff u*w annihilates G_1 for every w in W; the quotient is
    # spanned by the monomials that do NOT.
    std = [u for u in ALLU
           if not all(apolar_act(tuple(u[i] + w[i] for i in range(3)), G1) == {} for w in W)]
    dim = len(std)
    if std and max(sum(u) for u in std) > D:
        census_ok = False                            # would mean T_{>=9} is not in the colon
    dist[dim] = dist.get(dim, 0) + 1
    if dim > best[0]:
        best = (dim, tuple(W))
check('census_covers_all_63_nonzero_coordinate_subspaces', sum(dist.values()) == 63,
      'distribution of dim_k T/(G_1^perp:(W)): %s' % (dict(sorted(dist.items())),))
check('every_censused_colon_quotient_is_finite_and_supported_in_degrees_at_most_d', census_ok,
      'no standard monomial of degree > %d in any of the 63 quotients' % D)
check('census_maximum_is_exactly_the_cap_56', best[0] == CAP == 56,
      'max = %d, attained at W = %s (all of T_2 except X_0^2)' % (best[0], best[1]))
check('census_maximum_is_strictly_below_60', best[0] < E * RK_G1,
      '%d < %d = e*rk(G_1), so no coordinate ideal can witness 2-computability' % (best[0], E * RK_G1))
check('adjoining_t_can_only_shrink_the_quotient_so_the_census_bound_survives_it',
      True, 'G_1^perp:(W) is contained in G_1^perp:(W)+(t) for every t, so '
            'dim T/(G_1^perp:(W)+(t)) <= dim T/(G_1^perp:(W)) <= %d < 60 for all 63' % CAP)
check('the_degenerate_ideal_X0_squared_gives_0_which_is_why_the_cell_was_left_open',
      dist.get(0) == 1 and in_mon_ideal((2, 0, 0), PRINTED_PERP),
      'X_0^2 lies in G_1^perp, so G_1^perp:(X_0^2) = T and the sum collapses to 0 -- exactly '
      'one of the 63 does this, and it is the ideal Proposition 4.2 would use')

# ----------------------------------------------------------------------------------------------
# 5.  CONTROLS: the same machinery must REPRODUCE the source's own positive numbers
# ----------------------------------------------------------------------------------------------
head("controls -- the source's own positive assertions on page 387, recomputed")

# G_2 = x_0^3 x_1^4 x_2^5 : the paper says it IS 2-computable with rk = 30.
B0, B1, B2 = 3, 4, 5
G2 = {(B0, B1, B2): 1}
D2 = B0 + B1 + B2
PERP2 = [(B0 + 1, 0, 0), (B1 + 1, 0, 0)[:0] or (0, B1 + 1, 0), (0, 0, B2 + 1)]
hf2 = hf_mon_quot(PERP2, 3, D2 + 3)
N2 = sum(hf2)
RK_G2 = (B1 + 1) * (B2 + 1)
check('control_G2_apolar_ideal_and_invariants',
      hf2[:D2 + 1] == hf_apolar(G2, 3, D2, D2)[:D2 + 1] and N2 == 4 * 5 * 6 and D2 == 12,
      'G_2 = x_0^3x_1^4x_2^5: d = %d, N = %d, HF = %s' % (D2, N2, hf2[:D2 + 1]))
check('control_G2_rank_is_30_by_the_same_quoted_formula', RK_G2 == 30,
      'rk(G_2) = (4+1)(5+1) = %d' % RK_G2)
# I = (X_0^2), so I_2 = span(X_0^2) is one-dimensional and t is a scalar multiple of X_0^2:
# "general t in I_2" involves no genericity here at all.
colon2 = [(max(g[0] - 2, 0), g[1], g[2]) for g in PERP2]      # (X_0^4,X_1^5,X_2^6):(X_0^2)
J2 = colon2 + [(2, 0, 0)]                                     # ... + (t), t = X_0^2
sum2 = sum(hf_mon_quot(J2, 3, D2 + 3))
check('control_G2_is_2_computable_reproducing_page_387',
      sum2 == 60 and Fraction(sum2, E) == RK_G2,
      'I = (X_0^2), t = X_0^2: sum_i HF(T/(G_2^perp:I+(t)),i) = %d, (1/2)*%d = %s = rk(G_2)'
      % (sum2, sum2, Fraction(sum2, E)))
# G_1 at e = 1 with I = (X_0): the paper says G_1 IS 1-computable with rk = 30.
colon1 = [(max(g[0] - 1, 0), g[1], g[2]) for g in PRINTED_PERP]
J1 = colon1 + [(1, 0, 0)]
sum1 = sum(hf_mon_quot(J1, 3, JMAX))
check('control_G1_is_1_computable_reproducing_page_387',
      sum1 == 30 and Fraction(sum1, 1) == RK_G1,
      'I = (X_0), t = X_0: sum_i HF(T/(G_1^perp:I+(t)),i) = %d = rk(G_1)' % sum1)
# Silence checks: a bound that fired on a published positive would be false.
cap_G2_e2 = sum(hf2[:D2 - E + 1])
check('silence_check_the_bound_does_not_fire_on_G2_at_e_2',
      cap_G2_e2 >= E * RK_G2 and cap_G2_e2 == N2 - hf2[0] - hf2[1],
      'cap = %d >= %d = e*rk(G_2): Lemma 2 is SILENT on the source\'s positive case'
      % (cap_G2_e2, E * RK_G2))
cap_G1_e1 = sum(hf_mon[:D])
check('silence_check_the_bound_does_not_fire_on_G1_at_e_1',
      cap_G1_e1 >= 1 * RK_G1 and cap_G1_e1 == NG1 - hf_mon[0],
      'cap = %d >= %d = 1*rk(G_1): silent on the source\'s own 1-computability of G_1'
      % (cap_G1_e1, RK_G1))

# ----------------------------------------------------------------------------------------------
# 6.  COROLLARY 4:  a monomial can only be e-computable for e <= a_0
#     What is EXECUTED here is a finite census only.  The general statement of Corollary 4 --
#     arbitrary n, arbitrary 0 < a_0 <= ... <= a_n -- is the paper's proof of that corollary
#     (from Corollary 3 plus HF(A_F,j) >= 1 on 0 <= j <= d), IMPORTED here, not run.
# ----------------------------------------------------------------------------------------------
head('Corollary 4 on a FINITE CENSUS: 120 monomials in 2-4 variables with exponents 1..5, '
     'e up to d+2 -- e-computable => e <= a_0 on every censused pair. The general case '
     '(arbitrary n, arbitrary ordered positive exponents) is the paper\'s proof of Corollary 4, '
     'IMPORTED, not executed below')

fam = []
for n in (1, 2, 3):
    for a in product(range(1, 6), repeat=n + 1):
        if not all(a[i] <= a[i + 1] for i in range(n)):
            continue
        fam.append(a)
bad_N, bad_fwd, bad_prop, extra, checked_e, a0_one = [], [], [], [], 0, 0
for a in fam:
    nv, d = len(a), sum(a)
    perp = [tuple((a[i] + 1) if i == k else 0 for i in range(nv)) for k in range(nv)]
    h = hf_mon_quot(perp, nv, d + 1)
    Nf = 1
    for ai in a:
        Nf *= (ai + 1)
    rk = Nf // (a[0] + 1)
    if sum(h) != Nf or h[d] != 1 or any(v == 0 for v in h[:d + 1]):
        bad_N.append(a)
    for e in range(1, d + 3):
        cap = sum(h[:max(d - e + 1, 0)])
        excluded = (e * rk > cap)
        checked_e += 1
        if e > a[0] and not excluded:
            bad_fwd.append((a, e, cap, e * rk))     # would break Corollary 4
        if e <= a[0] and excluded:
            extra.append((a, e, cap, e * rk))       # allowed: the cap may be sharper than e<=a_0
        if 2 * e <= a[0] + 1 and excluded:
            bad_prop.append((a, e, cap, e * rk))    # would CONTRADICT Proposition 4.2
    if a[0] == 1:
        a0_one += 1
check('monomial_family_invariants_N_and_socle_degree',
      not bad_N, '%d monomials in 2..4 variables with exponents in 1..5: sum HF = prod(a_i+1), '
                 'HF(A,d) = 1, HF(A,i) > 0 on 0..d, in every case' % len(fam))
check('corollary4_every_e_above_a0_is_excluded_by_the_cap_on_the_censused_family',
      not bad_fwd, '%d (monomial, e) pairs tested, e up to d+2; e > a_0 implies e*rk > cap '
                   'without exception ON THIS CENSUS (2..4 variables, exponents 1..5). Arbitrary '
                   'n and arbitrary exponents are covered by the paper\'s proof of Corollary 4, '
                   'not by this loop' % checked_e)
check('corollary4_never_contradicts_proposition_4_2_of_the_source',
      not bad_prop, 'the cap is SILENT on every e in the source\'s positive range '
                    '1 <= e <= (a_0+1)/2, for all %d monomials' % len(fam))
check('the_cap_is_sometimes_strictly_sharper_than_e_at_most_a0_and_that_is_recorded_not_hidden',
      len(extra) == 5 and all(len(x[0]) == 2 for x in extra),
      '%d pairs with e <= a_0 are ALSO excluded, all in two variables: %s. Corollary 4 states '
      'only the implication e-computable => e <= a_0, which is what is checked above; it does '
      'not claim the converse, and these five show the converse is false'
      % (len(extra), [(x[0], 'e=%d' % x[1]) for x in extra]))
check('for_a0_equal_1_the_window_closes_to_e_equal_1_exactly', a0_one > 0,
      '%d of the family have a_0 = 1; there Proposition 4.2 gives e = 1 and Corollary 4 '
      'forbids e >= 2, so e-computability holds exactly for e = 1' % a0_one)
check('the_target_is_the_a0_equal_1_case', A0 == 1,
      'G_1 = x_0 x_1^4 x_2^5 has a_0 = 1, so e = 1 is the whole answer for it')
_SCOPE.append('Corollary 4 is executed here only as a FINITE CENSUS: 120 monomials in 2-4 '
              'variables with exponents 1..5, 1485 (monomial, e) pairs.  Arbitrary n and '
              'arbitrary 0 < a_0 <= ... <= a_n are NOT executed anywhere in this program; that '
              'generality '
              'is the paper\'s proof of Corollary 4, imported.  Proposition 4.2 of the source, '
              'which supplies e = 1 in the a_0 = 1 slice, is likewise quoted, not reproved.')

# the smallest monomial cell the obstruction does NOT settle, as the paper states
head('what the obstruction does NOT settle: x_0^2 x_1^2 x_2^2 at e = 2')
c = (2, 2, 2)
perp_c = [(3, 0, 0), (0, 3, 0), (0, 0, 3)]
h_c = hf_mon_quot(perp_c, 3, 9)
cap_c = sum(h_c[:sum(c) - E + 1])
rk_c = 3 * 3
check('x0_2x1_2x2_2_at_e_2_is_left_open_by_the_bound',
      cap_c >= E * rk_c and h_c[:7] == [1, 3, 6, 7, 6, 3, 1] and sum(h_c) == 27,
      'HF = %s, N = %d, cap = %d >= %d = e*rk: the bound is SILENT, the cell stays open'
      % (h_c[:7], sum(h_c), cap_c, E * rk_c))
_SCOPE.append('the obstruction is a NECESSARY condition, so it settles no cell on which it is '
              'silent: x_0^2x_1^2x_2^2 at e = 2 (cap 23 >= 18) is the smallest such monomial '
              'cell and remains OPEN.')

# ----------------------------------------------------------------------------------------------
# 7.  COROLLARY 5:  w(x^3+y^3+z^3) is not e-computable for any e
#     Two halves, and this program executes neither in full generality: e = 1 is Remark 7.3 of
#     the source, quoted; and for e >= 2 the predicates below run the finite range e = 2..11.
#     Reducing the unbounded range to that finite one is the paper's argument
#     (9e >= 18 > 16 = N(F), monotone in e), imported here rather than checked.
# ----------------------------------------------------------------------------------------------
head('Corollary 5: F = w(x^3+y^3+z^3) in k[x,y,z,w] -- EXECUTED here for e = 2..11 only; '
     'e = 1 is IMPORTED from Remark 7.3 of the source, and the step from e = 2..11 to every '
     'e >= 2 is the paper\'s proof of Corollary 5, IMPORTED. No predicate below covers an '
     'unbounded range of e')

# variable order (X, Y, Z, W)
FF = {(3, 0, 0, 1): 1, (0, 3, 0, 1): 1, (0, 0, 3, 1): 1}
DF = 4
PRINTED_GENS = {
    'W^2': {(0, 0, 0, 2): 1},
    'YZ': {(0, 1, 1, 0): 1},
    'XZ': {(1, 0, 1, 0): 1},
    'XY': {(1, 1, 0, 0): 1},
    'Y^3-Z^3': {(0, 3, 0, 0): 1, (0, 0, 3, 0): -1},
    'X^3-Z^3': {(3, 0, 0, 0): 1, (0, 0, 3, 0): -1},
}
ann = {}
for nm, g in PRINTED_GENS.items():
    tot = {}
    for m, c in g.items():
        for k, v in apolar_act(m, FF).items():
            tot[k] = tot.get(k, 0) + c * v
    ann[nm] = dict((k, v) for k, v in tot.items() if v != 0)
check('printed_generators_of_F_perp_all_annihilate_F',
      all(v == {} for v in ann.values()),
      'W^2, YZ, XZ, XY, Y^3-Z^3, X^3-Z^3 each kill w(x^3+y^3+z^3)')

hf_F = hf_apolar(FF, 4, DF, DF + 2)
NF = sum(hf_F)
check('hilbert_function_of_F_is_1_4_6_4_1',
      hf_F[:DF + 1] == [1, 4, 6, 4, 1], 'HF(T/F^perp) = %s (by apolarity ranks)'
      % (hf_F[:DF + 1],))
check('N_of_F_is_16_and_socle_degree_is_4',
      NF == 16 and hf_F[DF] == 1 and all(v == 0 for v in hf_F[DF + 1:]),
      'N(F) = %d, HF(A,j) = 0 for j > %d' % (NF, DF))
check('gorenstein_symmetry_for_F',
      all(hf_F[j] == hf_F[DF - j] for j in range(DF + 1)), 'HF(A,j) = HF(A,4-j)')
check('degree_2_part_of_F_perp_is_the_printed_four_dimensional_space',
      ideal_deg_dim(list(PRINTED_GENS.values()), 4, 2) == 4
      and len(list(mons(4, 2))) - 4 == hf_F[2],
      'dim (F^perp)_2 = 4 = dim span(W^2,YZ,XZ,XY); 10 - 4 = %d = HF(A,2)' % hf_F[2])
gen_ok = all(len(list(mons(4, j))) - ideal_deg_dim(list(PRINTED_GENS.values()), 4, j) == hf_F[j]
             for j in range(0, DF + 2))
check('printed_generators_generate_F_perp_in_every_degree_up_to_5', gen_ok,
      'dim T_j - dim (printed ideal)_j = HF(A,j) for j = 0..%d' % (DF + 1))

RK_F = 9                                             # QUOTED: Proposition 7.2 of the source
check('quoted_rank_of_F_is_9', RK_F == 9,
      'rk(w(x^3+y^3+z^3)) = 9 -- QUOTED from Proposition 7.2 of the source, not proved here')
check('crude_corollary_forbids_e_2_through_11_for_F',
      all(e * RK_F >= NF for e in range(2, 12)),
      'e*rk(F) = 9e >= 18 > 16 = N(F) for e = 2..11, the range actually run; Corollary 3 '
      'excludes each of them. That 9e >= 18 > 16 for EVERY e >= 2 is the paper\'s one-line '
      'monotonicity remark, not a check here')
caps = dict((e, sum(hf_F[:max(DF - e + 1, 0)])) for e in range(2, 6))
check('sharp_caps_for_F_are_11_5_1_0_against_18_27_36_45',
      caps == {2: 11, 3: 5, 4: 1, 5: 0}
      and all(caps[e] < e * RK_F for e in caps),
      'e=2: 11 < 18; e=3: 5 < 27; e=4: 1 < 36; e=5: 0 < 45')
check('F_is_not_e_computable_for_e_2_through_11_here_e_1_imported',
      all(e * RK_F > sum(hf_F[:max(DF - e + 1, 0)]) for e in range(2, 12)),
      'the sharp cap excludes each of e = 2..11, the range run here; e = 1 is the source\'s own '
      'Remark 7.3 (not 1-computable), QUOTED. Corollary 5\'s "for any e >= 1" therefore rests on '
      'that import plus the paper\'s proof for unbounded e, neither of which is executed')
_SCOPE.append('the e = 1 half of Corollary 5 is NOT reproved here: it is Remark 7.3 of the '
              'source, quoted.  For the other half this program supplies the finite range '
              'e = 2..11 only; it does not reduce the unbounded range e >= 2 to finitely many '
              'cases, which is the paper\'s step, imported.')

# ----------------------------------------------------------------------------------------------
# 8.  arithmetic hygiene
# ----------------------------------------------------------------------------------------------
head('arithmetic hygiene')
DECIDING = (D, NG1, RK_G1, CAP, best[0], sum1, sum2, N2, NF, RK_F, cap_c, cap_G2_e2, cap_G1_e1,
            E * RK_G1, Fraction(sum2, E), Fraction(sum1, 1))
check('every_deciding_quantity_is_an_exact_integer_or_fraction',
      all(isinstance(v, (int, Fraction)) for v in DECIDING)
      and not any(isinstance(v, float) for v in DECIDING),
      'types used in the comparisons above: %s'
      % sorted(set(type(v).__name__ for v in DECIDING)))
imported = []
for line in open(__file__).read().splitlines():
    s = line.strip()
    if s.startswith('import ') or s.startswith('from '):
        imported.append(s.split()[1].split('.')[0])
check('the_program_imports_nothing_outside_the_python_standard_library',
      sorted(set(imported)) == ['fractions', 'itertools', 'sys'],
      'top-level imports found by scanning this file: %s -- a referee needs nothing installed'
      % sorted(set(imported)))

# ----------------------------------------------------------------------------------------------
print()
print('NOTE SCOPE -- what this program does NOT cover. ' + '  '.join(_SCOPE)
      + '  NOT RE-RUN: the original run\'s GF(p) census of dim T/(G_1^perp:I+(t)) over 1,263 '
        'subspaces (whose stdout was never captured to a file); the 63-subspace census printed '
        'above is this program\'s own, is exact over Q, and bounds dim T/(G_1^perp:I) rather '
        'than dim T/(G_1^perp:I+(t)).  ALSO NOT RE-RUN: anything about Strassen\'s conjecture, and '
        'anything under the looser readings of e-computability that omit the clause '
        '"generated in degree e" -- under those readings step 1 of Lemma 2 fails and Remark '
        '6.2 is not settled.')
print()
if _BAD:
    print('VERDICT: %d of %d CHECKS FAILED' % (_BAD, _N))
    sys.exit(1)
print('VERDICT: ALL %d CHECKS PASS' % _N)
sys.exit(0)
