#!/usr/bin/env python3
"""Verification of a counterexample to a conjectured Tor-length identity.

The conjecture under test: for a regular local ring (R,m) of dimension n, an
ideal I generated by an R-regular sequence of length k, and an ideal J
generated by an R-regular sequence of length n, with the restriction
k <= n-1,
        length(Tor_i^R(R/I, R/J)) = binom(k,i) * length(R/(I+J)),  0<=i<=k.

VALUES TAKEN FROM THE PAPER (inputs; this program does not re-derive them)
  * the ring R = Q[x,y,z,t] localized at (x,y,z,t), so n = 4;
  * I = (x^2, y^2, z^2)  and  J = (x^2+xy, xz+z^2, y^2+yz, t), so k = 3;
  * the statement of the identity displayed above, including its hypotheses;
  * the asserted Groebner basis of J_0 = (x^2+xy, xz+z^2, y^2+yz) for graded
    reverse lexicographic order with x > y > z, and the asserted monomial
    basis 1; x,y,z; xy,yz,z^2; z^3 of A = Q[x,y,z]/J_0;
  * the asserted pairing matrix T with rows (1,-1,1),(1,1,-1),(-1,1,1) and
    det T = 4;
  * the asserted chain dimensions 8,24,24,8, differential ranks 4,6,4 and
    their graded pieces (3,1),(3,3),(1,3);
  * the asserted Tor-length vector (4,14,14,4), colength 4 and conjectured
    vector (4,12,12,4);
  * the two cited results making the identity true for k <= 2, used only to
    phrase the minimality of the pair (n,k) = (4,3).

DERIVED HERE (computed from the generators by exact rational arithmetic)
  * normal forms in A by row reducing every graded piece of J_0; the Hilbert
    function (1,3,3,1,0), hence colength 8 and (x,y,z)^4 in J_0.  Three forms
    in three variables with finite colength have codimension 3, so both
    triples of generators are regular sequences;
  * that the five asserted Groebner basis elements lie in J_0 and that their
    leading terms generate the initial ideal of J_0 in every degree through 6,
    which certifies the asserted basis and its 8 standard monomials;
  * the multiplication matrix of A_2 (x) A_1 -> A_3 and its determinant;
  * the three differentials of the Koszul complex K(x^2,y^2,z^2; A) as
    explicit rational matrices, that consecutive ones compose to zero, their
    exact ranks, their graded ranks, and the homology dimensions;
  * length(R/(I+J)) as dim A - rank d_1, and the ideal of A that it kills;
  * the conjectured vector binom(3,i)*colength and the exact set of indices
    where the computed vector differs from it: this is the refutation;
  * the same Tor vector recomputed from scratch in Q[x,y,z,t] and in
    Q[x,y,z,t1,t2], i.e. for gaps n-k = 1 and n-k = 2, which exercises the
    stabilization statement in the cases the argument uses;
  * a census over four graded complete intersections in three variables and
    five regular sequences: 20 instances each for k = 1, 2, 3, together with
    a control off the hypotheses.  The census is in three variables, so
    n = 3 in all of it: the k = 1 and k = 2 instances are in the range
    k <= n-1 of the conjecture under test, while the k = 3 instances have
    k = n and belong to the unrestricted assertion already disproved in the
    cited literature.  The k = 3 failures the census reports are therefore
    not additional counterexamples to the k <= n-1 conjecture; they reach
    its range only through stabilization.  The control matters: for k = 1 the
    identity is rank-nullity and holds for every element of every finite
    dimensional algebra, so no k = 1 instance can ever fail and that half of
    the census carries no information.  For k = 2 the identity is equivalent
    to rank d_1 = rank d_2; dropping only the complete intersection
    hypothesis on R/J breaks it, which is what the control exhibits, so the
    k = 2 half is discriminating.  The minimality check is conditioned on
    both, and fails rather than restating the claim if either collapses.

Because R/J is isomorphic to A, which is a graded Artinian local Q-algebra
with residue field Q, Tor_i^R(R/I,R/J) is the i-th homology of the Koszul
complex of x^2,y^2,z^2 over A, localization is inert, and lengths over R are
Q-vector space dimensions.

Standard library only; every decision is made with integers or fractions.
"""

import sys
from fractions import Fraction
from itertools import combinations

CHECKS = []
CENSUS = {}
Q0 = Fraction(0)
Q1 = Fraction(1)


# ---------------------------------------------------------------- polynomials
# A polynomial in nv variables is a dict {exponent tuple: Fraction}, 0 omitted.

def p_clean(p):
    return dict((m, c) for m, c in p.items() if c != 0)


def p_mul(p, q):
    r = {}
    for m1, c1 in p.items():
        for m2, c2 in q.items():
            m = tuple(a + b for a, b in zip(m1, m2))
            r[m] = r.get(m, Q0) + c1 * c2
    return p_clean(r)


def p_degree(p):
    return max(sum(m) for m in p) if p else -1


def p_homogeneous(p):
    return len(set(sum(m) for m in p)) <= 1


def mons(nv, d):
    """All exponent tuples in nv variables of total degree exactly d."""
    if nv == 1:
        return [(d,)]
    out = []
    for e in range(d, -1, -1):
        for rest in mons(nv - 1, d - e):
            out.append((e,) + rest)
    # descending graded reverse lexicographic order
    out.sort(key=lambda m: tuple(reversed(m)))
    return out


def grevlex_gt(a, b):
    """Graded reverse lexicographic order, first variable largest."""
    if sum(a) != sum(b):
        return sum(a) > sum(b)
    for i in range(len(a) - 1, -1, -1):
        if a[i] != b[i]:
            return a[i] < b[i]
    return False


def p_str(p, names):
    if not p:
        return "0"
    order = sorted(p.keys(), key=lambda m: (-sum(m), tuple(reversed(m))))
    out = ""
    for m in order:
        c = p[m]
        piece = "*".join(names[i] + ("^%d" % e if e > 1 else "")
                         for i, e in enumerate(m) if e)
        if not piece:
            piece = "1"
        if abs(c) != 1 or piece == "1":
            piece = ("%s*" % abs(c)) + piece if piece != "1" else str(abs(c))
        out += (" - " if c < 0 else (" + " if out else "")) + piece
    return out.strip()


def det(mat):
    n = len(mat)
    m = [list(r) for r in mat]
    d = Q1
    for c in range(n):
        pr = None
        for i in range(c, n):
            if m[i][c] != 0:
                pr = i
                break
        if pr is None:
            return Q0
        if pr != c:
            m[c], m[pr] = m[pr], m[c]
            d = -d
        d *= m[c][c]
        inv = Q1 / m[c][c]
        for i in range(c + 1, n):
            if m[i][c] != 0:
                f = m[i][c] * inv
                m[i] = [a - f * b for a, b in zip(m[i], m[c])]
    return d


def binom(n, i):
    r = 1
    for j in range(i):
        r = r * (n - j) // (j + 1)
    return r


def leading_monomial(p):
    lm = None
    for m in p:
        if lm is None or grevlex_gt(m, lm):
            lm = m
    return lm


def ck(name, ok, detail=""):
    CHECKS.append((name, bool(ok)))
    tag = "PASS" if ok else "FAIL"
    if detail:
        print("%s %s [%s]" % (tag, name, detail))
    else:
        print("%s %s" % (tag, name))
    return bool(ok)


def finish():
    n = len(CHECKS)
    bad = [nm for nm, ok in CHECKS if not ok]
    if bad:
        print("VERDICT: %d OF %d CHECKS FAILED" % (len(bad), n))
        sys.exit(1)
    print("VERDICT: ALL %d CHECKS PASS" % n)
    sys.exit(0)


# ------------------------------------------------------- exact linear algebra

def rref(rows, ncols):
    """Reduced row echelon form over Q.  Returns (rows, pivot column list)."""
    mat = [list(r) for r in rows]
    pivots = []
    r = 0
    for c in range(ncols):
        pr = None
        for i in range(r, len(mat)):
            if mat[i][c] != 0:
                pr = i
                break
        if pr is None:
            continue
        mat[r], mat[pr] = mat[pr], mat[r]
        inv = Q1 / mat[r][c]
        mat[r] = [v * inv for v in mat[r]]
        for i in range(len(mat)):
            if i != r and mat[i][c] != 0:
                f = mat[i][c]
                mat[i] = [a - f * b for a, b in zip(mat[i], mat[r])]
        pivots.append(c)
        r += 1
        if r == len(mat):
            break
    return mat[:r], pivots


def rank(rows, ncols):
    return len(rref(rows, ncols)[1])


def in_rowspace(rows, vec, ncols):
    """True iff vec lies in the span of rows."""
    return rank(list(rows) + [list(vec)], ncols) == rank(rows, ncols)


def ideal_piece(gens, nv, d):
    """Rows spanning the degree-d part of the homogeneous ideal (gens)."""
    basis = mons(nv, d)
    idx = dict((m, i) for i, m in enumerate(basis))
    rows = []
    for g in gens:
        e = p_degree(g)
        if e < 0 or e > d:
            continue
        for m in mons(nv, d - e):
            v = [Q0] * len(basis)
            for mg, c in g.items():
                v[idx[tuple(a + b for a, b in zip(m, mg))]] += c
            rows.append(v)
    return basis, idx, rows


class GradedQuotient(object):
    """S/(homogeneous gens) as a graded Q-vector space with normal forms.

    Per degree d the ideal piece is row reduced; pivot monomials are rewritten
    in terms of the non-pivot ones, which form a basis of the degree-d part.
    If some A_d = 0 then A_e = 0 for all e >= d, because S is generated in
    degree 1, so stopping at the first vanishing degree loses nothing.
    """

    def __init__(self, gens, nv, dmax=9):
        self.nv = nv
        self.gens = gens
        self.basis = {}
        self.red = {}
        self.artinian = False
        d = 0
        while d <= dmax:
            mlist, idx, rows = ideal_piece(gens, nv, d)
            red_rows, pivots = rref(rows, len(mlist))
            piv = set(pivots)
            nonpiv = [j for j in range(len(mlist)) if j not in piv]
            self.basis[d] = [mlist[j] for j in nonpiv]
            table = {}
            for pos, j in enumerate(nonpiv):
                v = [Q0] * len(nonpiv)
                v[pos] = Q1
                table[mlist[j]] = v
            for ri, c in enumerate(pivots):
                table[mlist[c]] = [-red_rows[ri][j] for j in nonpiv]
            self.red[d] = table
            if not self.basis[d]:
                self.artinian = True
                self.top = d - 1
                break
            d += 1
        if not self.artinian:
            self.top = dmax
        self.flat = []
        for e in range(self.top + 1):
            for m in self.basis[e]:
                self.flat.append((e, m))
        self.fidx = dict((k, i) for i, k in enumerate(self.flat))
        self.dim = len(self.flat)

    def hilbert(self):
        return [len(self.basis.get(d, [])) for d in range(self.top + 2)]

    def vec_of_poly(self, p):
        v = [Q0] * self.dim
        for m, c in p.items():
            d = sum(m)
            if d > self.top:
                continue
            for t, val in enumerate(self.red[d][m]):
                if val:
                    v[self.fidx[(d, self.basis[d][t])]] += c * val
        return v

    def mult_matrix(self, f):
        """Matrix of multiplication by homogeneous f on A, flat basis."""
        e = p_degree(f)
        M = [[Q0] * self.dim for _ in range(self.dim)]
        for j, (d, m) in enumerate(self.flat):
            dd = d + e
            if dd > self.top:
                continue
            for mg, c in f.items():
                mm = tuple(a + b for a, b in zip(m, mg))
                for t, val in enumerate(self.red[dd][mm]):
                    if val:
                        M[self.fidx[(dd, self.basis[dd][t])]][j] += c * val
        return M


class Koszul(object):
    """Koszul complex K(f_1,...,f_k; A) of an Artinian graded algebra A."""

    def __init__(self, A, fs):
        self.A = A
        self.k = len(fs)
        self.N = A.dim
        self.mats = [A.mult_matrix(f) for f in fs]
        self.wedge = dict((i, list(combinations(range(self.k), i)))
                          for i in range(self.k + 1))
        self.dims = dict((i, len(self.wedge[i]) * self.N)
                         for i in range(self.k + 1))
        self.d = {}
        for i in range(1, self.k + 1):
            nc = self.dims[i]
            nr = self.dims[i - 1]
            pos = dict((T, t) for t, T in enumerate(self.wedge[i - 1]))
            mat = [[Q0] * nc for _ in range(nr)]
            for ti, T in enumerate(self.wedge[i]):
                for l in range(i):
                    ts = pos[T[:l] + T[l + 1:]]
                    sgn = Q1 if l % 2 == 0 else -Q1
                    Mq = self.mats[T[l]]
                    for j in range(self.N):
                        col = ti * self.N + j
                        for r in range(self.N):
                            v = Mq[r][j]
                            if v:
                                mat[ts * self.N + r][col] += sgn * v
            self.d[i] = mat
        self.ranks = dict((i, rank(self.d[i], self.dims[i]))
                          for i in range(1, self.k + 1))

    def homology(self):
        h = []
        for i in range(self.k + 1):
            r_in = self.ranks.get(i + 1, 0)
            r_out = self.ranks.get(i, 0)
            h.append(self.dims[i] - r_out - r_in)
        return h

    def composites_vanish(self):
        for i in range(1, self.k):
            lo, hi = self.d[i], self.d[i + 1]
            for r in range(len(lo)):
                for c in range(self.dims[i + 1]):
                    s = Q0
                    for t in range(self.dims[i]):
                        if lo[r][t] and hi[t][c]:
                            s += lo[r][t] * hi[t][c]
                    if s != 0:
                        return False
        return True

    def graded_rank(self, i, e):
        """Rank of d_i restricted to A_e (x) wedge^i; the map is graded."""
        cols = [ti * self.N + j
                for ti in range(len(self.wedge[i]))
                for j in range(self.N) if self.A.flat[j][0] == e]
        sub = [[row[c] for c in cols] for row in self.d[i]]
        return rank(sub, len(cols))


# ------------------------------------------------- data quoted from the paper
V3 = ["x", "y", "z"]
V4 = ["x", "y", "z", "t"]
V5 = ["x", "y", "z", "t1", "t2"]

# J_0 = (x^2+xy, xz+z^2, y^2+yz) in Q[x,y,z]
J0 = [{(2, 0, 0): Q1, (1, 1, 0): Q1},
      {(1, 0, 1): Q1, (0, 0, 2): Q1},
      {(0, 2, 0): Q1, (0, 1, 1): Q1}]
# I = (x^2, y^2, z^2)
I3 = [{(2, 0, 0): Q1}, {(0, 2, 0): Q1}, {(0, 0, 2): Q1}]
# claimed Groebner basis of J_0 for grevlex with x > y > z
GB_CLAIM = J0 + [{(0, 1, 2): Q1, (0, 0, 3): -Q1}, {(0, 0, 4): Q1}]
# claimed monomial basis of A = S/J_0, by degree
A_BASIS_CLAIM = {0: [(0, 0, 0)],
                 1: [(1, 0, 0), (0, 1, 0), (0, 0, 1)],
                 2: [(1, 1, 0), (0, 1, 1), (0, 0, 2)],
                 3: [(0, 0, 3)]}
T_CLAIM = [[1, -1, 1], [1, 1, -1], [-1, 1, 1]]
DET_T_CLAIM = 4
N_CLAIM, K_CLAIM = 4, 3
TOR_CLAIM = [4, 14, 14, 4]
COLENGTH_CLAIM = 4
PREDICTED_CLAIM = [4, 12, 12, 4]
CHAIN_DIMS_CLAIM = [8, 24, 24, 8]
RANKS_CLAIM = {1: 4, 2: 6, 3: 4}
GRADED_RANKS_CLAIM = {1: (3, 1), 2: (3, 3), 3: (1, 3)}


def lift(p, nv):
    """View a polynomial in the first variables inside nv variables."""
    return dict((m + (0,) * (nv - len(m)), c) for m, c in p.items())


I4 = [lift(g, 4) for g in I3]
J4 = [lift(g, 4) for g in J0] + [{(0, 0, 0, 1): Q1}]


def check_object():
    print("exhibited object:")
    print("  R = Q[x,y,z,t] localized at (x,y,z,t),  dim R = %d" % len(V4))
    print("  I = (%s)" % ", ".join(p_str(g, V4) for g in I4))
    print("  J = (%s)" % ", ".join(p_str(g, V4) for g in J4))
    n, k = len(V4), len(I4)
    ok = (n == N_CLAIM and k == K_CLAIM and len(J4) == n)
    for g in I4 + J4:
        ok = ok and bool(g) and p_homogeneous(g)
    ok = ok and all(m[3] == 0 for g in I4 for m in g)
    ok = ok and all(p_degree(g) == 2 for g in I4)
    ok = ok and all(m[3] == 0 for g in J4[:3] for m in g)
    ok = ok and all(p_degree(g) == 2 for g in J4[:3])
    ok = ok and J4[3] == {(0, 0, 0, 1): Q1}
    ok = ok and [lift(g, 4) for g in J0] == J4[:3]
    ck("object_wellformed", ok,
       "n=%d, k=%d, |gens J|=%d" % (n, k, len(J4)))
    return n, k


def check_hypotheses(n, k):
    ck("hypothesis_k_le_n_minus_1", 1 <= k <= n - 1,
       "k=%d, n=%d, k<=n-1 is %s" % (k, n, k <= n - 1))


def check_gb_membership():
    ok = True
    for g in GB_CLAIM:
        d = p_degree(g)
        mlist, idx, rows = ideal_piece(J0, 3, d)
        v = [Q0] * len(mlist)
        for m, c in g.items():
            v[idx[m]] += c
        if not in_rowspace(rows, v, len(mlist)):
            ok = False
            print("  not in J_0: %s" % p_str(g, V3))
    ck("gb_elements_lie_in_ideal", ok,
       "%d claimed basis elements tested" % len(GB_CLAIM))


def check_gb_certified():
    lms = [leading_monomial(g) for g in GB_CLAIM]
    print("  grevlex leading terms: %s"
          % ", ".join(p_str({m: Q1}, V3) for m in lms))
    ok = True
    std = []
    for d in range(0, 7):
        mlist, idx, rows = ideal_piece(J0, 3, d)
        piv = set(mlist[c] for c in rref(rows, len(mlist))[1])
        lt = set(m for m in mlist
                 if any(all(m[i] >= q[i] for i in range(3)) for q in lms))
        if piv != lt:
            ok = False
            print("  degree %d: initial ideal differs from leading terms" % d)
        std += [m for m in mlist if m not in lt]
    claimed = sorted(sum(A_BASIS_CLAIM.values(), []))
    ok = ok and sorted(std) == claimed
    ck("gb_certified_by_initial_ideal", ok,
       "%d standard monomials through degree 6" % len(std))


def check_hilbert(A):
    hf = A.hilbert()
    ok = (hf == [1, 3, 3, 1, 0] and A.artinian and A.dim == 8)
    for d in sorted(A_BASIS_CLAIM):
        ok = ok and A.basis[d] == A_BASIS_CLAIM[d]
    print("  monomial basis of A: %s"
          % "; ".join(", ".join(p_str({m: Q1}, V3) for m in A.basis[d])
                      for d in range(A.top + 1)))
    ck("A_hilbert_and_monomial_basis", ok,
       "H = %s, length %d" % (hf[:4], A.dim))


def check_primary_and_regular(A):
    """Finite colength for 3 forms in 3 variables forces a regular sequence."""
    mlist, idx, rows = ideal_piece(J0, 3, 4)
    rr = rref(rows, len(mlist))
    ok_pow = (len(rr[1]) == len(mlist))
    B = GradedQuotient(I3, 3)
    ok = (ok_pow and A.artinian and A.dim == 8
          and B.artinian and B.dim == 8
          and len(J0) == 3 and len(I3) == 3)
    ck("regular_sequences_by_finite_colength", ok,
       "(x,y,z)^4 in J_0: %s; colength J_0 = %d = 2*2*2; colength I = %d"
       % (ok_pow, A.dim, B.dim))


def check_q_images(A):
    q = [A.vec_of_poly(g) for g in I3]
    tgt = [A.vec_of_poly({(1, 1, 0): -Q1}),
           A.vec_of_poly({(0, 1, 1): -Q1}),
           A.vec_of_poly({(0, 0, 2): Q1})]
    ok = (q == tgt)
    cols = [j for j, (d, m) in enumerate(A.flat) if d == 2]
    sub = [[v[j] for j in cols] for v in q]
    ok = ok and rank(sub, 3) == 3
    ok = ok and all(v[j] == 0 for v in q for j in range(A.dim)
                    if j not in cols)
    ck("q_normal_forms_span_A2", ok,
       "x^2 = -xy, y^2 = -yz, z^2 = z^2 in A; rank %d" % rank(sub, 3))
    return q


def check_pairing(A):
    row3 = A.fidx[(3, (0, 0, 3))]
    vs = [{(1, 0, 0): Q1}, {(0, 1, 0): Q1}, {(0, 0, 1): Q1}]
    T = [[A.vec_of_poly(p_mul(I3[i], vs[j]))[row3] for j in range(3)]
         for i in range(3)]
    dT = det(T)
    ok = (T == [[Fraction(v) for v in row] for row in T_CLAIM]
          and dT == DET_T_CLAIM and dT != 0)
    print("  A_2 (x) A_1 -> A_3 matrix rows: %s"
          % "; ".join(str([str(v) for v in r]) for r in T))
    ck("multiplication_pairing_matrix", ok, "det T = %s (nonzero)" % dT)


def check_koszul_shape(K):
    dims = [K.dims[i] for i in range(4)]
    ck("koszul_chain_dimensions", dims == CHAIN_DIMS_CLAIM, "dims %s" % dims)
    # d o d = 0 holds for any commuting operators, so on its own it cannot
    # detect a wrong object; it is paired here with a test that the
    # multiplication matrices really represent multiplication in A, which is
    # what the ranks below are read off from.
    engine_ok = True
    for f in I3:
        M = K.A.mult_matrix(f)
        for j, (dg, mg) in enumerate(K.A.flat):
            direct = K.A.vec_of_poly(p_mul(f, {mg: Q1}))
            if [M[r][j] for r in range(K.A.dim)] != direct:
                engine_ok = False
    ck("koszul_differentials_compose_to_zero",
       K.composites_vanish() and engine_ok,
       "d_i d_(i+1) = 0 for i = 1,2 (an identity for any commuting "
       "operators); multiplication matrices agree with normal forms on all "
       "%d basis elements" % K.A.dim)
    ranks = dict((i, K.ranks[i]) for i in (1, 2, 3))
    ck("koszul_differential_ranks", ranks == RANKS_CLAIM,
       "rank d_1,d_2,d_3 = %d,%d,%d" % (ranks[1], ranks[2], ranks[3]))
    gr = {}
    ok = True
    for i in (1, 2, 3):
        gr[i] = tuple(K.graded_rank(i, e) for e in range(4))
        ok = ok and gr[i][:2] == GRADED_RANKS_CLAIM[i]
        ok = ok and gr[i][2] == 0 and gr[i][3] == 0
        ok = ok and sum(gr[i]) == K.ranks[i]
    ck("koszul_graded_ranks", ok,
       "; ".join("d_%d: %s" % (i, list(gr[i])) for i in (1, 2, 3)))


def check_tor_vector(K):
    h = K.homology()
    ck("tor_length_vector_computed", h == TOR_CLAIM,
       "(l(Tor_i))_{i=0..3} = %s" % h)
    return h


def check_colength(A, K):
    img = []
    for f in I3:
        M = A.mult_matrix(f)
        for j in range(A.dim):
            img.append([M[r][j] for r in range(A.dim)])
    r = rank(img, A.dim)
    tgt = []
    for key in [(2, (1, 1, 0)), (2, (0, 1, 1)), (2, (0, 0, 2)),
                (3, (0, 0, 3))]:
        v = [Q0] * A.dim
        v[A.fidx[key]] = Q1
        tgt.append(v)
    same = (rank(img + tgt, A.dim) == r == rank(tgt, A.dim) == 4)
    col = A.dim - r
    ok = (col == COLENGTH_CLAIM and same and col == K.homology()[0])
    ck("colength_R_over_I_plus_J", ok,
       "l(R/(I+J)) = %d, basis 1,x,y,z (ideal = (xy,yz,z^2,z^3))" % col)
    return col


def check_refutation(h, col, k):
    pred = [binom(k, i) * col for i in range(k + 1)]
    ck("conjectured_vector_from_identity", pred == PREDICTED_CLAIM,
       "binom(3,i)*%d = %s" % (col, pred))
    bad = [i for i in range(k + 1) if h[i] != pred[i]]
    good = [i for i in range(k + 1) if h[i] == pred[i]]
    ok = (bad == [1, 2] and good == [0, 3]
          and h[1] == 14 and pred[1] == 12
          and h[2] == 14 and pred[2] == 12)
    ck("identity_fails_refutation", ok,
       "computed %s vs conjectured %s; fails at i in %s" % (h, pred, bad))
    ge = all(h[i] >= pred[i] for i in range(k + 1))
    ck("question_5_1_inequality_holds", ge and h != pred,
       "%s >= %s componentwise and not equal" % (h, pred))


def stabilize(r):
    """S[t_1..t_r]/(J_0 + (t_1..t_r)) and the Koszul complex of x^2,y^2,z^2."""
    nv = 3 + r
    gens = [lift(g, nv) for g in J0]
    for j in range(r):
        e = [0] * nv
        e[3 + j] = 1
        gens.append({tuple(e): Q1})
    A = GradedQuotient(gens, nv)
    K = Koszul(A, [lift(g, nv) for g in I3])
    return nv, gens, A, K


def check_stabilization(r, names):
    nv, gens, A, K = stabilize(r)
    h = K.homology()
    col = A.dim - K.ranks[1]
    pred = [binom(3, i) * col for i in range(4)]
    ok = (A.artinian and A.dim == 8 and len(gens) == nv
          and h == TOR_CLAIM and col == COLENGTH_CLAIM
          and h != pred and nv - 3 == r
          and 3 <= nv - r)
    print("  n = %d, J = (%s)" % (nv, ", ".join(p_str(g, names)
                                                for g in gens)))
    ck("stabilization_gap_%d_tor_vector" % r, ok,
       "n=%d, k=3, n-k=%d: Tor lengths %s, colength %d, conjectured %s"
       % (nv, nv - 3, h, col, pred))


def identity_holds(A, fs):
    """Return (holds, homology, colength) for K(fs; A)."""
    K = Koszul(A, fs)
    h = K.homology()
    col = A.dim - K.ranks[1]
    k = len(fs)
    pred = [binom(k, i) * col for i in range(k + 1)]
    return (h == pred), h, col, pred


def artinian_quotient(gens, nv, dmax=8):
    """A = S/(gens) if it is certified finite dimensional within dmax.

    A triple of forms of degree <= 3 in three variables with finite colength
    has socle degree at most 3+3+3-3, so degree 8 is a sufficient witness.
    """
    A = GradedQuotient(gens, nv, dmax=dmax)
    return A if A.artinian else None


def check_census():
    """Small census over graded complete intersections in three variables.

    Each J is a triple of forms with finite colength, hence a regular
    sequence; each f-prefix of such a triple is a regular sequence too.

    SCOPE, printed below and not to be read past: the census lives in three
    variables, so every instance has n = 3 and J generated by a regular
    sequence of length 3.  Its k = 1 and k = 2 instances therefore satisfy
    k <= n-1 and sit inside Conjecture 4.2's range, but its k = 3 instances
    have k = n, which is the unrestricted assertion already disproved in
    the literature (BLP Section 3) and is OUTSIDE Conjecture 4.2.  The k = 3
    failures found here are consequently NOT independent counterexamples to
    Conjecture 4.2; they become such only after the stabilization
    proposition moves them to n = 4, which is what the two
    stabilization_gap_r checks above do for the paper's own instance.  The
    in-range refutation is carried by identity_fails_refutation together
    with stabilization_gap_1 and stabilization_gap_2, not by this census.
    """
    x, y, z = (1, 0, 0), (0, 1, 0), (0, 0, 1)
    def mo(*ms):
        p = {}
        for c, m in ms:
            p[m] = p.get(m, Q0) + Fraction(c)
        return p_clean(p)
    quads = [
        [mo((1, (2, 0, 0))), mo((1, (0, 2, 0))), mo((1, (0, 0, 2)))],
        J0,
        [mo((1, (2, 0, 0)), (1, (1, 1, 0))), mo((1, (0, 2, 0))),
         mo((1, (0, 0, 2)))],
        [mo((1, (2, 0, 0)), (1, (0, 1, 1))), mo((1, (0, 2, 0)), (1, (1, 0, 1))),
         mo((1, (0, 0, 2)), (1, (1, 1, 0)))],
        # last triple is one dimensional (three coordinate lines) and must be
        # rejected by the finite colength test
        [mo((1, (1, 1, 0))), mo((1, (0, 1, 1))), mo((1, (1, 0, 1)))],
    ]
    seqs = [
        [mo((1, (2, 0, 0))), mo((1, (0, 2, 0))), mo((1, (0, 0, 2)))],
        [mo((1, (2, 0, 0)), (1, (0, 2, 0))), mo((1, (0, 2, 0)), (1, (0, 0, 2))),
         mo((1, (0, 0, 2)), (1, (2, 0, 0)))],
        [mo((1, (1, 0, 0))), mo((1, (0, 1, 0))), mo((1, (0, 0, 1)))],
        [mo((1, (2, 0, 0))), mo((1, (0, 2, 0))),
         mo((1, (0, 0, 2)), (1, (1, 1, 0)))],
        [mo((1, (3, 0, 0))), mo((1, (0, 2, 0))), mo((1, (0, 0, 2)))],
    ]
    # the ambient dimension of the census, derived from the data rather than
    # assumed: every generator is a form in the same number of variables, and
    # every J is a regular sequence of exactly that length, so n = nv here.
    # The f-sequences are held to the same length, which is what makes the
    # largest k tested below equal to n rather than merely at most n.
    widths = set(len(m) for gs in quads + seqs for g in gs for m in g)
    lengths = set(len(gs) for gs in quads + seqs)
    if len(widths) != 1 or lengths != widths:
        raise RuntimeError("census data is not a uniform set of triples of "
                           "forms in a fixed number of variables: monomial "
                           "widths %s, generator counts %s"
                           % (sorted(widths), sorted(lengths)))
    nv_census = sorted(widths)[0]
    n_census = nv_census
    algebras = [artinian_quotient(gs, nv_census) for gs in quads]
    good = [A for A in algebras if A is not None]
    rejected = [i for i, A in enumerate(algebras) if A is None]
    ok_seq = [fs for fs in seqs if artinian_quotient(fs, nv_census) is not None]
    ck("census_finite_colength_screen", rejected == [4] and len(good) == 4
       and len(ok_seq) == len(seqs) and n_census == 3,
       "%d of %d ideals certified zero dimensional; (xy,yz,zx) rejected; "
       "ambient dimension of every census instance is n = %d"
       % (len(good), len(quads), n_census))
    tested = {1: 0, 2: 0, 3: 0}
    fails = {1: 0, 2: 0, 3: 0}
    k3_fail_vectors = []
    ge_all = True
    for A in good:
        for fs in ok_seq:
            for k in (1, 2, 3):
                holds, h, col, pred = identity_holds(A, fs[:k])
                tested[k] += 1
                if not holds:
                    fails[k] += 1
                    ge_all = ge_all and all(h[i] >= pred[i]
                                            for i in range(k + 1))
                    if k == 3:
                        k3_fail_vectors.append((tuple(h), tuple(pred)))
    # the printed instance counts are pinned to the derived size of the census
    # (algebras that passed the screen times sequences that passed it), so a
    # loop that silently skipped instances cannot report a full census.
    n_inst = len(good) * len(ok_seq)
    ck("census_identity_holds_for_k_le_2",
       tested[1] >= 16 and tested[2] >= 16
       and tested[1] == n_inst and tested[2] == n_inst
       and fails[1] == 0 and fails[2] == 0,
       "%d instances with k=1 and %d with k=2, no failure; n = %d throughout, "
       "so these are k <= n-1 and inside Conjecture 4.2's range; the k=1 half "
       "is rank-nullity and cannot fail, so only the k=2 half is evidence"
       % (tested[1], tested[2], n_census))
    CENSUS.update(tested=tested, fails=fails)
    ck("census_finds_k_3_failures",
       fails[3] > 0 and 3 == n_census and tested[3] == n_inst
       and (TOR_CLAIM[0], TOR_CLAIM[1], TOR_CLAIM[2],
            TOR_CLAIM[3]) in [v for v, _ in k3_fail_vectors],
       "%d of %d k=3 instances fail; %s among them; NOT counterexamples to "
       "Conjecture 4.2: k = n = %d here, i.e. the already-refuted "
       "unrestricted case (BLP Section 3), outside the range k <= n-1; these "
       "enter Conjecture 4.2's range only via stabilization, as "
       "stabilization_gap_1 and stabilization_gap_2 do for the paper's "
       "instance"
       % (fails[3], tested[3], TOR_CLAIM, n_census))
    ck("census_failures_respect_inequality", ge_all,
       "every failing instance has Tor lengths >= binom(k,i)*colength (all "
       "failing instances are the k = n = %d ones described above)" % n_census)


def check_k2_control():
    """A control showing the k <= 2 census is discriminating, not vacuous.

    For k = 1 the identity is rank-nullity: Tor_0 = coker(f) and Tor_1 =
    ker(f) on a finite dimensional space, so both equal the colength for any
    f whatever, and no instance can ever fail.  For k = 2 the identity is
    equivalent to rank d_1 = rank d_2, which is NOT automatic: it uses that
    R/J is a complete intersection.  Dropping only that hypothesis, keeping
    f_1, f_2 a regular sequence of the ambient ring, must break it.
    """
    lin = [{(1, 0, 0): Q1}, {(0, 1, 0): Q1}]
    # not a complete intersection: 4 generators, height 3
    bad = GradedQuotient([{(2, 0, 0): Q1}, {(1, 1, 0): Q1},
                          {(0, 2, 0): Q1}, {(0, 0, 1): Q1}], 3)
    # a complete intersection of the same embedding dimension
    ci = GradedQuotient([{(2, 0, 0): Q1}, {(0, 2, 0): Q1},
                         {(0, 0, 1): Q1}], 3)
    hb, vb, cb, pb = identity_holds(bad, lin)
    hc, vc, cc, pc = identity_holds(ci, lin)
    h1, v1, c1, p1 = identity_holds(bad, lin[:1])
    ok = (bad.artinian and ci.artinian and hb is False and hc is True
          and h1 is True and vb != pb and vc == pc)
    ck("k2_criterion_needs_complete_intersection", ok,
       "off hypothesis: %s vs %s (fails); on hypothesis: %s vs %s (holds); "
       "k=1 holds even off hypothesis" % (vb, pb, vc, pc))
    CENSUS["control"] = ok


def check_nonreduced():
    """R/I is nonreduced, so the example is outside the reduced ICIS setting."""
    B = GradedQuotient(I3, 3)
    nil = []
    for v in ["x", "y", "z"]:
        e = [0, 0, 0]
        e[["x", "y", "z"].index(v)] = 1
        lin = B.vec_of_poly({tuple(e): Q1})
        sq = B.vec_of_poly({tuple(2 * a for a in e): Q1})
        if any(c != 0 for c in lin) and all(c == 0 for c in sq):
            nil.append(v)
    ck("R_mod_I_is_nonreduced", nil == ["x", "y", "z"] and B.dim == 8,
       "nonzero nilpotents in R/I: %s" % ", ".join(nil))


def check_minimality(n_obj, k_obj):
    """The smallest pair not excluded by the k <= 2 evidence is (4,3).

    The k >= 3 premise is a literature statement.  It is not assumed here:
    the check is conditioned on the census having found no k <= 2 failure and
    on the control above showing that a k = 2 failure is detectable at all.
    If either collapses, this check fails rather than repeating the claim.
    """
    supported = (CENSUS.get("fails", {}).get(1) == 0
                 and CENSUS.get("fails", {}).get(2) == 0
                 and CENSUS.get("control") is True)
    pairs = [(n, k) for n in range(1, 8) for k in range(1, n) if k >= 3]
    ok = (bool(pairs) and supported
          and min(n for n, k in pairs) == n_obj
          and min(k for n, k in pairs) == k_obj
          and (n_obj, k_obj) in pairs
          and all(n >= k + 1 for n, k in pairs))
    ck("minimality_of_the_pair_n_k", ok,
       "k<=2 evidence stands: %s; over k<=n-1 with k>=3 min (n,k) = (%d,%d), "
       "exhibited (%d,%d)" % (supported, min(n for n, k in pairs),
                              min(k for n, k in pairs), n_obj, k_obj))


def main():
    try:
        n, k = check_object()
        check_hypotheses(n, k)
        check_gb_membership()
        check_gb_certified()
        A = GradedQuotient(J0, 3)
        check_hilbert(A)
        check_primary_and_regular(A)
        if not (A.artinian and A.dim == 8):
            raise RuntimeError("S/J_0 is not the 8 dimensional algebra "
                               "the later checks need")
        check_q_images(A)
        check_pairing(A)
        K = Koszul(A, I3)
        check_koszul_shape(K)
        h = check_tor_vector(K)
        col = check_colength(A, K)
        check_refutation(h, col, k)
        check_stabilization(1, V4)
        check_stabilization(2, V5)
        check_nonreduced()
        check_census()
        check_k2_control()
        check_minimality(n, k)
    except Exception as exc:  # a corrupted input must not exit silently
        ck("verifier_ran_to_completion", False,
           "aborted: %s: %s" % (type(exc).__name__, exc))
    print("NOT RE-RUN: the two cited results that force k >= 3 (the k = 1 and")
    print("k = 2 cases of the identity) are literature statements; they are")
    print("supported here on a finite census, not proved.  The stabilization")
    print("statement is a homological argument valid for every gap; it is")
    print("instantiated here only at gaps 1 and 2 for this example, and no")
    print("exhaustive census over complete intersections was attempted.")
    print("NOT RE-RUN, SCOPE OF THE CENSUS: the census runs in three")
    print("variables, so every instance has n = 3.  Its k = 3 instances have")
    print("k = n, which is the unrestricted assertion already disproved in")
    print("the literature, NOT the k <= n-1 range of the conjecture under")
    print("test; the k = 3 failures counted above are therefore not that many")
    print("independent counterexamples to that conjecture, and they")
    print("enter its range only through the stabilization proposition, which")
    print("is applied here only to the paper's own instance (gaps 1 and 2).")
    print("The in-range refutation rests on identity_fails_refutation with")
    print("stabilization_gap_1 and stabilization_gap_2 alone.  Only the k = 1")
    print("and k = 2 halves of the census are in range, and they are")
    print("confirmations of the cited results, not tests of the conjecture.")
    finish()


if __name__ == "__main__":
    main()
