#!/usr/bin/env python3
"""
verify.py -- referee's verification program for

    "The Maximum Binary Case of Ribot's Zariski-Closedness Conjecture"

Standard library only (fractions, itertools, random).  All decisions are made
with exact integer / Fraction arithmetic; no floating point is used anywhere.

--------------------------------------------------------------------------
VALUES TAKEN FROM THE PAPER (inputs, not checks)
--------------------------------------------------------------------------
  * the support definition  E_delta = {x in {0,1}^d : |x| = delta (mod 2)};
  * Ribot's support  L_2 = {(1,1,1),(1,2,2),(2,1,2),(2,2,1)}  and the index
    dictionary  x_k = i_k - 1  (Section 3);
  * the d=3 choice  Omega = {alpha,beta,gamma,delta} with
    alpha=(1,1,1), beta=(1,1,-1), gamma=(1,-1,1), delta=(-1,1,1);
  * the claimed generator  (1,-1,-1,-1)  of the relation lattice Lambda;
  * the Fourier coordinate  p_eps(T) = 2^{-d} sum_x t_x i^{|x|} eps^x  and
    Phi_m(T) = Im( prod_eps p_eps^{m+} conj(p_eps)^{m-} );
  * the witness polynomial  H = Im(P conj(Q) conj(R) conj(S)),  P = 8 p_alpha
    etc.;
  * Ribot's quartic F of Example 4.1, i.e.
      F = sum_{i,j,k} (-1)^{i+j+k} t_{ijk} g(t_{i+1,j,k},t_{i,j+1,k},
                                             t_{i,j,k+1},t_{i+1,j+1,k+1}),
      g(w,x,y,z) = 2wxy + w^2 z + x^2 z + y^2 z - z^3, indices mod 2;
  * the four numbers asserted about them: H = 4F, 40 nonzero monomials,
    rank Lambda = 2^{d-1} - d, dim X_{E_0} = 2^{d-1} + d.
  * the paper's displayed expansions of P,Q,R,S (checked against the
    definition of p_eps, not assumed).

--------------------------------------------------------------------------
DERIVED HERE (the checks)
--------------------------------------------------------------------------
  A. The exhibited object.  E_0,E_1 are built from scratch, printed, counted,
     and tested for the partial-Latin-hyperrectangle hypothesis (pairwise
     Hamming distance >= 2).  E_0 for d=3 is shown to be exactly Ribot's L_2
     under x_k = i_k - 1.
  B. Maximality (the hypothesis of the paper's Corollary 2).
     alpha(Q_d) is computed -- by exhaustive maximum independent set for
     d <= 4 and by Koenig (n - maximum matching, matching computed with
     augmenting paths) for d <= 10 -- and the *census* of all independent
     sets of size 2^{d-1} is enumerated exhaustively for d = 2..6 to
     confirm that E_0 and E_1 are the only ones (d >= 7 is out of budget and
     the program says so on stdout).
  C. Lemma 5 (Fourier).  p_{-eps} = conj(p_eps) as symbolic linear forms;
     the SO(2)^d equivariance p_eps(R_theta.T) = e^{i<eps,theta>} p_eps(T)
     verified exactly with rational rotations (Pythagorean (c,s), c^2+s^2=1);
     and {T : Im p_eps(T)=0 for eps in Omega} = V_{E_0} by an exact rank
     computation over Q.
  D. The relation lattice.  rank A and rank Lambda are computed by exact
     Gaussian elimination for d = 2..12, for the paper's Omega and for EVERY
     admissible Omega when d <= 5 (2^{2^{d-1}} sign choices); an integer
     kernel basis is produced, and for d=3 the kernel is shown to be
     generated by the primitive vector (1,-1,-1,-1).  Check D6 also verifies
     Lemma 6 (character duality), the algebraic engine of the converse
     inclusion, for the paper's own A on the N-torsion of the torus: im phi
     equals the annihilator of ker A inside mu_N^Omega, enumerated element by
     element for d = 3 (N = 7) and d = 4 (N = 5) and by an exact F_N dimension
     count for d = 2..8 and N = 5, 7, 11.
  E. The equations really do vanish on the orbit.  For d = 2..5, for a
     lattice basis of Lambda and for random Z-combinations of it, Phi_m(z.T0)
     is evaluated in exact Gaussian rationals at rotated members of V_{E_0}
     and must be 0; two controls -- an m with A(m) != 0, and a non-parity
     support of the same cardinality -- must give nonzero values, so the
     check is not vacuous.  Every "must be 0" sample is additionally required
     to have all p_eps(T) != 0 and every m to be nonzero, so that no
     evaluation can be satisfied by a vanishing factor or an empty product.

     SCOPE WARNING.  Section E establishes only the inclusion
     X_{E_0} subset {Phi_m = 0}.  The reverse inclusion -- the whole nontrivial
     content of Theorem 1, and the reason Proposition 7 asserts
     X_{L_2} = {F = 0} rather than merely "contained in" -- is NOT verified
     globally, because deciding membership in the orbit of a given rational
     tensor needs the rotation angles, which are not rational.  What is
     verified instead is (a) its algebraic engine, Lemma 6, exactly (check D6),
     (b) the primitivity/saturation input it consumes (check D6), and (c) the
     first-order statement along the orbit (checks G2, G3).
  F. THE LOAD-BEARING IDENTITY.  H is expanded from the *definition* of
     p_eps with an exact multivariate polynomial class, F is built
     independently from Ribot's formula, the scalar c with H = cF is read off
     from the data, and H == 4F is decided by dictionary equality of the two
     expansions.  Monomial counts are counted, not asserted.
  G. Dimension.  dim X_{E_0} = 2^{d-1} + d is checked as the exact rank of
     the tangent space V_{E_0} + span{infinitesimal rotations} at a generic
     point, for d = 2..8; for d = 3 the gradient of H at an orbit point is
     computed, shown nonzero, and its kernel shown to contain that 7-
     dimensional tangent space -- so {H=0} and X_{L_2} agree to first order.
"""

import itertools
import random
import sys
from fractions import Fraction

CHECKS = []


def ck(name, ok, detail=""):
    CHECKS.append((name, bool(ok)))
    tag = "PASS" if ok else "FAIL"
    if detail:
        print("%s %s [%s]" % (tag, name, detail))
    else:
        print("%s %s" % (tag, name))
    return bool(ok)


def finish():
    n = len(CHECKS)
    bad = [c for c in CHECKS if not c[1]]
    if not bad:
        print("VERDICT: ALL %d CHECKS PASS" % n)
        sys.exit(0)
    print("VERDICT: %d OF %d CHECKS FAILED" % (len(bad), n))
    sys.exit(1)


# ----------------------------------------------------------------------
# 1. exact Gaussian rationals, as pairs (re, im) of Fractions
# ----------------------------------------------------------------------

def gz(re=0, im=0):
    return (Fraction(re), Fraction(im))


def gadd(a, b):
    return (a[0] + b[0], a[1] + b[1])


def gsub(a, b):
    return (a[0] - b[0], a[1] - b[1])


def gmul(a, b):
    return (a[0] * b[0] - a[1] * b[1], a[0] * b[1] + a[1] * b[0])


def gconj(a):
    return (a[0], -a[1])


def gpow(a, n):
    r = gz(1, 0)
    for _ in range(n):
        r = gmul(r, a)
    return r


def gis_zero(a):
    return a[0] == 0 and a[1] == 0


# i^k, exactly
IPOW = [gz(1, 0), gz(0, 1), gz(-1, 0), gz(0, -1)]


# ----------------------------------------------------------------------
# 2. exact multivariate polynomials: dict {exponent tuple -> Fraction}
# ----------------------------------------------------------------------

def p_zero():
    return {}


def p_const(c, nv):
    c = Fraction(c)
    return {} if c == 0 else {(0,) * nv: c}


def p_var(k, nv):
    e = [0] * nv
    e[k] = 1
    return {tuple(e): Fraction(1)}


def p_add(a, b):
    r = dict(a)
    for e, c in b.items():
        v = r.get(e, Fraction(0)) + c
        if v == 0:
            r.pop(e, None)
        else:
            r[e] = v
    return r


def p_scal(a, c):
    c = Fraction(c)
    if c == 0:
        return {}
    return dict((e, v * c) for e, v in a.items())


def p_sub(a, b):
    return p_add(a, p_scal(b, -1))


def p_mul(a, b):
    r = {}
    for ea, ca in a.items():
        for eb, cb in b.items():
            e = tuple(x + y for x, y in zip(ea, eb))
            v = r.get(e, Fraction(0)) + ca * cb
            if v == 0:
                r.pop(e, None)
            else:
                r[e] = v
    return r


def p_eq(a, b):
    return p_sub(a, b) == {}


def p_degrees(a):
    return set(sum(e) for e in a)


def p_eval(a, vals):
    tot = Fraction(0)
    for e, c in a.items():
        t = c
        for k, ek in enumerate(e):
            if ek:
                t *= vals[k] ** ek
        tot += t
    return tot


def p_diff(a, k):
    r = {}
    for e, c in a.items():
        if e[k] == 0:
            continue
        f = list(e)
        f[k] -= 1
        f = tuple(f)
        v = r.get(f, Fraction(0)) + c * e[k]
        if v == 0:
            r.pop(f, None)
        else:
            r[f] = v
    return r


# ----------------------------------------------------------------------
# 3. complex polynomials: pair (real part, imaginary part)
# ----------------------------------------------------------------------

def c_zero():
    return (p_zero(), p_zero())


def c_add(a, b):
    return (p_add(a[0], b[0]), p_add(a[1], b[1]))


def c_mul(a, b):
    return (p_sub(p_mul(a[0], b[0]), p_mul(a[1], b[1])),
            p_add(p_mul(a[0], b[1]), p_mul(a[1], b[0])))


def c_conj(a):
    return (a[0], p_scal(a[1], -1))


def c_scal(a, g):
    """multiply by the Gaussian rational g = (gr, gi)"""
    gr, gi = g
    return (p_sub(p_scal(a[0], gr), p_scal(a[1], gi)),
            p_add(p_scal(a[0], gi), p_scal(a[1], gr)))


def c_pow(a, n, nv):
    r = (p_const(1, nv), p_zero())
    for _ in range(n):
        r = c_mul(r, a)
    return r


# ----------------------------------------------------------------------
# 4. the paper's objects, built from scratch
# ----------------------------------------------------------------------

def cube(d):
    """all x in {0,1}^d, lexicographic (x_1 most significant)"""
    return [tuple(t) for t in itertools.product((0, 1), repeat=d)]


def var_index(x):
    """position of the coordinate t_x among the 2^d variables"""
    k = 0
    for b in x:
        k = 2 * k + b
    return k


def E_delta(d, delta):
    return [x for x in cube(d) if sum(x) % 2 == delta]


def hamming(x, y):
    return sum(1 for a, b in zip(x, y) if a != b)


def scaled_p(d, eps):
    """the complex polynomial 2^d * p_eps in the 2^d variables t_x.

    Coefficient of t_x is i^{|x|} * eps^x, straight from the definition."""
    nv = 1 << d
    out = c_zero()
    for x in cube(d):
        sgn = 1
        for k in range(d):
            if x[k] == 1 and eps[k] == -1:
                sgn = -sgn
        coeff = c_scal((p_var(var_index(x), nv), p_zero()), IPOW[sum(x) % 4])
        out = c_add(out, c_scal(coeff, gz(sgn, 0)))
    return out


def omega_paper(d):
    """one representative per antipodal pair: those with eps_1 = +1 ...

    for d = 3 the paper's own list is used verbatim (see PAPER_OMEGA3)."""
    return [tuple(e) for e in itertools.product((1, -1), repeat=d) if e[0] == 1]


# ----------------------------------------------------------------------
# 5. exact linear algebra over Q
# ----------------------------------------------------------------------

def rref(rows):
    """reduced row echelon form; returns (matrix, pivot columns)"""
    m = [[Fraction(v) for v in r] for r in rows]
    if not m:
        return [], []
    ncol = len(m[0])
    piv = []
    r = 0
    for c in range(ncol):
        s = None
        for k in range(r, len(m)):
            if m[k][c] != 0:
                s = k
                break
        if s is None:
            continue
        m[r], m[s] = m[s], m[r]
        inv = Fraction(1) / m[r][c]
        m[r] = [v * inv for v in m[r]]
        for k in range(len(m)):
            if k != r and m[k][c] != 0:
                f = m[k][c]
                m[k] = [a - f * b for a, b in zip(m[k], m[r])]
        piv.append(c)
        r += 1
        if r == len(m):
            break
    return m, piv


def rank(rows):
    return len(rref(rows)[1])


def kernel_basis(rows, ncol):
    """basis of {v : rows . v = 0}, entries cleared to integers"""
    m, piv = rref(rows)
    free = [c for c in range(ncol) if c not in piv]
    out = []
    for f in free:
        v = [Fraction(0)] * ncol
        v[f] = Fraction(1)
        for r, c in enumerate(piv):
            v[c] = -m[r][f]
        den = 1
        for a in v:
            den = den * a.denominator // gcd(den, a.denominator)
        iv = [int(a * den) for a in v]
        g = 0
        for a in iv:
            g = gcd(g, abs(a))
        if g > 1:
            iv = [a // g for a in iv]
        out.append(iv)
    return out


def gcd(a, b):
    while b:
        a, b = b, a % b
    return abs(a)


def rank_mod(rows, p):
    """rank over the prime field F_p, exact integer arithmetic"""
    m = [[int(v) % p for v in r] for r in rows]
    if not m:
        return 0
    ncol = len(m[0])
    r = 0
    for c in range(ncol):
        s = None
        for k in range(r, len(m)):
            if m[k][c] % p:
                s = k
                break
        if s is None:
            continue
        m[r], m[s] = m[s], m[r]
        inv = pow(m[r][c], p - 2, p)
        m[r] = [(v * inv) % p for v in m[r]]
        for k in range(len(m)):
            if k != r and m[k][c] % p:
                f = m[k][c]
                m[k] = [(a - f * b) % p for a, b in zip(m[k], m[r])]
        r += 1
        if r == len(m):
            break
    return r


# ----------------------------------------------------------------------
# 6. the hypercube graph Q_d: matching, independence number, census
# ----------------------------------------------------------------------

def qd_adj(d):
    """neighbour bitmask per vertex of Q_d, vertices 0..2^d-1"""
    n = 1 << d
    return [sum(1 << (v ^ (1 << k)) for k in range(d)) for v in range(n)]


def max_matching_qd(d):
    """maximum bipartite matching of Q_d by augmenting paths (Kuhn)"""
    n = 1 << d
    left = [v for v in range(n) if bin(v).count("1") % 2 == 0]
    nb = [[v ^ (1 << k) for k in range(d)] for v in range(n)]
    match = {}

    def try_aug(u, seen):
        for w in nb[u]:
            if w in seen:
                continue
            seen.add(w)
            if w not in match or try_aug(match[w], seen):
                match[w] = u
                return True
        return False

    size = 0
    for u in left:
        if try_aug(u, set()):
            size += 1
    return size, match


def census_max_independent(d, target, node_cap=None):
    """all independent sets of Q_d of size exactly `target`, exhaustively.

    Returns (list_of_sets, nodes_explored, complete_flag)."""
    n = 1 << d
    adj = qd_adj(d)
    found = []
    nodes = [0]
    truncated = [False]

    def dfs(i, chosen, banned, cnt):
        nodes[0] += 1
        if node_cap is not None and nodes[0] > node_cap:
            truncated[0] = True
            return
        if cnt == target:
            found.append(tuple(chosen))
            return
        if cnt + (n - i) < target:
            return
        if i >= n:
            return
        if not (banned >> i) & 1:
            chosen.append(i)
            dfs(i + 1, chosen, banned | adj[i], cnt + 1)
            chosen.pop()
        dfs(i + 1, chosen, banned, cnt)

    dfs(0, [], 0, 0)
    return found, nodes[0], not truncated[0]


def brute_alpha(d):
    """independence number of Q_d by exhaustive subset search (small d)"""
    n = 1 << d
    adj = qd_adj(d)
    best = 0
    for mask in range(1 << n):
        ok = True
        m = mask
        while m:
            v = (m & -m).bit_length() - 1
            if adj[v] & mask:
                ok = False
                break
            m &= m - 1
        if ok:
            c = bin(mask).count("1")
            if c > best:
                best = c
    return best


# ----------------------------------------------------------------------
# 7. exact numeric layer: rational tensors, rational rotations, p_eps
# ----------------------------------------------------------------------

# rational points of S^1 (Pythagorean), used as exact rotations
PYTH = [(Fraction(3, 5), Fraction(4, 5)), (Fraction(5, 13), Fraction(12, 13)),
        (Fraction(8, 17), Fraction(15, 17)), (Fraction(-7, 25), Fraction(24, 25)),
        (Fraction(20, 29), Fraction(-21, 29)), (Fraction(1), Fraction(0)),
        (Fraction(-9, 41), Fraction(-40, 41)), (Fraction(28, 53), Fraction(45, 53))]


def rotate_mode(d, t, k, c, s):
    """apply [[c,-s],[s,c]] in mode k to the dict-free list t of length 2^d"""
    n = 1 << d
    out = list(t)
    bit = 1 << (d - 1 - k)
    for v in range(n):
        if v & bit:
            continue
        w = v | bit
        a, b = t[v], t[w]
        out[v] = c * a - s * b
        out[w] = s * a + c * b
    return out


def rotate_all(d, t, angles):
    for k, (c, s) in enumerate(angles):
        t = rotate_mode(d, t, k, c, s)
    return t


def p_eps_value(d, eps, t):
    """p_eps(T) as an exact Gaussian rational, straight from the definition"""
    acc = gz(0, 0)
    for x in cube(d):
        sgn = 1
        for k in range(d):
            if x[k] == 1 and eps[k] == -1:
                sgn = -sgn
        term = gmul(IPOW[sum(x) % 4], gz(t[var_index(x)] * sgn, 0))
        acc = gadd(acc, term)
    inv = Fraction(1, 1 << d)
    return (acc[0] * inv, acc[1] * inv)


def phi_m_value(d, omega, m, t):
    """Phi_m(T) exactly: Im( prod p_eps^{m+} conj(p_eps)^{m-} )"""
    acc = gz(1, 0)
    for j, eps in enumerate(omega):
        p = p_eps_value(d, eps, t)
        if m[j] > 0:
            acc = gmul(acc, gpow(p, m[j]))
        elif m[j] < 0:
            acc = gmul(acc, gpow(gconj(p), -m[j]))
    return acc[1]


def z_pow_eps(angles, eps):
    """z^eps for z_k = c_k + i s_k, exactly"""
    acc = gz(1, 0)
    for (c, s), e in zip(angles, eps):
        z = (c, s)
        acc = gmul(acc, z if e == 1 else gconj(z))
    return acc


def random_tensor_in_V(d, delta, rng):
    """a rational tensor supported on E_delta"""
    t = [Fraction(0)] * (1 << d)
    for x in E_delta(d, delta):
        t[var_index(x)] = Fraction(rng.randint(-9, 9), rng.randint(1, 5))
    return t


def random_tensor(d, rng):
    return [Fraction(rng.randint(-9, 9), rng.randint(1, 5))
            for _ in range(1 << d)]


# ----------------------------------------------------------------------
# 8. the 2x2x2 quartic: H from the definition, F from Ribot's formula
# ----------------------------------------------------------------------

VAR_NAMES = ["t111", "t112", "t121", "t122", "t211", "t212", "t221", "t222"]

# INPUT (paper, Section 3): the choice of Omega
PAPER_OMEGA3 = [(1, 1, 1), (1, 1, -1), (1, -1, 1), (-1, 1, 1)]
PAPER_GEN3 = [1, -1, -1, -1]          # INPUT: claimed generator of Lambda


def ijk_index(i, j, k):
    return 4 * (i - 1) + 2 * (j - 1) + (k - 1)


def flip(i):
    return 2 if i == 1 else 1


def build_F():
    """Ribot's quartic of Example 4.1, built from its formula"""
    nv = 8
    T = [p_var(v, nv) for v in range(nv)]

    def g(w, x, y, z):
        out = p_scal(p_mul(p_mul(w, x), y), 2)
        for u in (w, x, y):
            out = p_add(out, p_mul(p_mul(u, u), z))
        return p_sub(out, p_mul(p_mul(z, z), z))

    F = p_zero()
    for i in (1, 2):
        for j in (1, 2):
            for k in (1, 2):
                sgn = -1 if (i + j + k) % 2 else 1
                term = p_mul(T[ijk_index(i, j, k)],
                             g(T[ijk_index(flip(i), j, k)],
                               T[ijk_index(i, flip(j), k)],
                               T[ijk_index(i, j, flip(k))],
                               T[ijk_index(flip(i), flip(j), flip(k))]))
                F = p_add(F, p_scal(term, sgn))
    return F


def build_H():
    """H = Im(P conj(Q) conj(R) conj(S)) with P = 8 p_alpha, ... """
    P = scaled_p(3, PAPER_OMEGA3[0])
    Q = scaled_p(3, PAPER_OMEGA3[1])
    R = scaled_p(3, PAPER_OMEGA3[2])
    S = scaled_p(3, PAPER_OMEGA3[3])
    prod = c_mul(c_mul(c_mul(P, c_conj(Q)), c_conj(R)), c_conj(S))
    return prod[1], (P, Q, R, S)


def linear_form_str(pol):
    """render a linear polynomial as a signed sum of variable names"""
    parts = []
    for v in range(8):
        e = [0] * 8
        e[v] = 1
        c = pol.get(tuple(e), Fraction(0))
        if c == 0:
            continue
        sg = "+" if c > 0 else "-"
        mag = "" if abs(c) == 1 else str(abs(c))
        parts.append("%s%s%s" % (sg, mag, VAR_NAMES[v]))
    return "".join(parts) if parts else "0"


def scalar_ratio(a, b):
    """the unique c with a == c*b, or None if no such scalar exists"""
    if not b:
        return None
    e0 = sorted(b)[0]
    if e0 not in a:
        return None
    c = a[e0] / b[e0]
    return c if p_eq(a, p_scal(b, c)) else None


# INPUT (paper, Section 3): Ribot's support L_2
PAPER_L2 = [(1, 1, 1), (1, 2, 2), (2, 1, 2), (2, 2, 1)]

# INPUT (paper, proof of Prop. 7): the displayed expansions of P,Q,R,S
PAPER_PQRS = [
    ("P", "+t111-t122-t212-t221", "+t112+t121+t211-t222"),
    ("Q", "+t111+t122+t212-t221", "-t112+t121+t211+t222"),
    ("R", "+t111+t122-t212+t221", "+t112-t121+t211+t222"),
    ("S", "+t111-t122+t212+t221", "+t112+t121-t211+t222"),
]

DMAX_STRUCT = 12       # range for the purely combinatorial / rank checks
CENSUS_DMAX = 6        # exhaustive independent-set census range


# ----------------------------------------------------------------------
# A. the exhibited object
# ----------------------------------------------------------------------

def section_A():
    print("--- A. the exhibited object ---")
    e0 = E_delta(3, 0)
    print("    E_0 (d=3)  = %s" % (sorted(e0),))
    print("    +1 shifted = %s" % (sorted(tuple(a + 1 for a in x) for x in e0),))
    print("    Ribot L_2  = %s" % (sorted(PAPER_L2),))

    ok = all(len(E_delta(d, s)) == (1 << (d - 1))
             for d in range(2, DMAX_STRUCT + 1) for s in (0, 1))
    ck("A1_cardinality_2^(d-1)", ok, "d=2..%d, both parities" % DMAX_STRUCT)

    ok = True
    for d in range(2, DMAX_STRUCT + 1):
        a, b = set(E_delta(d, 0)), set(E_delta(d, 1))
        if a & b or (a | b) != set(cube(d)) or len(a) + len(b) != (1 << d):
            ok = False
    ck("A2_E0_E1_partition_cube", ok, "d=2..%d" % DMAX_STRUCT)

    worst = None
    for d in range(2, 11):
        for s in (0, 1):
            L = E_delta(d, s)
            for u, v in itertools.combinations(L, 2):
                h = hamming(u, v)
                if worst is None or h < worst:
                    worst = h
    ck("A3_parity_class_is_partial_latin", worst is not None and worst >= 2,
       "min Hamming distance over d=2..10 = %s (need >= 2)" % worst)

    shifted = set(tuple(a + 1 for a in x) for x in e0)
    ck("A4_E0_equals_Ribot_L2", shifted == set(PAPER_L2),
       "set equality under x_k = i_k - 1")

    hs = [hamming(u, v) for u, v in itertools.combinations(PAPER_L2, 2)]
    ck("A5_L2_is_partial_latin", len(hs) == 6 and min(hs) >= 2,
       "pairwise Hamming distances = %s" % sorted(hs))

    ok = True
    for d in range(2, DMAX_STRUCT + 1):
        img = set(tuple(1 - x[0] if k == 0 else x[k] for k in range(d))
                  for x in E_delta(d, 0))
        if img != set(E_delta(d, 1)):
            ok = False
    ck("A6_swap_e0_e1_maps_E0_onto_E1", ok,
       "one-factor swap is a bijection E_0 -> E_1, d=2..%d" % DMAX_STRUCT)


# ----------------------------------------------------------------------
# B. maximality of the support, and the census behind the Corollary
# ----------------------------------------------------------------------

def section_B():
    print("--- B. maximality and the census ---")

    ok = True
    detail = []
    for d in (2, 3, 4):
        a = brute_alpha(d)
        detail.append("alpha(Q_%d)=%d" % (d, a))
        if a != (1 << (d - 1)):
            ok = False
    ck("B1_alpha_Qd_exhaustive", ok, ", ".join(detail) + " (all subsets)")

    ok = True
    detail = []
    for d in range(2, 11):
        nu, _ = max_matching_qd(d)
        alpha = (1 << d) - nu           # Koenig, Q_d bipartite
        if nu != (1 << (d - 1)) or alpha != (1 << (d - 1)):
            ok = False
        if d <= 5 or d == 10:
            detail.append("d=%d:nu=%d,alpha=%d" % (d, nu, alpha))
    ck("B2_perfect_matching_gives_alpha", ok,
       "d=2..10; " + ", ".join(detail))

    ok = True
    detail = []
    for d in range(2, CENSUS_DMAX + 1):
        tgt = 1 << (d - 1)
        sets, nodes, complete = census_max_independent(d, tgt)
        want = set()
        for s in (0, 1):
            want.add(tuple(sorted(var_index(x) for x in E_delta(d, s))))
        got = set(tuple(sorted(s)) for s in sets)
        if not complete or got != want or len(got) != 2:
            ok = False
        detail.append("d=%d:%d sets/%d nodes" % (d, len(got), nodes))
    ck("B3_census_only_E0_E1", ok,
       "; ".join(detail) + "  (exhaustive for d<=%d)" % CENSUS_DMAX)
    print("    NOT RE-RUN: the independent-set census for d >= %d "
          "(search tree grows ~10^3 per dimension; d=%d already costs ~9*10^7 "
          "nodes).  Every other check below runs for the full stated range."
          % (CENSUS_DMAX + 1, CENSUS_DMAX))

    # a control: sets of size 2^{d-1}+1 must NOT exist (so B3 is not vacuous)
    ok = True
    for d in (2, 3, 4, 5):
        sets, _, complete = census_max_independent(d, (1 << (d - 1)) + 1)
        if sets or not complete:
            ok = False
    ck("B4_no_independent_set_of_size_2^(d-1)+1", ok,
       "exhaustive, d=2..5")


# ----------------------------------------------------------------------
# C. Lemma 5 (the Fourier lemma)
# ----------------------------------------------------------------------

def lin_row(pol, nv):
    row = [Fraction(0)] * nv
    for e, c in pol.items():
        assert sum(e) == 1
        row[list(e).index(1)] = c
    return row


def section_C():
    print("--- C. Lemma 5 (Fourier) ---")

    ok = True
    for d in (2, 3, 4, 5):
        for eps in itertools.product((1, -1), repeat=d):
            a = scaled_p(d, eps)
            b = scaled_p(d, tuple(-e for e in eps))
            if not (p_eq(a[0], b[0]) and p_eq(a[1], p_scal(b[1], -1))):
                ok = False
    ck("C1_p_minus_eps_is_conjugate", ok,
       "symbolic identity over all eps, d=2..5")

    rng = random.Random(20260824)
    ok, tested = True, 0
    for d in (2, 3, 4, 5):
        for _ in range(4):
            t = random_tensor(d, rng)
            angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(d)]
            rt = rotate_all(d, t, angles)
            for eps in itertools.product((1, -1), repeat=d):
                lhs = p_eps_value(d, eps, rt)
                rhs = gmul(z_pow_eps(angles, eps), p_eps_value(d, eps, t))
                tested += 1
                if lhs != rhs:
                    ok = False
    ck("C2_SO2d_equivariance", ok,
       "%d exact Gaussian-rational identities, rational rotations, d=2..5"
       % tested)

    ok = True
    detail = []
    for d in range(2, 9):
        nv = 1 << d
        omega = omega_paper(d) if d != 3 else PAPER_OMEGA3
        rows = [lin_row(scaled_p(d, eps)[1], nv) for eps in omega]
        r = rank(rows)
        # The target 2^(d-1) is also the number of rows, so "rank == 2^(d-1)"
        # alone would be satisfied by a rank routine that returned len(rows).
        # Re-rank a deliberately dependent augmentation: the answer must not
        # move even though the row count did.
        aug = rows + [rows[0], [a + b for a, b in zip(rows[0], rows[-1])]]
        r_aug = rank(aug)
        odd = set(var_index(x) for x in E_delta(d, 1))
        support_ok = all(rows[i][j] == 0
                         for i in range(len(rows)) for j in range(nv)
                         if j not in odd)
        if r != (1 << (d - 1)) or r_aug != r or not support_ok:
            ok = False
        if d <= 4:
            detail.append("d=%d:rank=%d" % (d, r))
    ck("C3_real_p_eps_cuts_out_V_E0", ok,
       "Im p_eps involves only odd-weight coordinates and the "
       "2^(d-1) forms are independent, d=2..8; " + ", ".join(detail))

    rng = random.Random(7)
    ok, nz = True, 0
    for d in (2, 3, 4, 5):
        omega = omega_paper(d) if d != 3 else PAPER_OMEGA3
        for _ in range(6):
            t = random_tensor_in_V(d, 0, rng)
            if any(p_eps_value(d, eps, t)[1] != 0 for eps in omega):
                ok = False
            t1 = random_tensor(d, rng)
            if any(p_eps_value(d, eps, t1)[1] != 0 for eps in omega):
                nz += 1
    ck("C4_forward_direction_and_control", ok and nz > 0,
       "tensors in V_E0 give real p_eps; %d generic tensors do not" % nz)


# ----------------------------------------------------------------------
# D. the relation lattice Lambda = ker A
# ----------------------------------------------------------------------

def A_rows(omega, d):
    """the d x |Omega| integer matrix of A(m) = sum m_eps eps"""
    return [[Fraction(eps[k]) for eps in omega] for k in range(d)]


def A_apply(omega, m, d):
    return tuple(sum(m[j] * omega[j][k] for j in range(len(omega)))
                 for k in range(d))


def admissible_omegas(d):
    """every choice of one representative per antipodal pair"""
    reps = [e for e in itertools.product((1, -1), repeat=d) if e[0] == 1]
    for signs in itertools.product((1, -1), repeat=len(reps)):
        yield [tuple(s * c for c in e) for s, e in zip(signs, reps)]


def section_D():
    print("--- D. the relation lattice ---")

    ok, detail = True, []
    for d in range(2, DMAX_STRUCT + 1):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        n = len(omega)
        rA = rank(A_rows(omega, d))
        # A has exactly d rows, so "rank A == d" alone cannot distinguish a
        # correct rank from len(rows); re-rank a dependent augmentation.
        rA_aug = rank(A_rows(omega, d) + [A_rows(omega, d)[0]])
        ker = kernel_basis(A_rows(omega, d), n)
        if n != (1 << (d - 1)) or rA != d or rA_aug != d \
                or len(ker) != (1 << (d - 1)) - d:
            ok = False
        if any(A_apply(omega, v, d) != (0,) * d for v in ker):
            ok = False
        if d <= 6:
            detail.append("d=%d:|Omega|=%d,rk A=%d,rk Lambda=%d"
                          % (d, n, rA, len(ker)))
    ck("D1_rank_Lambda_is_2^(d-1)_minus_d", ok,
       "; ".join(detail) + " (d=2..%d, kernel basis verified in ker A)"
       % DMAX_STRUCT)

    ok, cnt = True, 0
    for d in (2, 3, 4, 5):
        for omega in admissible_omegas(d):
            cnt += 1
            if rank(A_rows(omega, d)) != d:
                ok = False
                break
    ck("D2_rank_d_for_every_admissible_Omega", ok,
       "%d sign choices, d=2..5 exhaustive" % cnt)

    ker3 = kernel_basis(A_rows(PAPER_OMEGA3, 3), 4)
    g = PAPER_GEN3
    ok = (len(ker3) == 1
          and A_apply(PAPER_OMEGA3, g, 3) == (0, 0, 0)
          and (ker3[0] == g or ker3[0] == [-a for a in g]))
    gg = 0
    for a in g:
        gg = gcd(gg, abs(a))
    ck("D3_Lambda3_is_Z_times_1m1m1m1", ok and gg == 1,
       "computed kernel basis %s, A(g)=%s, gcd=%d"
       % (ker3, A_apply(PAPER_OMEGA3, g, 3), gg))

    bad = [(1, 1, -1, -1), (1, 0, 0, 0), (0, 1, 1, 1), (2, -1, -1, -1)]
    ok = all(A_apply(PAPER_OMEGA3, m, 3) != (0, 0, 0) for m in bad)
    ck("D4_control_nonrelations_have_A_nonzero", ok,
       "A%s = %s" % (bad[0], A_apply(PAPER_OMEGA3, bad[0], 3)))

    # The paper's spanning step is  e_j = (v - v_j)/2  with v = (1,...,1).
    # Checking that identity alone is a tautology -- it holds for every d with
    # no reference to Omega, so it cannot fail.  What has content is that the
    # two vectors the step consumes really are available in the chosen Omega
    # (up to the antipodal sign, which the step is allowed to absorb) and that
    # the family it uses spans the same space as the actual columns of A.
    ok = True
    why = []
    for d in range(2, DMAX_STRUCT + 1):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        oset = set(omega)
        v = (1,) * d
        fam = [v]
        for j in range(d):
            vj = tuple(-1 if k == j else 1 for k in range(d))
            fam.append(vj)
            for u in (v, vj):
                if u not in oset and tuple(-a for a in u) not in oset:
                    ok = False
                    why.append("d=%d: %s not an antipodal rep of Omega"
                               % (d, (u,)))
            ej = tuple(Fraction(a - b, 2) for a, b in zip(v, vj))
            want = tuple(Fraction(1) if k == j else Fraction(0)
                         for k in range(d))
            if ej != want:
                ok = False
                why.append("d=%d j=%d: (v-v_j)/2 = %s" % (d, j, (ej,)))
        rf = rank([[Fraction(a) for a in r] for r in fam])
        ra = rank(A_rows(omega, d))
        if rf != d or ra != d or rf != ra:
            ok = False
            why.append("d=%d: rank{v,v_j} = %d, rank A = %d, want %d"
                       % (d, rf, ra, d))
    ck("D5_span_argument_e_j_equals_half_v_minus_vj", ok,
       "v and every v_j are antipodal representatives of the chosen Omega, "
       "(v-v_j)/2 = e_j, and rank{v,v_1..v_d} = rank A = d (computed), "
       "d=2..%d%s" % (DMAX_STRUCT, "" if ok else "; " + "; ".join(why[:3])))


# ----------------------------------------------------------------------
# E. the equations vanish on the orbit  (X_{E_0} subset of {Phi_m = 0})
# ----------------------------------------------------------------------

def section_E():
    print("--- E. Phi_m vanishes on the orbit ---")
    rng = random.Random(31337)
    ok, tested = True, 0
    worst = None
    for d in (2, 3, 4, 5):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        lam = kernel_basis(A_rows(omega, d), len(omega))
        for trial in range(3):
            t0 = random_tensor_in_V(d, 0, rng)
            angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(d)]
            t = rotate_all(d, t0, angles)
            # NON-VACUITY: Phi_m = 0 must be a genuine cancellation of phases,
            # not a product one of whose factors happens to vanish.  A random
            # draw can hand us a degenerate tensor with p_eps(T) = 0, and then
            # Phi_m(T) = 0 for every m whatever the theorem says.
            if any(gis_zero(p_eps_value(d, eps, t)) for eps in omega):
                ok = False
                worst = (d, "degenerate sample: some p_eps(T) = 0")
            for mv in lam:
                val = phi_m_value(d, omega, mv, t)
                tested += 1
                if val != 0:
                    ok = False
                    worst = (d, mv, val)
    ck("E1_Phi_m_zero_on_rotated_V_E0", ok,
       "%d exact evaluations, d=2..5, rational rotations, every sample with "
       "all p_eps(T) != 0 so no evaluation is vacuous%s"
       % (tested, "" if ok else "; failure %s" % (worst,)))

    # control: an m OUTSIDE Lambda must not vanish on the orbit
    ok, hits = False, 0
    for d in (3, 4):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        for _ in range(6):
            t0 = random_tensor_in_V(d, 0, rng)
            angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(d)]
            t = rotate_all(d, t0, angles)
            m = [0] * len(omega)
            m[0] = 1
            if A_apply(omega, m, d) == (0,) * d:
                continue
            if phi_m_value(d, omega, m, t) != 0:
                hits += 1
                ok = True
    ck("E2_control_m_not_in_Lambda_does_not_vanish", ok,
       "%d nonzero values of Phi_m on the orbit for m with A(m) != 0" % hits)

    # the parity support really is needed: a NON-parity support of the same
    # size must break E1 for at least one m in Lambda
    # The draw must be forced away from zero.  With rng.randint(-9,9) an entry
    # can come out 0; dropping t_111 collapses this support onto a subset of
    # E_0 and Phi_m vanishes for a reason that has nothing to do with the
    # control -- which is why the threshold used to be "hits >= 6" and the
    # printed score was 11/12.  Non-degenerate draws must fire 12/12.
    hits = 0
    rng3 = random.Random(880301)
    d = 3
    omega = PAPER_OMEGA3
    lam = kernel_basis(A_rows(omega, d), len(omega))
    for _ in range(12):
        t0 = [Fraction(0)] * 8
        # support {000,011,101,111}: contains the edge 101-111, not a
        # partial Latin hyperrectangle, and not a parity class
        for x in [(0, 0, 0), (0, 1, 1), (1, 0, 1), (1, 1, 1)]:
            num = 0
            while num == 0:
                num = rng3.randint(-9, 9)
            t0[var_index(x)] = Fraction(num, rng3.randint(1, 5))
        angles = [PYTH[rng3.randrange(len(PYTH))] for _ in range(d)]
        t = rotate_all(d, t0, angles)
        if any(phi_m_value(d, omega, mv, t) != 0 for mv in lam):
            hits += 1
    ck("E3_control_non_parity_support_breaks_it", hits == 12,
       "%d/12 rotated tensors on the support {000,011,101,111} have "
       "Phi_m != 0 (all 12 entries drawn nonzero, so every trial is a real "
       "test)" % hits)

    # general m in Lambda, not just basis vectors
    ok, tested = True, 0
    for d in (3, 4, 5):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        lam = kernel_basis(A_rows(omega, d), len(omega))
        for _ in range(4):
            # m = 0 would make Phi_m the empty product, whose imaginary part is
            # 0 for every T; resample until the combination is nontrivial.
            mv = [0] * len(omega)
            while all(a == 0 for a in mv):
                mv = [0] * len(omega)
                for b in lam:
                    c = rng.randint(-2, 2)
                    if c:
                        mv = [a + c * y for a, y in zip(mv, b)]
            if A_apply(omega, mv, d) != (0,) * d:
                ok = False
            t0 = random_tensor_in_V(d, 0, rng)
            angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(d)]
            t = rotate_all(d, t0, angles)
            tested += 1
            if any(gis_zero(p_eps_value(d, eps, t)) for eps in omega):
                ok = False          # same non-vacuity guard as E1
            if phi_m_value(d, omega, mv, t) != 0:
                ok = False
    ck("E4_Phi_zero_for_random_lattice_elements", ok,
       "%d nonzero random Z-combinations of the Lambda basis, d=3,4,5, "
       "all samples with p_eps(T) != 0" % tested)


def section_D6():
    """(i) the computed Lambda basis is a Z-basis of ker A -- and is the very
    basis that E1/E4 evaluate; (ii) Lemma 6 (character duality), the algebraic
    engine of the converse inclusion, is verified exactly for the paper's own A
    on the N-torsion mu_N of the torus: im phi = ann(ker A) inside mu_N^Omega.
    For d = 3 and d = 4 both sides are enumerated element by element; for
    d = 2..8 the two dimensions are computed over F_N and compared."""
    ok = True
    why = []
    exhaustive = []
    for d in range(2, 9):
        omega = PAPER_OMEGA3 if d == 3 else omega_paper(d)
        rows = A_rows(omega, d)
        mm, piv = rref(rows)
        nc = len(omega)
        free = [c for c in range(nc) if c not in piv]

        # (i) integral with an identity minor on the free columns
        basis = []
        for f in free:
            v = [0] * nc
            v[f] = 1
            good = True
            for r, c in enumerate(piv):
                e = -mm[r][f]
                if e.denominator != 1:
                    ok = False
                    good = False
                    why.append("d=%d: kernel entry %s not integral" % (d, e))
                else:
                    v[c] = int(e)
            if good:
                basis.append(v)
        # the licence must attach to the object E1/E4 actually use
        if [list(b) for b in kernel_basis(rows, nc)] != basis:
            ok = False
            why.append("d=%d: kernel_basis() != identity-minor basis" % d)
        if len(basis) != nc - d:
            ok = False
            why.append("d=%d: %d kernel vectors, want %d"
                       % (d, len(basis), nc - d))

        # (ii) character duality on mu_N, N odd (coprime to every elementary
        # divisor of A, which are 1,2,...,2), by dimension count over F_N.
        # im phi_N = {(<eps,theta>)_eps} = image of A^T, of dimension rank A;
        # ann(Lambda) = null space of the Lambda basis, of dimension nc - rank.
        # im is contained in ann for free ((A m).theta = m.(A^T theta)), so
        # equality is exactly the equality of the two dimensions.
        for N in (5, 7, 11):
            ra = rank_mod(rows, N)
            rl = rank_mod(basis, N) if basis else 0
            if ra != d or rl != nc - d or (nc - rl) != ra:
                ok = False
                why.append("d=%d N=%d: dim im=%d, dim ann=%d"
                           % (d, N, ra, nc - rl))
            for b in basis:
                for k in range(d):
                    if sum(b[j] * int(rows[k][j]) for j in range(nc)) % N:
                        ok = False
                        why.append("d=%d N=%d: im not inside ann" % (d, N))

        # (iii) for the small d, enumerate BOTH sides and compare as sets
        if d in (3, 4):
            N = 7 if d == 3 else 5
            img = set()
            for th in itertools.product(range(N), repeat=d):
                img.add(tuple(sum(e * t for e, t in zip(eps, th)) % N
                              for eps in omega))
            ann = set()
            for u in itertools.product(range(N), repeat=nc):
                if all(sum(b[j] * u[j] for j in range(nc)) % N == 0
                       for b in basis):
                    ann.add(u)
            if img != ann:
                ok = False
                why.append("d=%d N=%d: |im|=%d |ann|=%d, im != ann"
                           % (d, N, len(img), len(ann)))
            exhaustive.append("d=%d,N=%d: |im|=|ann|=%d"
                              % (d, N, len(img)))

    ck("D6_Z_basis_of_Lambda_and_character_duality", ok,
       "the rref kernel basis is integral with an identity minor, equals the "
       "basis E1/E4 evaluate, and has rank 2^(d-1)-d; Lemma 6 holds on mu_N "
       "for N=5,7,11 (dim im = dim ann = d) for d=2..8, and both sides are "
       "enumerated exhaustively for " + "; ".join(exhaustive)
       + ("" if ok else "  FAILURES: " + "; ".join(why[:3])))


# ----------------------------------------------------------------------
# F. THE LOAD-BEARING IDENTITY  H = 4F
# ----------------------------------------------------------------------

def section_F():
    print("--- F. the 2x2x2 quartic: H = 4F ---")
    H, (P, Q, R, S) = build_H()
    F = build_F()

    ok = True
    got = []
    for (nm, re_s, im_s), pol in zip(PAPER_PQRS, (P, Q, R, S)):
        gre, gim = linear_form_str(pol[0]), linear_form_str(pol[1])
        got.append("%s=%s%s(i)" % (nm, gre, gim))
        if gre != re_s or gim != im_s:
            ok = False
    ck("F1_PQRS_match_paper_display", ok,
       "derived from p_eps: " + "; ".join(got))

    ck("F2_H_homogeneous_quartic_40_monomials",
       p_degrees(H) == {4} and len(H) == 40,
       "degrees %s, %d nonzero monomials" % (sorted(p_degrees(H)), len(H)))

    ck("F3_F_homogeneous_quartic_40_monomials",
       p_degrees(F) == {4} and len(F) == 40,
       "degrees %s, %d nonzero monomials" % (sorted(p_degrees(F)), len(F)))

    c = scalar_ratio(H, F)
    ck("F4_H_equals_4F", c == 4 and p_eq(H, p_scal(F, 4)),
       "scalar read off the expansions: H = %s * F, and H - 4F has %d terms"
       % (c, len(p_sub(H, p_scal(F, 4)))))

    ck("F5_coefficients_are_integers",
       all(v.denominator == 1 for v in H.values())
       and all(v.denominator == 1 for v in F.values()),
       "H and F both live in Z[t_ijk]; |coeffs of H| in %s"
       % sorted(set(abs(int(v)) for v in H.values())))

    # H is a proper equation: an explicit rational tensor off the hypersurface
    rng = random.Random(5)
    wit = None
    for _ in range(200):
        t = random_tensor(3, rng)
        if p_eval(H, t) != 0:
            wit = t
            break
    # NB: the failure branch must be reportable.  If no witness exists (H
    # identically zero, say) then formatting a witness would raise and the
    # program would die before printing any verdict, so guard the detail text.
    if wit is None:
        detail = ("no rational tensor with H(T) != 0 was found in 200 draws: "
                  "{H=0} is not a proper hypersurface")
    else:
        detail = ("witness T=%s has H(T)=%s, F(T)=%s"
                  % ([str(v) for v in wit], p_eval(H, wit), p_eval(F, wit)))
    ck("F6_hypersurface_is_proper", wit is not None and p_eval(H, wit) != 0,
       detail)

    # link Prop. 7's H to Theorem 1's Phi_m: H = 8^4 * Phi_g
    ok, n = True, 0
    for _ in range(20):
        t = random_tensor(3, rng)
        if p_eval(H, t) != (1 << 12) * phi_m_value(3, PAPER_OMEGA3,
                                                   PAPER_GEN3, t):
            ok = False
        n += 1
    ck("F7_H_is_8^4_times_Phi_generator", ok,
       "%d random rational tensors, exact; ties Prop. 7 to Theorem 1" % n)

    # Ribot's own quartic vanishes on the orbit of V_{L_2}
    ok, n = True, 0
    for _ in range(40):
        t0 = random_tensor_in_V(3, 0, rng)
        angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(3)]
        t = rotate_all(3, t0, angles)
        if p_eval(F, t) != 0 or p_eval(H, t) != 0:
            ok = False
        n += 1
    ck("F8_F_vanishes_on_the_orbit", ok,
       "%d exact evaluations at SO(2)^3-rotated tensors supported on L_2" % n)


# ----------------------------------------------------------------------
# G. dimension, and the converse inclusion to first order
# ----------------------------------------------------------------------

def infinitesimal_rot(d, t, k):
    """J_k . T with J = [[0,-1],[1,0]]: the derivative of the mode-k rotation"""
    return rotate_mode(d, t, k, Fraction(0), Fraction(1))


def tangent_vectors(d, t0, angles=None):
    """basis of V_{E_0} plus the d orbit directions, pushed by the rotation"""
    vecs = []
    for x in E_delta(d, 0):
        e = [Fraction(0)] * (1 << d)
        e[var_index(x)] = Fraction(1)
        vecs.append(e)
    for k in range(d):
        vecs.append(infinitesimal_rot(d, t0, k))
    if angles is not None:
        vecs = [rotate_all(d, v, angles) for v in vecs]
    return vecs


def section_G():
    print("--- G. dimension and the local converse ---")
    rng = random.Random(99)

    ok, detail = True, []
    for d in range(2, 9):
        want = (1 << (d - 1)) + d
        for _ in range(3):
            t0 = random_tensor_in_V(d, 0, rng)
            vecs = tangent_vectors(d, t0)
            r = rank(vecs)
            # len(vecs) is exactly 2^(d-1)+d, i.e. the target; augment with a
            # dependent vector so the count and the answer differ.
            r_aug = rank(vecs + [[a + b for a, b in zip(vecs[0], vecs[-1])]])
            if r != want or r_aug != want:
                ok = False
        if d <= 5 or d == 8:
            detail.append("d=%d:%d" % (d, want))
    ck("G1_dim_X_E0_is_2^(d-1)_plus_d", ok,
       "exact tangent rank at generic points equals 2^(d-1)+d for "
       "d=2..8 (" + ", ".join(detail) + ")")

    H, _ = build_H()
    grads_nonzero, annihilated, ranks_ok, n = True, True, True, 0
    for _ in range(15):
        t0 = random_tensor_in_V(3, 0, rng)
        angles = [PYTH[rng.randrange(len(PYTH))] for _ in range(3)]
        t = rotate_all(3, t0, angles)
        g = [p_eval(p_diff(H, k), t) for k in range(8)]
        if all(v == 0 for v in g):
            grads_nonzero = False
        vecs = tangent_vectors(3, t0, angles)
        if rank(vecs) != 7 or rank(vecs + [vecs[0]]) != 7:
            ranks_ok = False
        for v in vecs:
            if sum(a * b for a, b in zip(g, v)) != 0:
                annihilated = False
        n += 1
    ck("G2_gradient_of_H_nonzero_on_the_orbit", grads_nonzero,
       "%d orbit points, all with grad H != 0, so {H=0} is smooth of "
       "dimension 7 there" % n)
    ck("G3_orbit_tangent_space_lies_in_ker_dH", annihilated and ranks_ok,
       "at each of %d orbit points the 7-dimensional tangent space of "
       "X_{L_2} is annihilated by dH; with G2 this forces the two "
       "7-dimensional tangent spaces to coincide" % n)

    print("    NOT RE-RUN: Remark 3's identification of X_{E_0} as the "
          "unique top-dimensional component of Ribot's bato variety quotes "
          "Ribot's Lemma 4.5 and Theorem 1.7 and is not re-derived here; "
          "only dim X_{E_0} = 2^(d-1)+d is (check G1).")
    print("    NOT RE-RUN: the reverse inclusion {Phi_m=0} subset X_{E_0} is "
          "NOT verified globally -- deciding orbit membership of a given "
          "rational tensor requires the rotation angles, which are irrational, "
          "so no exact test exists in this arithmetic.  What is verified is "
          "its algebraic engine Lemma 6, exactly and for the paper's own A "
          "(check D6), and the first-order statement along the orbit (G2-G3). "
          "The forward inclusion X_{E_0} subset {Phi_m=0} IS verified globally "
          "and exactly (E1-E4, F8).")


def main():
    print("verify.py -- 'The Maximum Binary Case of Ribot's "
          "Zariski-Closedness Conjecture'")
    print("exact arithmetic only (Fraction / int); standard library only")
    section_A()
    section_B()
    section_C()
    section_D()
    section_D6()
    section_E()
    section_F()
    section_G()
    finish()


if __name__ == "__main__":
    main()
