#!/usr/bin/env python3
"""
Conjecture 5.23 of Acevedo, Blekherman, Debus, Riener (arXiv:2408.04616v1) asserts
    trop(B Sigma_{2d}^*) = T_{2d}^{(2)}   for all d >= 3.
The source paper confirms it for d = 3,4,5, where it gives explicit facet lists (reproduced
below as L_2, L_3, L_4).  SMALLEST DEGREE NOT COVERED BY THOSE CONFIRMATIONS: d = 6
(2d = 12), R^{pi(6)} = R^11, which is the case this program decides.

STRUCTURAL implementation, in HALVED coordinates: index by partitions of d, which is exactly
the source paper's own R^{pi(d)} indexing. Halving parts is an order isomorphism
Lambda^eps_{2d} -> Lambda_d because superdominance compares ascending prefix sums, which
scale, and lengths are preserved.

SIDE A  trop(B Sigma_{2d}^*), presented via the cited rational-polyhedrality and
        tropicalization results for the sums-of-squares cone, generated by:
   type (1)  y_mu >= y_{mu*}         mu = (2a) u la u la, mu* = mu with its TWO LARGEST PARTS MERGED
                                      ONLY when l(a) >= 2 (else the diagonal entry is the single
                                      power sum p_mu, so l_ii^- is EMPTY and the cited
                                      inequality (1) is vacuous: max(empty) = -infinity).
   type (2)  y_{(2a)la la} + y_{(2a')la' la'} >= 2 y_{(a+a')la la'}
                                      ONLY for pairs of terms in the SAME BLOCK of the
                                      block-diagonal matrix M (else L_ij = 0, l_ij empty, vacuous).
   A BLOCK = the set of terms X^a p_la with a FIXED SUPPORT and a FIXED PARITY OF EACH a_i,
   la an even partition (possibly empty), |a| + |la| = d.  This is the block decomposition of
   the partial-symmetry matrix used in the source paper's degree-6 worked case.  Inside a
   block, "same support" and "a+a' even" hold AUTOMATICALLY.
   The terms of a block are COMPOSITIONS, so (1,3) and (3,1) are DISTINCT terms and their 2x2
   block is a genuine generator -- this alignment freedom is essential.

SIDE B  T_{2d}^{(2)}, the second-order superdominance system: y_{b1} + y_{b2} >= 2 y_c for ALL
        even partitions b1,b2,c of 2d with b1.b2 superdominates c.c.

DECISION.  The inclusion T^(2) subset trop(B Sigma^*) is a theorem of the source paper, so
equality fails iff some row g of B is NOT a nonnegative combination of the rows of A.  By
Farkas that is decided exactly, and the infeasibility certificate IS the counterexample: y
with A y >= 0 (so y is in trop) and g . y < 0 (so y violates a T^(2) inequality).  All
arithmetic in Fraction.
"""
import sys
from fractions import Fraction
from itertools import combinations

# ---------------------------------------------------------------- partitions / order

def partitions(n, maxp=None):
    if maxp is None:
        maxp = n
    if n == 0:
        return [()]
    out = []
    for k in range(min(n, maxp), 0, -1):
        for rest in partitions(n - k, k):
            out.append((k,) + rest)
    return out

def even_partitions(n):
    return [p for p in partitions(n) if all(x % 2 == 0 for x in p)]

def asc_prefix(p):
    s = sorted(p)
    out, t = [], 0
    for x in s:
        t += x
        out.append(t)
    return out

def superdom(la, mu):
    """la superdominates mu:  sum of j smallest parts of la <= same for mu, j=1..min(len,len)."""
    A, B = asc_prefix(la), asc_prefix(mu)
    for j in range(min(len(A), len(B))):
        if A[j] > B[j]:
            return False
    return True

def merge_two_largest(mu):
    s = sorted(mu, reverse=True)
    if len(s) < 2:
        return None
    return tuple(sorted([s[0] + s[1]] + s[2:], reverse=True))

def srt(t):
    return tuple(sorted([x for x in t if x > 0], reverse=True))

# ---------------------------------------------------------------- blocks and terms

def blocks(d):
    """All non-empty blocks. Block = (o,e) canonical parity vector: o odd positions then e even
    positions. Terms = compositions a (a_i odd >=1 for the first o, even >=2 for the last e)
    together with an even partition la, |a|+|la| = d.  Returns list of lists of (a, la)."""
    res = []
    for o in range(0, d + 1):
        if (o - d) % 2 != 0:          # |la| even forces |a| == d (mod 2), and |a| == o (mod 2)
            continue
        for e in range(0, d + 1):
            k = o + e
            if o * 1 + e * 2 > d:
                continue
            terms = []
            for a in _compositions(o, e, d):
                rem = d - sum(a)
                if rem < 0 or rem % 2 != 0:
                    continue
                for la in even_partitions(rem):
                    terms.append((a, la))
            if terms:
                res.append(((o, e), terms))
    return res

def _compositions(o, e, d):
    """all tuples length o+e, first o odd>=1, last e even>=2, total <= d"""
    def rec(i, left, cur):
        if i == o + e:
            yield tuple(cur)
            return
        if i < o:
            vals = range(1, left + 1, 2)
        else:
            vals = range(2, left + 1, 2)
        for v in vals:
            # feasibility: remaining minimums
            rem_min = sum(1 for j in range(i + 1, o)) + sum(2 for j in range(max(i + 1, o), o + e))
            if v + rem_min > left:
                continue
            cur.append(v)
            yield from rec(i + 1, left - v, cur)
            cur.pop()
    return rec(0, d, [])

# ---------------------------------------------------------------- generator matrices

def trop_generators(d, include_l1_singletons=False):
    """rows of A as dicts partition->int coefficient, with provenance strings."""
    coords = partitions(d)
    idx = {p: i for i, p in enumerate(coords)}
    rows, prov = [], []
    seen = set()

    def add(vec, why):
        key = tuple(vec)
        if key in seen:
            return
        seen.add(key)
        rows.append(vec)
        prov.append(why)

    for (oe, terms) in blocks(d):
        # ---- type (1), one per term with l(a) >= 2  (halved: mu/2 = a u m u m, m = la/2)
        for (a, la) in terms:
            m = tuple(x // 2 for x in la)
            mu = srt(a + m + m)                      # halved partition of d
            if len(a) < 2 and not include_l1_singletons:
                continue
            star = merge_two_largest(mu)
            if star is None:
                continue
            v = [0] * len(coords)
            v[idx[mu]] += 1
            v[idx[star]] -= 1
            add(v, "type1 block%s a=%s la=%s : y%s >= y%s" % (oe, a, la, mu, star))
        # ---- type (2), one per unordered pair of DISTINCT terms in the same block
        for (t1, t2) in combinations(range(len(terms)), 2):
            (a, la), (ap, lap) = terms[t1], terms[t2]
            m = tuple(x // 2 for x in la)
            mp = tuple(x // 2 for x in lap)
            b1 = srt(a + m + m)
            b2 = srt(ap + mp + mp)
            w = tuple((a[i] + ap[i]) // 2 for i in range(len(a)))     # (a+a')/2, even inside a block
            assert all((a[i] + ap[i]) % 2 == 0 for i in range(len(a)))
            c = srt(w + m + mp)
            v = [0] * len(coords)
            v[idx[b1]] += 1
            v[idx[b2]] += 1
            v[idx[c]] -= 2
            if all(x == 0 for x in v):
                continue
            add(v, "type2 block%s (a=%s,la=%s)x(a=%s,la=%s) : y%s + y%s >= 2y%s"
                % (oe, a, la, ap, lap, b1, b2, c))
    return coords, rows, prov

def T2_generators(d):
    coords = partitions(d)
    idx = {p: i for i, p in enumerate(coords)}
    rows, prov = [], []
    seen = set()
    for (b1, b2) in [(x, y) for i, x in enumerate(coords) for y in coords[i:]]:
        for c in coords:
            if not superdom(srt(b1 + b2), srt(c + c)):
                continue
            v = [0] * len(coords)
            v[idx[b1]] += 1
            v[idx[b2]] += 1
            v[idx[c]] -= 2
            if all(x == 0 for x in v):
                continue
            key = tuple(v)
            if key in seen:
                continue
            seen.add(key)
            rows.append(v)
            prov.append("T2: y%s + y%s >= 2y%s" % (b1, b2, c))
    return coords, rows, prov

# ---------------------------------------------------------------- exact rational LP (Farkas)

def in_cone(A, g):
    """Is g a nonnegative combination of the rows of A?  A: list of int vectors (len n).
    Returns (True, lam) or (False, y) with y such that A y >= 0 (componentwise) and g.y < 0.
    Exact Fraction phase-1 simplex, Bland's rule (no cycling)."""
    m = len(A)
    n = len(g)
    # constraints  M lam = g,  M = A^T  (n x m)
    M = [[Fraction(A[j][i]) for j in range(m)] for i in range(n)]
    rhs = [Fraction(x) for x in g]
    sign = [1] * n
    for i in range(n):
        if rhs[i] < 0:
            sign[i] = -1
            rhs[i] = -rhs[i]
            M[i] = [-x for x in M[i]]
    # tableau: columns 0..m-1 lam, m..m+n-1 artificials, then rhs
    T = [M[i] + [Fraction(1 if k == i else 0) for k in range(n)] + [rhs[i]] for i in range(n)]
    basis = [m + i for i in range(n)]
    # objective row: reduced costs for min sum(artificials)
    obj = [Fraction(0)] * (m + n + 1)
    for j in range(m + n):
        obj[j] = -sum(T[i][j] for i in range(n)) if j < m else Fraction(0)
    zval = sum(rhs)
    it = 0
    while True:
        it += 1
        if it > 20000:
            raise RuntimeError("simplex iteration cap")
        piv_col = -1
        for j in range(m + n):
            if obj[j] < 0:
                piv_col = j
                break                      # Bland: lowest index
        if piv_col < 0:
            break
        piv_row, best = -1, None
        for i in range(n):
            if T[i][piv_col] > 0:
                r = T[i][-1] / T[i][piv_col]
                if best is None or r < best or (r == best and basis[i] < basis[piv_row]):
                    best, piv_row = r, i
        if piv_row < 0:
            raise RuntimeError("unbounded in phase 1 (impossible)")
        p = T[piv_row][piv_col]
        T[piv_row] = [x / p for x in T[piv_row]]
        for i in range(n):
            if i != piv_row and T[i][piv_col] != 0:
                f = T[i][piv_col]
                T[i] = [T[i][k] - f * T[piv_row][k] for k in range(m + n + 1)]
        f = obj[piv_col]
        if f != 0:
            obj = [obj[k] - f * T[piv_row][k] for k in range(m + n + 1)]
        basis[piv_row] = piv_col
        zval = sum(T[i][-1] for i in range(n) if basis[i] >= m)
    if zval == 0:
        lam = [Fraction(0)] * m
        for i in range(n):
            if basis[i] < m:
                lam[basis[i]] = T[i][-1]
        return True, lam
    # infeasible: pi_i = 1 - reduced cost of artificial i ; y = -sign*pi  (so A y >= 0, g.y < 0)
    pi = [Fraction(1) - obj[m + i] for i in range(n)]
    y = [-sign[i] * pi[i] for i in range(n)]
    return False, y

def check_witness(A, g, y):
    ok_cone = all(sum(A[j][i] * y[i] for i in range(len(y))) >= 0 for j in range(len(A)))
    val = sum(g[i] * y[i] for i in range(len(y)))
    return ok_cone, val

# ---------------------------------------------------------------- published data (halved)

L = {
 2: [("y(1,1) >= y(2)", {(1, 1): 1, (2,): -1})],
 3: [("y(1,1,1)+y(3) >= 2y(2,1)", {(1, 1, 1): 1, (3,): 1, (2, 1): -2}),
     ("y(2,1) >= y(3)", {(2, 1): 1, (3,): -1})],
 4: [("y(1^4)+y(2,2) >= 2y(2,1,1)", {(1, 1, 1, 1): 1, (2, 2): 1, (2, 1, 1): -2}),
     ("y(2,1,1)+y(4) >= 2y(3,1)", {(2, 1, 1): 1, (4,): 1, (3, 1): -2}),
     ("y(3,1) >= y(2,2)", {(3, 1): 1, (2, 2): -1}),
     ("y(2,2) >= y(4)", {(2, 2): 1, (4,): -1})],
 5: [("y(3,1,1) >= y(2,2,1)", {(3, 1, 1): 1, (2, 2, 1): -1}),
     ("y(4,1) >= y(3,2)", {(4, 1): 1, (3, 2): -1}),
     ("y(3,2) >= y(5)", {(3, 2): 1, (5,): -1}),
     ("y(3,1,1)+y(5) >= 2y(4,1)", {(3, 1, 1): 1, (5,): 1, (4, 1): -2}),
     ("y(2,2,1)+y(5) >= 2y(3,2)", {(2, 2, 1): 1, (5,): 1, (3, 2): -2}),
     ("y(2,2,1) >= y(4,1)", {(2, 2, 1): 1, (4, 1): -1}),
     ("y(2,1,1,1)+y(3,2) >= 2y(2,2,1)", {(2, 1, 1, 1): 1, (3, 2): 1, (2, 2, 1): -2}),
     ("y(2,1,1,1)+y(4,1) >= 2y(3,1,1)", {(2, 1, 1, 1): 1, (4, 1): 1, (3, 1, 1): -2}),
     ("y(1^5)+y(2,2,1) >= 2y(2,1,1,1)", {(1, 1, 1, 1, 1): 1, (2, 2, 1): 1, (2, 1, 1, 1): -2})],
}
# the total order on partitions of 5 recorded in the source paper (halved coordinates give the
# same statement on Lambda_5)
CHAIN5 = [(1, 1, 1, 1, 1), (2, 1, 1, 1), (3, 1, 1), (2, 2, 1), (4, 1), (3, 2), (5,)]
# recorded in the source paper: valid on trop(BP_10^*), NOT valid on trop(BSigma_10^*)
EXTRA_BP10 = {(1, 1, 1, 1, 1): 1, (3, 2): 1, (4, 1): 1, (3, 1, 1): -3}

def densify(d, dct):
    coords = partitions(d)
    idx = {p: i for i, p in enumerate(coords)}
    v = [0] * len(coords)
    for p, c in dct.items():
        v[idx[p]] += c
    return v

# ---------------------------------------------------------------- controls

def control_chain():
    print("[CTRL-1 published total order on partitions of 5]")
    ok = True
    for i in range(len(CHAIN5) - 1):
        a, b = CHAIN5[i], CHAIN5[i + 1]
        s = superdom(a, b) and not superdom(b, a)
        ok = ok and s
        print("   %s succ %s : %s" % (a, b, s))
    tot = all(superdom(x, y) or superdom(y, x) for x in partitions(5) for y in partitions(5))
    print("   total order on Lambda_5 : %s  (paper: yes)" % tot)
    bad = [(x, y) for x in partitions(6) for y in partitions(6)
           if not superdom(x, y) and not superdom(y, x)]
    print("   Lambda_6 incomparable pairs : %d  (paper: not a total order for d>=6)" % (len(bad) // 2))
    print("   e.g. %s" % (bad[:6],))
    print("   CTRL-1 %s" % ("PASS" if (ok and tot and bad) else "FAIL"))
    return ok and tot and bool(bad)

def control_published_facets(d, singletons):
    coords, A, provA = trop_generators(d, singletons)
    okall = True
    for (name, dct) in L[d]:
        g = densify(d, dct)
        f, cert = in_cone(A, g)
        if not f:
            okall = False
        print("   L_%d member in cone(A): %-42s %s" % (d - 1, name, f))
    Lrows = [densify(d, dct) for (_, dct) in L[d]]
    for j, r in enumerate(A):
        f, cert = in_cone(Lrows, r)
        if not f:
            okall = False
            print("   *** A row NOT implied by published L_%d: %s" % (d - 1, provA[j]))
    print("   CTRL-2 d=%d (|A|=%d, singleton-type1=%s): %s"
          % (d, len(A), singletons, "PASS (cones equal)" if okall else "FAIL"))
    return okall

def control_forced_positive(d, singletons):
    """(a) reversed strict order inequality must be REFUSED with a verified witness
       (b) published trop(BP_10^*) extra facet must be REFUSED at d=5"""
    coords, A, provA = trop_generators(d, singletons)
    ok = True
    # (a) find a strict superdominance pair and reverse it
    ps = partitions(d)
    for x in ps:
        for y in ps:
            if x != y and superdom(x, y):
                g = [0] * len(ps)
                g[ps.index(y)] += 1
                g[ps.index(x)] -= 1        # y_y >= y_x  -- must NOT be valid
                f, cert = in_cone(A, g)
                if f:
                    print("   *** FORCED-POSITIVE FAILED: reversed %s>=%s accepted" % (y, x))
                    ok = False
                else:
                    c1, val = check_witness(A, g, cert)
                    if not (c1 and val < 0):
                        print("   *** witness verification failed on reversed pair")
                        ok = False
                break
        break
    print("   CTRL-3a reversed-order inequality refused with verified witness: %s" % ok)
    if d == 5:
        g = densify(5, EXTRA_BP10)
        f, cert = in_cone(A, g)
        if f:
            print("   *** CTRL-3b FAILED: published trop(BP_10^*)-only facet accepted on trop(BSigma_10^*)")
            ok = False
        else:
            c1, val = check_witness(A, g, cert)
            print("   CTRL-3b published trop(BP_10^*) extra facet y(1^5)+y(3,2)+y(4,1) >= 3y(3,1,1)"
                  " refused: True; witness verified: %s, value %s" % (c1, val))
            print("      witness y = %s" % dict(zip(partitions(5), cert)))
            ok = ok and c1 and val < 0
    return ok

def control_proved_inclusion(d, singletons):
    """The source paper's theorem T^(2) subset trop, i.e. EVERY row of A is implied by B."""
    coords, A, provA = trop_generators(d, singletons)
    _, B, provB = T2_generators(d)
    bad = []
    for j, r in enumerate(A):
        f, _ = in_cone(B, r)
        if not f:
            bad.append(provA[j])
    print("   CTRL-4 d=%d PROVED inclusion T^(2) subset trop  (|A|=%d,|B|=%d): %s"
          % (d, len(A), len(B), "PASS" if not bad else "FAIL"))
    for b in bad[:8]:
        print("      *** A row not implied by T^(2): %s" % b)
    return not bad

# ---------------------------------------------------------------- main decision

def decide(d, singletons):
    coords, A, provA = trop_generators(d, singletons)
    _, B, provB = T2_generators(d)
    print("=== DECIDE d=%d : |coords|=%d  |A(trop gens)|=%d  |B(T2 gens)|=%d  singleton-type1=%s"
          % (d, len(coords), len(A), len(B), singletons))
    viol = []
    for j, g in enumerate(B):
        f, cert = in_cone(A, g)
        if not f:
            ok, val = check_witness(A, g, cert)
            viol.append((provB[j], cert, ok, val))
    print("    T^(2) generators tested: %d / %d  (EXHAUSTION = %d/%d = 1)"
          % (len(B), len(B), len(B), len(B)))
    print("    NOT implied by trop's generators: %d" % len(viol))
    for (why, cert, ok, val) in viol[:12]:
        print("    *** %s" % why)
        print("        witness verified in trop: %s   value g.y = %s" % (ok, val))
        print("        y = %s" % dict(zip(coords, cert)))
    return len(A), len(B), viol, coords, A, provA

if __name__ == "__main__":
    singletons = (len(sys.argv) > 1 and sys.argv[1] == "singletons")
    print("#### CONTROLS")
    c1 = control_chain()
    c2 = all(control_published_facets(d, singletons) for d in (2, 3, 4, 5))
    c3 = control_forced_positive(5, singletons)
    c4 = all(control_proved_inclusion(d, singletons) for d in (3, 4, 5, 6))
    print("#### SUMMARY OF CONTROLS chain=%s publishedfacets=%s forcedpos=%s provedincl=%s"
          % (c1, c2, c3, c4))
    print("#### NEGATIVE CONTROLS: published equality at d=3,4,5 must give ZERO violations")
    for d in (3, 4, 5):
        decide(d, singletons)
    print("#### DEGREE d=6, THE SMALLEST CASE THE SOURCE PAPER DOES NOT SETTLE")
    nA, nB, viol, coords, A, provA = decide(6, singletons)
    print("#### trop(BSigma_12^*) GENERATOR LIST (halved coords, partitions of 6)")
    for p in provA:
        print("    " + p)
    print("=== END OF RUN")
